### PR TITLE
MNG-5889 - adding logic that looks for the file argument and starts t…

### PR DESCRIPTION
**Pull request by rpatrick00**
…he search for the .mvn directory at the location of the specified POM when present

### CODE REVIEW

**Comment by rpatrick00** [comment]
Fixing a small problem...will resubmit

**Comment by jochenw** [comment]
I wonder, whether this couldn't be handled at the Java level? If so, there would be no need to change script files, making them even more complex than they already are.

**Comment by rpatrick00** [comment]
Because the maven shell scripts are finding the .mvn directory before starting java in order to find the relevant .mvn/jvm.config to process any java command-line options that may be found in it.  This location is passed into the Java process so that the Java code does not look for the .mvn directory again...

**Comment by jochenw** [comment]
Then possibly a good first step would be to move that logic from the scripts to the Java Main class.

**Comment by rpatrick00** [comment]
Did you not understand what I said?

.mvn/jvm.config might look like this:

-Xmx2048m 
-Xms1024m 
-XX:MaxPermSize=512m 
-Djava.awt.headless=true

If I move the processing of that file into Java, how am I going to set those options on the Java command-line used to start Maven?

**Comment by Tibor17** [comment]
IIUC this might be useful in CI because you may run `mvn deploy -f /path/to/project/pom.xml` and the discovery would be made in `/path/to/project/.mvn` as well. AFAIK Maven is not 2 processes running but one and you need to pass jvm options like this then.

**Comment by aheritier** [comment]
+1000 for this change (as far as it is tested/validated)
This problem of using -f on CI servers (and non only) is very common and it makes the usage of .mvn folders useless.
The problem is to be sure that we are fixing this for linux and windows

**Comment by rpatrick00** [comment]
I tested this on both Linux and Windows, but most of the testing was on Windows simply because Windows CMD scripts are challenging to get right.  The sh script is much simpler...

**Comment by Tibor17** [comment]
I want to test it as well and then push it to master.

**Comment by Tibor17** [comment]
@rpatrick00 pls squash it to one commit.

**Comment by rpatrick00** [comment]
Submitting a new pull request...

https://github.com/apache/maven/pull/94

**Comment by rpatrick00** [comment]
@Tibor17, have you looked at the pull request?  Any issues with merging it?

**Comment by jira-importer** [comment]
Resolve #7889

**Pull request closed without merging**
