### PR TITLE
[MNG-8178] Fall back to System.getProperty for missing context props

### PR DESCRIPTION
**Pull request by kohlschuetter**
A call to context.getSystemProperties() may yield empty an empty map, or one missing the desired key, which makes a subsequent call of toLowerCase fail with a NullPointerException.

Fall-back to using System.getProperty (with an empty default, in case that one fails too).

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`,
       where you replace `MNG-XXX` and `SUMMARY` with the appropriate JIRA issue.
 - [x] Also format the first line of the commit message like `[MNG-XXX] SUMMARY`.
       Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
We should try to find root cause ... why properties is not available in contexts

**Comment by kohlschuetter** [comment]
@slawekjaranowski DefaultProfileActivationContext.setSystemProperties allows empty/null system properties (the default value if setSystemProperties isn't called is an empty map, too). Moreover, I don't think we can make any assumptions on "os.name", etc., to be available.

As to where this from: I've added an exception to `DefaultProfileActivationContext` that checks for empty property maps, and this is what I get
```
    at org.apache.maven.model.profile.DefaultProfileActivationContext.setSystemProperties (DefaultProfileActivationContext.java:108)
    at org.apache.maven.model.building.DefaultModelBuilder.getProfileActivationContext (DefaultModelBuilder.java:661)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:265)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:247)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:176)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:123)
    at org.apache.maven.report.projectinfo.ModulesReport$ModulesRenderer.renderBody (ModulesReport.java:174)
    at org.apache.maven.reporting.AbstractMavenReportRenderer.render (AbstractMavenReportRenderer.java:82)
    at org.apache.maven.report.projectinfo.ModulesReport.executeReport (ModulesReport.java:75)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:289)
    at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:198)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:298)
    at org.apache.maven.plugins.site.render.SiteMojo.renderNonDoxiaDocuments (SiteMojo.java:280)
    at org.apache.maven.plugins.site.render.SiteMojo.renderLocale (SiteMojo.java:162)
    at org.apache.maven.plugins.site.render.SiteMojo.execute (SiteMojo.java:115)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke (Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
```

**Comment by cstamas** [comment]
```
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:298)
```
?

You are building a site here? As we have related issue https://issues.apache.org/jira/browse/DOXIASITETOOLS-343 that may be related...

**Comment by kohlschuetter** [comment]
@cstamas fwiw, I'm seeing this with 3.9.7/3.9.8. The behavior of the site tools probably was like this long before, but the bug is only triggered due to changes made with [MNG-5726](https://issues.apache.org/jira/browse/MNG-5726)

**Comment by kohlschuetter** [comment]
Bug description here https://issues.apache.org/jira/browse/MNG-8135

**Comment by gnodet** [comment]
> @slawekjaranowski DefaultProfileActivationContext.setSystemProperties allows empty/null system properties (the default value if setSystemProperties isn't called is an empty map, too). Moreover, I don't think we can make any assumptions on "os.name", etc., to be available.
> 
> As to where this from: I've added an exception to `DefaultProfileActivationContext` that checks for empty property maps, and this is what I get
> 
> ```
>     at org.apache.maven.model.profile.DefaultProfileActivationContext.setSystemProperties (DefaultProfileActivationContext.java:108)
>     at org.apache.maven.model.building.DefaultModelBuilder.getProfileActivationContext (DefaultModelBuilder.java:661)
>     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:265)
>     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:247)
>     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:176)
>     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:123)
>     at org.apache.maven.report.projectinfo.ModulesReport$ModulesRenderer.renderBody (ModulesReport.java:174)
>     at org.apache.maven.reporting.AbstractMavenReportRenderer.render (AbstractMavenReportRenderer.java:82)
>     at org.apache.maven.report.projectinfo.ModulesReport.executeReport (ModulesReport.java:75)
>     at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:289)
>     at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:198)
>     at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:298)
>     at org.apache.maven.plugins.site.render.SiteMojo.renderNonDoxiaDocuments (SiteMojo.java:280)
>     at org.apache.maven.plugins.site.render.SiteMojo.renderLocale (SiteMojo.java:162)
>     at org.apache.maven.plugins.site.render.SiteMojo.execute (SiteMojo.java:115)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
>     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
>     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
>     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
>     at java.lang.reflect.Method.invoke (Method.java:580)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
> ```

The assumption is not `context.getSystemProperties()` returns... system properties.  So imho, the PR is wrong and it means the caller does not set the system properties correctly.  In Maven itself, the only place is in `DefaultModelBuilder`, where properties are set correctly afaik.  So the bug is that the system properties are not correctly set on the request:
https://github.com/apache/maven-project-info-reports-plugin/blob/master/src/main/java/org/apache/maven/report/projectinfo/ModulesReport.java#L160-L162

**Review by gnodet — CHANGES_REQUESTED** [review]
The assumption is not context.getSystemProperties() returns... system properties. So imho, the PR is wrong and it means the caller does not set the system properties correctly. In Maven itself, the only place is in DefaultModelBuilder, where properties are set correctly afaik. So the bug is that the system properties are not correctly set on the request:
https://github.com/apache/maven-project-info-reports-plugin/blob/master/src/main/java/org/apache/maven/report/projectinfo/ModulesReport.java#L160-L162

This is a problem in `maven-project-info-reports-plugin` and should be fixed there imho.

**Comment by kohlschuetter** [comment]
@gnodet I see. Can you please coordinate this? I'm just a frustrated user. Thanks a lot!

**Comment by gnodet** [comment]
We could mitigate the issue by supporting null values though instead of calling `toLowerCase()` on the maybe null property.

**Comment by kohlschuetter** [comment]
@gnodet By just "handling" null values (e.g., converting to ""), we wouldn't get the correct "active" state for profiles based on the OS.

I really don't see what we'd lose by falling back to `System.getProperty`.

**Comment by kohlschuetter** [comment]
@gnodet Moreover, this is a regression from 3.9.6. Who knows, maybe more plugins are affected by this.

**Comment by gnodet** [comment]
> @gnodet Moreover, this is a regression from 3.9.6. Who knows, maybe more plugins are affected by this.

Ah, I see now.
We're trying to chase down the calls to `System.getProperty`, so can we rather use the following instead:
```
        String actualOsName = context.getSystemProperties().getOrDefault("os.name", Os.OS_NAME).toLowerCase(Locale.ENGLISH);
        String actualOsArch = context.getSystemProperties().getOrDefault("os.arch", Os.OS_ARCH).toLowerCase(Locale.ENGLISH);
        String actualOsVersion = context.getSystemProperties().getOrDefault("os.version", Os.OS_VERSION).toLowerCase(Locale.ENGLISH);
```
It should have the desired behaviour without introducing new calls.

**Review by gnodet — APPROVED** [review]

**Comment by michael-o** [comment]
Am I stupid or why are these props empty?

**Comment by gnodet** [comment]
> Am I stupid or why are these props empty?

Look at https://github.com/apache/maven-project-info-reports-plugin/pull/75

**Review by cstamas — APPROVED** [review]

**Comment by michael-o** [comment]
> > Am I stupid or why are these props empty?
> 
> Look at [apache/maven-project-info-reports-plugin#75](https://github.com/apache/maven-project-info-reports-plugin/pull/75)

Nice catch, let me please review all reporting plugins before we merge this. I do remember some other stuff.

**Review by slawekjaranowski — APPROVED** [review]

**Review by michael-o — APPROVED** [review]
Fine with me, will continue on the fix in MPIR.

**Comment by jira-importer** [comment]
Resolve #9817

**Pull request merged**
