### PR TITLE
[MNG-6825] Replace FileUtils with Commons IO

### PR DESCRIPTION
**Pull request by timtebeek**
For: https://issues.apache.org/jira/browse/MNG-6825

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`,
       where you replace `MNG-XXX` and `SUMMARY` with the appropriate JIRA issue.
 - [x] Also format the first line of the commit message like `[MNG-XXX] SUMMARY`.
       Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by timtebeek** [comment]
This PR was largely created through: https://github.com/timtebeek/maven-rewrite/blob/main/file-utils.yml

It's not yet a complete migration, as [a few cases need dedicated recipes](https://github.com/timtebeek/maven-rewrite/blob/0f80732db3959183d171e451f8c9284e9bedb99d/file-utils.yml#L47-L59), or manual work to convert completely, depending on how much they are used.

**Comment by gnodet** [comment]
Could we just switch to the nio api which provides a bunch of helper methods ?  I'd rather remove dependencies than adding one....

**Comment by michael-o** [comment]
> Could we just switch to the nio api which provides a bunch of helper methods ? I'd rather remove dependencies than adding one....

I think yes, with a little bit of effort.

**Comment by elharo** [comment]
Not everything in this PR is covered by NIO in Java 8. As of Java 11 though we should be able to remove most uses of Apache Commons IO too.

**Review by elharo — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #8219

**Pull request merged**
