### PR TITLE
[MNG-7827] Ensure maven 4 Log API is the primary and documented API for mojos

### PR DESCRIPTION
**Pull request by rmannibucau**
Following this checklist to help us incorporate your
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MNG-XXX] SUMMARY`,
       where you replace `MNG-XXX` and `SUMMARY` with the appropriate JIRA issue.
 - [X] Also format the first line of the commit message like `[MNG-XXX] SUMMARY`.
       Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by gnodet** [comment]
@rmannibucau not sure what the point of this PR is.  I would not force 3.x plugins to use the maven 4 api, I think it's better to keep it for 4.x plugins.

**Comment by rmannibucau** [comment]
@gnodet there are two goals:

1. Drop the irrelevant documentation we never agreed upon to use SLF4J (api) for plugins
2. Ensure the default is the actual maven logging system and not stdout/stderr directly for other cases if it is present

v4 API is more a way to do the bridge easily and with less internal efforts (since it is hidden anyway)

**Comment by gnodet** [comment]
> 2. Ensure the default is the actual maven logging system and not stdout/stderr directly for other cases if it is present

I don't understand the actual use case.  All mojos called by maven are [injected with a proper log](https://github.com/apache/maven/blob/e08c95a6735a82c7abc25e2dc67ea4773ed9d05d/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java#L557-L560) already.  The `SystemStreamLog` is really a fallback.  In which case would this new code actually be used ?

**Comment by rmannibucau** [comment]
@gnodet good for me too, I wondered about this point too and if true we should delete SystemStreamLog and just fail instead probably. If useful it means we must forward the fallback to the actual expected logging system behind `Log` and now it is v4 mecanism thanks new `Log` API, this was the intent behind this PR but happy to just drop it too cause I share your reasoning.

**Comment by cstamas** [comment]
> 1. Drop the irrelevant documentation we never agreed upon to use SLF4J (api) for plugins

Then your memory is lossy :smile: 
See https://lists.apache.org/thread/bh9vr9fwt2cqf3ltg88jm1fh5y0d57b0

Please, stop with this "change the logging..." madness.

**Comment by rmannibucau** [comment]
@cstamas this is only one of the 4-5 explaining why we must not leak our default impl and where we didnt find an agreement in terms of api leak yes.
Note we dont want to change the logging, just keep the one we had and fix the bug introduced in the javadoc which doesnt reflects discussion outcomes.
Technically, there are multiple cons leaking slf4j but community wise a vote wouldnt pass but in force so both are bad.
Last is that maven didnt migrate its api to slf4j in plugin - never, we miss several steps to say it is done so current absusive comment is even wrong - so let's fix it, will impact nobody as of today and not mislead mojo dev.

**Comment by gnodet** [comment]
Closing as duplicate of #793

**Comment by slawekjaranowski** [comment]
source branch deleted

**Comment by jira-importer** [comment]
Resolve #9092

**Comment by slawekjaranowski** [comment]
@rmannibucau how it corresponding to 3.10.0 version?

**Comment by rmannibucau** [comment]
@slawekjaranowski hmm no more sure but guess plan was to backport but was not done cause lack of time/holidays

**Pull request closed without merging**
