### PR TITLE
[MNG-7445]  Refactoring, remove the useless line

### PR DESCRIPTION
**Pull request by Gakiii**
Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by Gakiii** [comment]
i think the “return” can be written in the last line

**Review by gnodet — APPROVED** [review]

**Review by mthmulders — APPROVED** [review]

**Comment by mthmulders** [comment]
Thanks for your contribution, @Gakiii!

Two remaining things:
1. Would it be possible for you to explicitly declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)? There's a checkbox for that in the PR template.
1. Also, there is no JIRA ticket for this refactoring. Would it be possible for you to create one?

**Comment by Gakiii** [comment]
> Thanks for your contribution, @Gakiii!
> 
> Two remaining things:
> 
> 1. Would it be possible for you to explicitly declare this contribution to be licensed under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)? There's a checkbox for that in the PR template.
> 2. Also, there is no JIRA ticket for this refactoring. Would it be possible for you to create one?

of course.
For the first thing, I have checked the checkbox.
For the second thing, I created a JIRA question, but cause this is the first time I contribution code to Maven, I don't know the detail how to do this.
Could you help me? 
I create the[MNG-7445] for this PR, what should I do next step?

**Comment by Gakiii** [comment]
@gnodet

**Comment by Gakiii** [comment]
@gnodet  
I created a JIRA ticket, and linked to this PR.
Could you tell me if I  did the right thing？

**Comment by khmarbaise** [comment]
Thank you for your contribution. The change has been merged into 
 * master - d92538b80f302fc40530468efe7ca7bf63b7ba52
 * maven-3.8.x - 69bde0b901f983117032f674a3701d6a6eb4b716
 * maven-3.9.x - f7b073f3eb88e4e82d5ec10a91d2bf6b442c03c6

**Pull request closed without merging**
