### PR TITLE
[MNG-7820] Get rid of plexus-utils introspection classes

### PR DESCRIPTION
**Pull request by gnodet**
Use maven-shared-utils reflection classes.

### CODE REVIEW

**Comment by gnodet** [comment]
I think I can also remove the copyright because the code has already been donated to the ASF as those classes also exist [in maven-shared-utils](https://github.com/apache/maven-shared-utils/tree/master/src/main/java/org/apache/maven/shared/utils/introspection)...
@elharo do you agree ?

**Review by michael-o — COMMENTED** [review]
No opinion here.

**Comment by elharo** [comment]
I'm sorry. IANAL and I simply don't know. We need an official ruling from someone in a position at the Apache project to offer legal advice and make decisions like this.

**Comment by gnodet** [comment]
> I'm sorry. IANAL and I simply don't know. We need an official ruling from someone in a position at the Apache project to offer legal advice and make decisions like this.

Well, it was really a courtesy question.  I'll use the maven-shared-utils copy of those classes which are already in the ASF so definitely no copyright / legal issue.

**Review by cstamas — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #9100

**Pull request merged**
