### PR TITLE
[MNG-7324] switch from JAXB to Modello

### PR DESCRIPTION
**Pull request by hboutemy**

### CODE REVIEW

**Comment by gnodet** [comment]
@hboutemy  I've pushed additional commits to https://github.com/apache/maven/pull/604, getting rid of jaxb and fixing other bugs.

**Comment by hboutemy** [comment]
@AlexanderAshitkin @gnodet ok to merge this to MNG-7129 branch?

**Comment by gnodet** [comment]
> @AlexanderAshitkin @gnodet ok to merge this to [MNG-7129](https://issues.apache.org/jira/browse/MNG-7129) branch?

+1 for me, fwiw the doc will have to be updated at some point

**Comment by hboutemy** [comment]
@gnodet doc updated and models split to different Java packages corresponding to XML filenames

**Comment by gnodet** [comment]
> @gnodet doc updated and models split to different Java packages corresponding to XML filenames

I'd like to change the package names from `buildinfo` to `build` and `buildsdiff` to `diff`.  Thoughts ?

Also, I'm not really sure it makes sense to work on several branches to actually create a branch that will be eventually merged to master.  Should we simply commit to the original `MNG-7129` branch ?

**Comment by gnodet** [comment]
Superseded by #607

**Comment by hboutemy** [comment]
@gnodet 
> I'd like to change the package names from buildinfo to build and buildsdiff to diff. Thoughts ?
No problem for me: I'm like you, I'm discovering, reading and trying to improve namings to better match what I think I understood
this is where I'd love to have feedback from initial developers

> Also, I'm not really sure it makes sense to work on several branches...
we are defining/discovering how to work together: I like you idea on Jira sub-tasks, for example
On branches, I expected that we would manage to have feedback earlier, then merge to initial branch faster: I completely agree with you that it does not make sense to add many branches if we don't merge somewhere
let's continue on #607

**Pull request closed without merging**
