### PR TITLE
Add ModelSource test for MNG-5669

### PR DESCRIPTION
**Pull request by michael-o**
@mickaelistria Please have a look.

### CODE REVIEW

**Comment by mickaelistria** [comment]
That seems good, and I'd really like to see this case covered in next Maven major; so +1 for merging it!

**Review by olamy — APPROVED** [review]

**Comment by michael-o** [comment]
Will merge soon

**Comment by rfscholte** [comment]
My wish is to deprecate and finally remove `model.getPomFile()`: one should use MavenProject to ask for the pom file. In Maven 3 it was used as the key for the model, but with the Maven 4 code that's not required anymore. The mdo-file also demonstrates it is a weird field: it is not part of the ModelReader.
Having this test as long as this field is there is fine.

**Comment by mickaelistria** [comment]
> My wish is to deprecate and finally remove model.getPomFile():

IIRC, the issue is (or was) that the pomFile wasn't set on project if it's not set on the model. But I agree with your analysis that model shouldn't even have to reference the pom file, and this is more the duty of ProjectBuilder.
Basically, the lines that are setting pomFile in the Model when `source instanceof FileModelSource` would have to be placed in ProjectBuilder. I remember I tried that but ProjectBuilder was harder to tweak back then.

**Comment by jira-importer** [comment]
Resolve #6664

**Pull request closed without merging**
