### PR TITLE
[MNG-7172] Exclude JAnsi native library for MacOS

### PR DESCRIPTION
**Pull request by rfscholte**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by mthmulders — CHANGES_REQUESTED** [review]
I've downloaded both the tar.gz and the zip from [Jenkins](https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven/job/MNG-7172/lastSuccessfulBuild/artifact/org/apache/maven/apache-maven/4.0.0-alpha-1-SNAPSHOT/) and extracted them.

Both still have the JAnsi native library in them:

```/tmp/targz $ find apache-maven/lib/jansi-native/Mac
apache-maven/lib/jansi-native/Mac
apache-maven/lib/jansi-native/Mac/x86
apache-maven/lib/jansi-native/Mac/x86/libjansi.jnilib
apache-maven/lib/jansi-native/Mac/x86_64
apache-maven/lib/jansi-native/Mac/x86_64/libjansi.jnilib
```

```/tmp/zip $ find apache-maven/lib/jansi-native/Mac
apache-maven/lib/jansi-native/Mac
apache-maven/lib/jansi-native/Mac/x86
apache-maven/lib/jansi-native/Mac/x86/libjansi.jnilib
apache-maven/lib/jansi-native/Mac/x86_64
apache-maven/lib/jansi-native/Mac/x86_64/libjansi.jnilib
```

I'm afraid somehow these changes do not have the expected effect.

**Comment by rfscholte** [comment]
I was looking at the jansi-native library of Maven 3.8.1, but the structure has changed. Will fix it.

**Comment by michael-o** [comment]
It is "macOS", "OSX" is dead for a very long time.

**Review by michael-o — APPROVED** [review]
One remaining nit and that's it.

**Comment by mthmulders** [comment]
Checked the .zip and the .tar.gz archive, they look fine: no jnilib files present.

**Review by gnodet — APPROVED** [review]

**Review by michael-o — APPROVED** [review]

**Comment by rfscholte** [comment]
Merged with https://github.com/apache/maven/commit/6bed162a65bcd2f8ab481ed3c938b83814cb550d

**Comment by jira-importer** [comment]
Resolve #8283

**Pull request closed without merging**
