### PR TITLE
[MNG-7173] The maven-resolver-provider:MavenResolverModule is broken

### PR DESCRIPTION
**Pull request by cstamas**
It is broken since 3.6.2 or so, when ModelBuilder got decorated with
JSR330 injections, that work in sisu but not in Guice as it needs
explicit bindings added.

This is an UT that proves that module is incomplete.

### CODE REVIEW

**Comment by cstamas** [comment]
As expected, newly added UT fails:
```
Error:  Errors: 
Error:    MavenResolverModuleTest.smokeTest:31 » Creation Unable to create injector, see...
[INFO] 
Error:  Tests run: 28, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by cstamas** [comment]
Related: after https://issues.apache.org/jira/browse/MNG-6685 the Guice module was not updated.

**Comment by cstamas** [comment]
This PR is defunct, Guice modules were removed in https://github.com/apache/maven/pull/1282

**Comment by jira-importer** [comment]
Resolve #8282

**Pull request closed without merging**
