### PR TITLE
[MNG-7285] - Test showcasing regression

### PR DESCRIPTION
**Pull request by mickaelistria**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by famod** [comment]
Btw, I might have an idea on how to solve MNG-6843 with a different approach, isolated to `MojoExecutor`.
It won't be pretty (_if_ it works at all), but it should be less invasive than the TL in MavenProject (or a "proper" refactoring like #475).

**Comment by famod** [comment]
#578 tries to fix MNG-6843 differently, avoiding any ThreadLocals or refactorings,

**Comment by michael-o** [comment]
Can we agree that, unfortunately, @famod's did not work out as expected an can revert both commits in separate ticket to make it clear in the release notes first? The we can go over to @famod's new proposal.

@famod In any case, thank you very much for your dedication and time!

**Comment by mickaelistria** [comment]
Was a similar test included with some other commit? If so, should this be closed now?

**Comment by gnodet** [comment]
This test has been integrated into #627 and #628.

**Pull request closed without merging**
