### PR TITLE
[MNG-5600] Dependency management import should support exclusions.

### PR DESCRIPTION
**Pull request by ChristianSchulte**

### CODE REVIEW

**Comment by ChristianSchulte** [comment]
[Corresponding IT pull request.](https://github.com/apache/maven-integration-testing/pull/30)

**Comment by RayzorFlash** [comment]
@ChristianSchulte - Any update on when this can/will be merged?? I'm unfamiliar with the maven contribution process

**Comment by alex1989hu** [comment]
@olamy  @rfscholte -  Could we get this patch being merged? If any help is needed don't hesitate to ping me.

Here is @ChristianSchulte's updated patch without conflict:
```patch
diff --git a/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java b/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
index f981944f940fcbc912959752d3cff4bc1586519f..616859c60c71aa22f1af9e386c86f7167f19d794 100644
--- a/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
+++ b/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java
@@ -27,6 +27,7 @@
 import org.apache.maven.model.Build;
 import org.apache.maven.model.Dependency;
 import org.apache.maven.model.DependencyManagement;
+import org.apache.maven.model.Exclusion;
 import org.apache.maven.model.InputLocation;
 import org.apache.maven.model.InputSource;
 import org.apache.maven.model.Model;
@@ -1316,6 +1317,41 @@ private void importDependencyManagement( Model model, ModelBuildingRequest reque
                     importMgmt = new DependencyManagement();
                 }
 
+                // [MNG-5600] Dependency management import should support exclusions.
+                if ( !dependency.getExclusions().isEmpty() )
+                {
+                    for ( final Exclusion exclusion : dependency.getExclusions() )
+                    {
+                        if ( exclusion.getGroupId() != null && exclusion.getArtifactId() != null )
+                        {
+                            for ( final Iterator<Dependency> dependencies = importMgmt.getDependencies().iterator();
+                                dependencies.hasNext(); )
+                            {
+                                final Dependency candidate = dependencies.next();
+
+                                if ( ( exclusion.getGroupId().equals( "*" )
+                                    || exclusion.getGroupId().equals( candidate.getGroupId() ) )
+                                    && ( exclusion.getArtifactId().equals( "*" )
+                                    || exclusion.getArtifactId().equals( candidate.getArtifactId() ) ) )
+                                {
+                                    // Dependency excluded from import.
+                                    dependencies.remove();
+                                }
+                            }
+                        }
+                    }
+
+                    for ( final Dependency includedDependency : importMgmt.getDependencies() )
+                    {
+                        includedDependency.getExclusions().addAll( dependency.getExclusions() );
+                    }
+                }
+                else
+                {
+                    // Only dependency managements without exclusion processing applied can be cached.
+                    putCache( request.getModelCache(), groupId, artifactId, version, ModelCacheTag.IMPORT, importMgmt );
+                }
+
                 putCache( request.getModelCache(), groupId, artifactId, version, ModelCacheTag.IMPORT, importMgmt );
             }
```

**Comment by olamy** [comment]
@alex1989hu  please provide another pr

**Pull request closed without merging**
