### PR TITLE
MNG-5577: convert remaining non core/compat modules

### PR DESCRIPTION
**Pull request by josephw**
Further conversion to JSR 330 annotations, following [Plexus Migration](https://wiki.eclipse.org/Sisu/PlexusMigration) -- everything outside core and compat, with some test changes to adjust.

This incorporates #232 by @slachiewicz, but omits the logging change in 39ca59d8bcce6b1 to focus on the annotations.

In tests, use of `PlexusTestCase` for trivial wiring is reduced, to directly construct the classes under test. Tests that do more significant wiring are modified to use `PlexusConstants.SCANNING_ON` so JSR 330-annotated classes no longer included in component indexes are picked up.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by michael-o** [comment]
I would really prefer to have seperate tickets and PRs for each module. I don't want to review and merge so many changes at once.

**Comment by michael-o** [comment]
Thank you for your hard work!

**Comment by josephw** [comment]
That's reasonable; I've created subtasks of [MNG-5577](https://issues.apache.org/jira/browse/MNG-5577):
* `maven-model-builder` -- [MNG-6685](https://issues.apache.org/jira/browse/MNG-6685)
* `maven-embedder` -- [MNG-6686](https://issues.apache.org/jira/browse/MNG-6686)
* `maven-compat` --[MNG-6687](https://issues.apache.org/jira/browse/MNG-6687)

and I'll split this into separate PRs against the first two.

**Comment by jira-importer** [comment]
Resolve #6750

**Pull request closed without merging**
