### PR TITLE
[MNG-6344] Upgrade Guice to 4.2 wit AOP (cglib)

### PR DESCRIPTION
**Pull request by slachiewicz**
I provide it, if someone could run tests on it and check on larger projects.

### CODE REVIEW

**Comment by michael-o** [comment]
What is the benefit of having it with AOP?

**Comment by slachiewicz** [comment]
Based on [Guice optional AOP](https://github.com/google/guice/wiki/OptionalAOP#optional-aop)

> In Guice 2.0 and later, AOP is optional. If your platform doesn't support bytecode generation, you can download a version of Guice that doesn't include AOP support. This is most useful for mobile platforms like Android. This version also lacks fast reflection and line numbers in error messages. For this reason, we recommend Guice+AOP even in applications that don't use method interceptors.

Only risk I can see is inclusion of additional dependency to CGLIB and ASM

**Comment by mcculls** [comment]
Maven doesn't export any of the `com.google.inject` or `org.aopalliance` packages to plugins, so they're currently unable to take advantage of any AOP features (although maven-core could if it wished). The only reason to switch to the AOP build would be for the slightly faster reflection via CGLIB. Both CGLIB and ASM are embedded under an internal package, so there shouldn't be any clashes with other copies of these libraries on the classpath.

However because the AOP build leans on CGLIB and ASM for reflection then it's affected more by recent JDK changes. For example while the latest release works fine on JDK 9, it needs a bump to ASM 6.2 to work properly on JDK 10+

Given this, and because no plugins can use AOP until we export the packages from maven-core's `extension.xml`, we've kept with the no-AOP version. That may change if we want to start allowing AOP in plugins - but that's best done under a separate feature request, rather than at the same time as a version bump.

HTH

**Pull request closed without merging**
