### PR TITLE
[MNG-8081] Profile property activation interpolation

### PR DESCRIPTION
**Pull request by cstamas**
Property profile activation should interpolate.

---

https://issues.apache.org/jira/browse/MNG-8081

### CODE REVIEW

**Review by slawekjaranowski — COMMENTED** [review]
looks ok

**Comment by mbenson** [comment]
I notice that this implementation _only_ interpolates properties in property activations, whereas my submitted implementations for both v3.9.x and v4 attempt to satisfy the "least surprise" principle by applying interpolations to _all_ property activations. IMHO that's the best way forward but I am satisfied if this PR becomes the 3.9.x implementation.

**Comment by cstamas** [comment]
@mbenson can you clarify what you mean by "only [...] property activations" vs "all property activations" as I think don't understand it fully...

**Comment by mbenson** [comment]
Sorry @cstamas, was working late and apparently not 100%. Edited my comment with changed text in bold.

**Comment by gnodet** [comment]
Similar to #1447

**Pull request closed without merging**
