### PR TITLE
[MNG-5961] Fix the SLF4J logger factory implementation used for LOG4J2

### PR DESCRIPTION
**Pull request by aheritier**
This is the fix I did in https://git-wip-us.apache.org/repos/asf?p=maven.git;a=blobdiff;f=maven-embedder/src/main/resources/META-INF/maven/slf4j-configuration.properties;h=cd01f9e6bb29cf31371e0e6df04d095430d3ea9b;hp=87418363b1812e85d6a41a63df4486d07227e1d5;hb=202f757af3aba6e1b96631de025e0ba692098009;hpb=5a3332ca347628605bec7d3e9f9309081aaba46c

### CODE REVIEW

**Comment by aheritier** [comment]
cc @michael-o @stephenc 
https://issues.apache.org/jira/browse/MNG-5961

**Comment by aheritier** [comment]
I think @stephenc will tell me to push a branch on ASF side :-)

**Comment by michael-o** [comment]
I am fine with this PR. You have to raise the issue on the dev mailing list to have at least someone who seconds it. If someone does, after your branch passes all tests, go ahead and merge into master.

**Comment by aheritier** [comment]
@michael-o we don't have a CI validation here, thus I have to open a real branch on ASF side. Right ?

**Comment by michael-o** [comment]
Do this:

    git checkout master
    git checkout -b MNG-5961
    git cherry-pick <your-sha1>
    git push

Wait for the Jenkins build to finish, get approval

    git checkout master
    git merge MNG-5961

Delete branch locally and remote.

**Comment by aheritier** [comment]
Cool @michael-o it is exactly what I did
the build is in progress
https://builds.apache.org/view/Maven/job/maven-3.x-jenkinsfile/job/MNG-5961/

**Comment by stephenc** [comment]
>  we don't have a CI validation here

Yep waiting to get SCM API 2.0.x back into the uc and then pester infra to upgrade

**Comment by jira-importer** [comment]
Resolve #7488

**Pull request closed without merging**
