### PR TITLE
MNG-3092: Filter Version Range Result

### PR DESCRIPTION
**Pull request by barthel**
The discussion on issue [MNG-3092](https://issues.apache.org/jira/browse/MNG-3092) shows the seriously needs of different kinds of version range resolving in Maven.

I know about the risk on changing the resolving mechanism in Maven.
I always had the backward compatibility in mind, if I have something changed.
I added some basic tests for the default version range resolver before I've started with the refactoring.

This pull request contains the basic tests and a less invasive solution based on a filter works with resolved version range results.

The actual version range resolving algorithm **wasn't changed** and the internal used default filter implementation don't filter anything.

The goal:
Provide a hook for Maven extensions/plugins to change the list of resolved version range results as required.

These changes are only placed in _maven-aether-provider_.

### CODE REVIEW

**Comment by barthel** [comment]
Only b6d72699c8b0089351f797e217d635424c1ae5a2 contains the enhancements.

**Comment by barthel** [comment]
Is there anything else I can do to help to merge this change or make/explain it better?

**Comment by jvanzyl** [comment]
Squash it please.

**Comment by barthel** [comment]
Only b6d7269 is the relevant commit. All other commits are merged from master into my feature branch.

**Comment by michael-o** [comment]
Create a branch named by the issue on top of master and put a single commit onto it.

**Comment by barthel** [comment]
I've open a new PR (#70) based on master and re-created branch MNG-3092. This branch contains the cherry picked b6d7269.

**Pull request closed without merging**
