### PR TITLE
[MNG-6268] When a reactor build fails Maven should include -f (if used) in command line suggestion

### PR DESCRIPTION
**Pull request by michael-o**
I don't know whether this should be included, but it is trivial to provide. I will let the community decide. If accepted someone should write an IT for that.

### CODE REVIEW

**Comment by rfscholte** [comment]
Writing a unittest is much easier in this case and sufficient enough.

**Review by eolivelli — APPROVED** [review]
LGTM 

I agree that a unit test is enough here

**Comment by michael-o** [comment]
Just scratching my head how the full boostrap with a unit test would work here since I'd need to analyze stdout/err.

**Comment by rfscholte** [comment]
IIRC @mthmulders had a similar usecase recently

**Comment by mthmulders** [comment]
> IIRC @mthmulders had a similar usecase recently

Not sure if I understand correctly what you refer to. I recently had a contribution to Plexus Archiver where I wrote a [`CapturingLog`](https://github.com/codehaus-plexus/plexus-archiver/blob/master/src/test/java/org/codehaus/plexus/archiver/CapturingLog.java). But given that this is SLF4J, it might be easier to go with something like [SLF4J Test](https://projects.lidalia.org.uk/slf4j-test/).

**Comment by michael-o** [comment]
The SFL4J test looks promising, but wouldn't it be easier to do just an IT instead of going through a new component?

**Comment by rfscholte** [comment]
Another option is to increase the visibility of `logBuildResumeHint( String resumeBuildHint )` a bit, in the unittest making a new MavenCli with an override of this method. To me an IT is overkill for this check, as it is simple input/output validation, only the difficulty here is that it is writing directly the the logging framework. Better adjust the class to make it testable

**Comment by michael-o** [comment]
Another option is to have no test at all since this change is straight forward. Pipe input to output unmodified as you can see.

**Comment by rfscholte** [comment]
I'm fine with no test in this case.

**Comment by michael-o** [comment]
The issue has been closed as wontfix. So closing this, but leaving the branch for a while.

**Pull request closed without merging**
