### PR TITLE
Change out JAVA_HOME. Add JRE used. JRE used print /jre and JAVA_HOME…

### PR DESCRIPTION
**Pull request by marcelosv**
I read the discursion of issue MNG-5756 and I change code out for JAVA_HOME and JRE.
Now, print two information to JAVA.

### CODE REVIEW

**Comment by michael-o** [comment]
The diff is huge, you have a line ending issue.

**Comment by eis** [comment]
Unfortunately it's not only line ending issue - you've changed the formatting on those files as well, so ignoring line endings (`?w=1`) the diff is still huge. It seems you've reformatted the entire files.

**Comment by marcelosv** [comment]
OK, i go change and correct

**Comment by marcelosv** [comment]
ok. correct the code. :D

**Comment by jira-importer** [comment]
Resolve #7672

**Pull request closed without merging**
