### PR TITLE
String handling issues identified by PMD

### PR DESCRIPTION
**Pull request by alexhenrie**
The code linting tool [PMD](http://pmd.sourceforge.net/pmd-5.2.0/) identified numerous places where Maven's string handling is inefficient. I've prepared a set of patches that should help speed things up.

The command I used was `pmd -d . -R java-strings`

### CODE REVIEW

**Comment by jvanzyl** [comment]
I have some code that touches a lot of this so I'd like to apply that first. Also what's the performance difference you observe?

**Comment by Tibor17** [comment]
Nowadays execution time of array allocation is logarithmic function(array.length).
One way or another since of Java 6 the the objects are allocated in the stack instead of in main memory. This did speed up the entire VM in Java 6 (u45). So regarding array size with length 512 in StringBuilder and 3GHz CPU, the allocation take much less than 150 nano seconds because the allocation is logarithmic maybe 50 nanos or so.

**Comment by alexhenrie** [comment]
@jvanzyl I can wait until you've finished your other changes, that's no problem. I haven't been able to measure the performance improvement because Maven's execution time is so variable. However, if you search for more information about these optimizations, you will find people explaining that they are indeed worthwhile.

**Comment by ChristianSchulte** [comment]
This has been committed. See MNG-5934. Please close this pull request manually.

**Comment by alexhenrie** [comment]
OK, thanks!

**Pull request closed without merging**
