### PR TITLE
[MNG-7329] Upgrade maven-enforcer-plugin

### PR DESCRIPTION
**Pull request by gnodet**
This is required in order to be able to build master with itself.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by mthmulders** [comment]
Is this a work-around for the fact that https://github.com/apache/maven-parent/pull/32 has not yet been released? Based on what @cstamas said in [MNG-7319](https://issues.apache.org/jira/browse/MNG-7319?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=17437157#comment-17437157), I guess that latter is the long-term fix.

**Comment by mthmulders** [comment]
> Imho, having master not building correctly should be fixed asap

Most certainly agree. We shouldn't even let it come this far (but that's a different topic).

> What about quickly include this PR and eventually revert when maven-parent is released?

I don't know how much work it would be to release maven-parent. I feel that would be "the right way" to solve it. But updating it for Maven only (as this PR does) is most likely the _fastest_ way forward. The only thing I'm afraid of is that we will forget to remove this quick patch when maven-parent is released...

**Comment by slawekjaranowski** [comment]
We have also m-e-p version in ASF parent pom
 
and was updated https://github.com/apache/maven-apache-parent/commit/9e195c86baada07b2a1a493ca7eed622d0482b36

**Comment by gnodet** [comment]
> But updating it for Maven only (as this PR does) is most likely the _fastest_ way forward. The only thing I'm afraid of is that we will forget to remove this quick patch when maven-parent is released...

I've raised https://issues.apache.org/jira/browse/MNG-7330 to not forget it.

**Review by mthmulders — APPROVED** [review]
Looks good!

**Review by slachiewicz — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #8115

**Pull request merged**
