### PR TITLE
[MNG-7909] Upgrade to Resolver 2.0.0-alpha-1

### PR DESCRIPTION
**Pull request by cstamas**
Upgrade to Resolver 2.0.0.

Changes:
* many UT code used `new DefaultRepositorySystem()` ctor that is gone (was present due SL only), replaced with mocks
* dropped MavenResolverModule Guice module (as AetherGuice module is gone as well)
* updated Resolver version to 2.0.0-alpha-1
* added jdk transport (that prevails apache on Java 11)
* rename of "native" into "apache", deprecate "native" name
* introduce "jdk" transport

---

https://issues.apache.org/jira/browse/MNG-7909

### CODE REVIEW

**Comment by cstamas** [comment]
One IT fails, recorded as https://issues.apache.org/jira/browse/MRESOLVER-412

**Comment by cstamas** [comment]
Seems some more ITs failed, looking...
The read poms one is recorded (and is not resolver related) https://issues.apache.org/jira/browse/MRESOLVER-412
Rest needs to be looked at.

**Comment by cstamas** [comment]
On Java 11 IT failures are:
```
Error:  Failures: 
Error:    MavenITmng4368TimestampAwareArtifactInstallerTest.testitJarPackaging:153->AbstractMavenIntegrationTestCase.assertFalse:363->AbstractMavenIntegrationTestCase.assertFalse:367 expected: <false> but was: <true>
Error:    MavenITmng5669ReadPomsOnce.testWithBuildConsumer:114->AbstractMavenIntegrationTestCase.assertTrue:359 Duplicate items: org.apache.maven:maven:3.2.5
org.apache.commons:commons-parent:52
org.codehaus.plexus:plexus:10 ==> expected: <true> but was: <false>
Error:    MavenITmng5669ReadPomsOnce.testWithoutBuildConsumer:78->AbstractMavenIntegrationTestCase.assertTrue:359 Duplicate items: org.apache.commons:commons-parent:52
org.apache:apache:15
org.apache.maven:maven-parent:25 ==> expected: <true> but was: <false>
Error:  Errors: 
Error:    MavenITmng5175WagonHttpTest.testmng5175_ReadTimeOutFromSettings:124 » Verification Text not found in log: Read timed out
   MavenITmng7470ResolverTransportTest.testResolverTransportDefault:106->performTest:97 » Verification Text not found in log: [DEBUG] Using transporter HttpTransporter
[INFO] 
Error:  Tests run: 904, Failures: 3, Errors: 2, Skipped: 34
```

Info:
* we know about MavenITmng5669ReadPomsOnce, there is issue in model builder when using MT collector (and resolver 2.0.0 makes BF default that is MT)
* MavenITmng5175WagonHttpTest is strange, is called "Wagon" but asserts that "apache" transport is used (is not, on Java11+ is jdk used)
* the only questionable is MavenITmng4368TimestampAwareArtifactInstallerTest

**Comment by gnodet** [comment]
> * we know about MavenITmng5669ReadPomsOnce, there is issue in model builder when using MT collector (and resolver 2.0.0 makes BF default that is MT)

Wasn't this one solved by #893 ?

**Comment by cstamas** [comment]
> Wasn't this one solved by #893 ?

WILL be solved when merged, yes :smile:

**Comment by jira-importer** [comment]
Resolve #9005

**Pull request merged**
