### PR TITLE
Backport 3.8: [MNG-7686]

### PR DESCRIPTION
**Pull request by tbw777**

### CODE REVIEW

**Comment by tbw777** [comment]
Error:  src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java:[57,69] (whitespace) ParenPad: '(' is not followed by whitespace.
Error:  src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java:[57,89] (whitespace) ParenPad: ')' is not preceded with whitespace.
Error:  src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java:[192,45] (whitespace) ParenPad: '(' is not followed by whitespace.
Error:  src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java:[192,55] (whitespace) ParenPad: ')' is not preceded with whitespace.
Error:  src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java:[192,68] (whitespace) ParenPad: '(' is not followed by whitespace.
Error:  src/main/java/org/apache/maven/plugin/descriptor/PluginDescriptor.java:[192,70] (whitespace) ParenPad: ')' is not preceded with whitespace.

**Comment by gnodet** [comment]
This is not a bug, so I would not back port it on 3.8.x.

**Comment by michael-o** [comment]
> This is not a bug, so I would not back port it on 3.8.x.

Not a bug, correct, but easy to address. I don't mind doing it.

**Comment by michael-o** [comment]
Merged.

**Comment by jira-importer** [comment]
Resolve #8767

**Pull request closed without merging**
