### PR TITLE
[MNG-7848] Add Jenkinsfile.s390x for Jenkins CI on s390x

### PR DESCRIPTION
**Pull request by vivkong**
As discussed on https://github.com/apache/maven/pull/1239, we would like to add `Jenkinsfile.s390x` back and re-enable the s390x pipeline on Jenkins CI (https://ci-maven.apache.org/job/Maven/job/Maven%20Core%20s390x/).  The s390x build will run on `master` branch only with no PR checks so we won't encounter issues with custom IT branch.

@olamy @elharo @gnodet I appreciate your help in reviewing this and getting Jenkins CI setup to use the Jenkinsfile once it's merged.  Thank you!

---
Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`,
       where you replace `MNG-XXX` and `SUMMARY` with the appropriate JIRA issue.
 - [x] Also format the first line of the commit message like `[MNG-XXX] SUMMARY`.
       Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by vivkong** [comment]
Is it possible to re-run the checks as the Jenkinsfile shouldn't affect integration tests?  Thanks.

**Comment by elharo** [comment]
I clicked the button to rerun the failed jobs

**Comment by vivkong** [comment]
Thanks @elharo!

**Comment by vivkong** [comment]
Thanks @olamy for merging this.  Will s390x builds be running on https://ci-maven.apache.org/job/Maven/job/Maven%20Core%20s390x/ or a new one needs to be setup?   Thanks for your help.

**Comment by vivkong** [comment]
Hi @olamy, any updates on add s390x builds on Jenkins?  Thanks.

**Comment by olamy** [comment]
@vivkong my bad sorry for delay 
all done here https://ci-maven.apache.org/job/Maven/job/maven-core.s390x/
you might need some setup on your nodes as master need jdk 11 now.
cheers

**Comment by vivkong** [comment]
HI @olamy, Thanks for your help!  I will create a PR to upgrade the JDK and fix the s390x build.

**Comment by jira-importer** [comment]
Resolve #8740

**Pull request merged**
