### PR TITLE
MNG-5577 convert most of maven core to jsr330 annotations

### PR DESCRIPTION
**Pull request by josephw**
The aim of this PR is to get `git grep 'org.codehaus.plexus.component.annotations' maven-core/src/main/java/` down as low as possible; it covers everything except `DefaultLifecyclePluginAnalyzer`.

(For `DefaultLifecyclePluginAnalyzer`, switching `@Requirement` to `@Inject` for `lifecycleMappings` means it's no longer wired up with a `RealmFilteredBeans`, and [`MNG-4385`](https://issues.apache.org/jira/browse/MNG-4385) regresses.)

Tests are also simplified, to avoid injection in tests of concrete classes, and remove some no-longer-used mocks.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ x Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by slachiewicz** [comment]
I found one issue with Intellij check this stacktrace:
https://gist.github.com/slachiewicz/56bab10ce43c8da6a548002fb9a31bbc

**Comment by olamy** [comment]
core IT?

**Comment by slachiewicz** [comment]
Yes, core it is green

**Comment by michael-o** [comment]
Folks, do have have a way to run this PR against all Plugin ITs? I'd like to avoid the same situation as with the multiple POM loads against Maven Shade Plugin.

**Comment by rfscholte** [comment]
Why do we keep changing maven-compat? By showing it is maintained it will be harder to convince projects to drop it.

@michael-o no, unless somebody has it all on his system, he can easily make an aggregator for it. But I'm not so worried about this. The loop was caused by new implementations, this is a clear replacement. Plugins that might be hit are more likely the tiles-maven-plugin and polyglot-maven-plugin.

**Comment by michael-o** [comment]
Running ITs here too...

**Comment by josephw** [comment]
> Why do we keep changing maven-compat?

The changes to maven-compat are test-only; a couple are necessary to wire up the classes from `maven-core` after this change, another couple are simplifications.

I'd be delighted if the module wasn't there at all, and would also support formally WONTFIX'ing [MNG-6687](https://issues.apache.org/jira/browse/MNG-6687).

**Comment by slachiewicz** [comment]
It's worth to do change also in maven-compat as we have few implementation beans that are required for maven to run.

Quick check - rename maven-compat.jar in Maven installation and try to run something. ;-)


I have few more commits almost ready to get rid off plexus annotations that we can review later.

**Comment by rfscholte** [comment]
I issued https://issues.apache.org/jira/browse/MNG-5995 so I am aware of the awkward compat situation. However this shouldn't be solved in compat, but in core. mven-compat should be conisdered dead code, it was there to keep Maven2 plugins compatible with Maven 3. I prefer to spend energy on the other modules.

**Comment by jira-importer** [comment]
Resolve #6750

**Pull request closed without merging**
