### PR TITLE
[3.9.x][MNG-7587] Upgrade to sisu 0.9.0.M2

### PR DESCRIPTION
**Pull request by gnodet**
JIRA issue: https://issues.apache.org/jira/browse/MNG-7587

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by cstamas** [comment]
What about:
* using sisu "no_asm" classifier
* using guice "classes" classifier
* declaring asm (whatever version) as maven dep?

**Comment by kwin** [comment]
> What about:

> using sisu "no_asm" classifier
> using guice "classes" classifier
> declaring asm (whatever version, for start 9.5) as maven dep?

I would defer to add this additional complexity until there is a new version of ASM released which is not integrated in Sisu.

**Comment by gnodet** [comment]
> > What about:
> 
> > using sisu "no_asm" classifier
> > using guice "classes" classifier
> > declaring asm (whatever version, for start 9.5) as maven dep?
> 
> I would defer to add this additional complexity until there is a new version of ASM released which is not (yet) integrated in Sisu.

We can't defer.  We use juice 5.1.0 which embeds asm 9.2, so we need to use version which does not embed asm.

**Review by cstamas — APPROVED** [review]
For 3.9.x "simple upgrade" is the way to go, and let's to the "asm trick" on master

**Comment by jira-importer** [comment]
Resolve #8936

**Pull request merged**
