### PR TITLE
MNG-5909 : Add combined expression evaluator to file activation property

### PR DESCRIPTION
**Pull request by lbndev**
Suggested solution for MNG-5909 : the file activation element will understand basic boolean expressions such as and(file1,file2) or(file3,!file4) etc... Please see added unit test for expression examples.
If you think this could benefit to other activators (property, os, ...) please say so and I will happily modify them too.
I will also post a message on maven dev mailing list.

### CODE REVIEW

**Comment by kwin** [comment]
@lbndev Can you redo the PR only containing the actual change (IIUC this is only commit https://github.com/apache/maven/pull/92/commits/2efe3d2d3b92685d83c2598a7f85c39ebdd59ebc). Otherwise it is impossible to review.

**Comment by lbndev** [comment]
Hello @kwin,

Wow, resurrecting an old request !
I rebased my change on branch "pre-reset-master" (see branch MNG-5909-oldmaster), then I cherry-picked in on top of the new master, fixing conflicts.

It used to work on the initial version of this PR (almost 2 years ago), but I should take time to build & test this new version just to make sure it plays nicely with all the other changes in maven over the last 2 years. Maybe I'll find time during the weekend.

Thanks for your interrest in this PR

Loïc

**Comment by bdelion** [comment]
UP

**Comment by michael-o** [comment]
This does not incur a model change, does it?

**Comment by marcelstoer** [comment]
Any chance this will ever be accepted?

**Comment by michael-o** [comment]
I will try to look at this in the next two weeks.

**Comment by michael-o** [comment]
@marcelstoer Please ping me by mid of April.

**Comment by marcelstoer** [comment]
> Please ping me by mid of April.

Ping

**Comment by michael-o** [comment]
> 
> 
> > Please ping me by mid of April.
> 
> Ping

Seriously? Do you live a by different calendar? You consider 2021-04-05 mid of April?

**Comment by marcelstoer** [comment]
Not sure what the intention of this comment was (i.e. _why_ I should ping you) but "by mid April" means no later than mid April. You meant "around" mid April instead?

**Comment by jira-importer** [comment]
Resolve #7496

**Pull request closed without merging**
