### PR TITLE
[MNG-8376] Exit with a nicer error message when running on JDK < 17

### PR DESCRIPTION
**Pull request by gnodet**
Needs to be tested on windows, or maybe just add an IT ?

### CODE REVIEW

**Comment by michael-o** [comment]
> Needs to be tested on windows, or maybe just add an IT ?

Why not, sounds reasonable...

**Review by elharo — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
We assume thet user have awk ....
What do you think to create a simple class like:

```java
public class CheckJavaVersion {
    public static void main(String[] args) {
        if (Double.parseDouble(System.getProperty("java.vm.specification.version")) < 17.0) {
            System.exit(2);
        }
    }
}

```

compile with target 8, put in bin directory

it will be easy to execute and check statu code of execution

**Comment by gnodet** [comment]
> We assume thet user have awk .... What do you think to create a simple class like:
> 
> ```java
> public class CheckJavaVersion {
>     public static void main(String[] args) {
>         if (Double.parseDouble(System.getProperty("java.vm.specification.version")) < 17.0) {
>             System.exit(2);
>         }
>     }
> }
> ```
> 
> compile with target 8, put in bin directory
> 
> it will be easy to execute and check statu code of execution

I just changed the script to simply rely on java to verify that the argument can be used.

**Review by slawekjaranowski — APPROVED** [review]

**Review by cstamas — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #9477

**Pull request merged**
