### PR TITLE
[MNG-7055] Fix G level metadata handling

### PR DESCRIPTION
**Pull request by cstamas**
Maven Artifact Transfer silently prevents group level metadata to reach Resolver and causes metadata loss on install/deploy. Fix is to "bridge" this from maven-resolver-provider (and core) by reusing the actual metadata that m-plugin-p:addPluginArtifactMetadata mojo adds, but m-a-t filters out.

https://issues.apache.org/jira/browse/MNG-7055

### CODE REVIEW

**Comment by mthmulders** [comment]
How does this relate to [MNG-7055](https://issues.apache.org/jira/browse/MNG-7055)?

**Comment by cstamas** [comment]
> How does this relate to [MNG-7055](https://issues.apache.org/jira/browse/MNG-7055)?

Fixes it (not yet, once done)

**Comment by cstamas** [comment]
The ITs reported in MNG-7055 to fail with 3.x of m-install-p and m-deploy-p are passing OK (!), but now another IT fails:
```
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    MavenIT0138PluginLifecycleTest>AbstractMavenIntegrationTestCase.runTest:265->testit0138:60 Expected file was not found: /home/runner/work/maven/maven/maven-integration-testing/core-it-suite/target/test-classes/it0138/target/plugin-add-plugin-artifact-metadata.txt
[INFO] 
Error:  Tests run: 882, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by cstamas** [comment]
Patched ITs with https://github.com/apache/maven-integration-testing/pull/114 all pass OK:
```
[INFO] Tests run: 879, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 192.019 s - in org.apache.maven.it.IntegrationTestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 879, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by rfscholte** [comment]
A similar change needs to be done for both plugins, in case it is used with Maven 3

**Comment by mthmulders** [comment]
> > How does this relate to [MNG-7055](https://issues.apache.org/jira/browse/MNG-7055)?
> 
> Fixes it (not yet, once done)

I'm a bit sad that the work that @MartinKanters and me had done so far (announced [in the JIRA ticket](https://issues.apache.org/jira/browse/MNG-7055?focusedCommentId=17379009&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17379009) and more recently [here on GitHub](https://github.com/apache/maven/pull/552#issuecomment-927659381)) is apparently of no use.

**Comment by rfscholte** [comment]
@mthmulders this is a fix for Maven 4, but not for Maven 3

**Comment by mthmulders** [comment]
> @mthmulders this is a fix for Maven 4, but not for Maven 3

I don't think the fix that @MartinKanters and I have worked on is compatible with this approach.

**Comment by gnodet** [comment]
Does this mean that the `AddPluginArtifactMetadataMojo` from maven-plugin-plugin is completely useless ?  This is actually one of the pain point because it depends on the `GroupRepositoryMetadata` which is in maven-compat.

**Comment by cstamas** [comment]
> Does this mean that the `AddPluginArtifactMetadataMojo` from maven-plugin-plugin is completely useless ? This is actually one of the pain point because it depends on the `GroupRepositoryMetadata` which is in maven-compat.

Yes and no: Yes, as _we could_ get the only missing piece even without it (the goalPrefix that is plugin configuration). The "price" would be high, go thru plugin config/DOM stuff.... No, as due that above, it made this PR stupid simple (just reuse the data that mojo gave to us).

In general (and that's why I created this PR initially to drop this useless mojo) I'd drop it, but this seems like "simple first step", and later we can change it at will. Given m-plugin-p is "just a plugin" but is still quite often referenced in core (so somewhat not "just a plugin"), I think we could do more here, for example change the mojo to just stick some values somewhere (ie. session) and alter the provider in maven core and voila, GroupRepositoryMetadata is not needed....

**Review by gnodet — APPROVED** [review]

**Comment by gnodet** [comment]
Related to https://github.com/apache/maven-plugin-tools/pull/37 wrt `GroupRepositoryMetadata` ...

**Comment by jira-importer** [comment]
Resolve #7983

**Pull request merged**
