### PR TITLE
[MNG-7335] Parallel build fails due to missing JAR artifacts in compilePath

### PR DESCRIPTION
**Pull request by gnodet**
This is a slightly modified version of the patch outlined in https://issues.apache.org/jira/browse/MNG-7335 by @famod.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by rmannibucau — APPROVED** [review]

**Comment by gnodet** [comment]
Added an integration test at https://github.com/apache/maven-integration-testing/pull/127

**Comment by famod** [comment]
Funnily, the frist approach to MNG-6843 back then was also cloning...which @rfscholte didn't like that much: https://github.com/apache/maven/pull/310#issuecomment-571317501

**Comment by gnodet** [comment]
> Funnily, the frist approach to [MNG-6843](https://issues.apache.org/jira/browse/MNG-6843) back then was also cloning...which @rfscholte didn't like that much: [#310 (comment)](https://github.com/apache/maven/pull/310#issuecomment-571317501)

Thx for the pointer.  That lead me to have a closer look and come up with #625 which I think is a better fix.

**Comment by gnodet** [comment]
Closing this one in favour of #625

**Comment by jira-importer** [comment]
Resolve #8102

**Pull request closed without merging**
