### PR TITLE
[MNG-5995] Removed maven-compat as it not required anymore for maven …

### PR DESCRIPTION
**Pull request by rajivpjs**
Please review and let me know of any changes.

Thanks.

### CODE REVIEW

**Comment by khmarbaise** [comment]
Ok If you remove them and compiled Maven you tried to build a simple project with that compiled Maven version?

**Comment by rajivpjs** [comment]
That's right. It worked.

To build the project I ran mvn -Drat.skip=true clean package and mvn -Drat.skip=true validate. -Drat.skip=true was required so that I avoid the RATException. Have I missed anything?

**Comment by khmarbaise** [comment]
I meant that you should try to compile an example project with the created Maven Core version?  I don't meant you should build Maven core itself...

**Comment by rajivpjs** [comment]
I realised that on Friday evening, after reading again. That's why I sent an e-mail to the mailing list to work out how to build with maven. I will check whether my changes work, by using your command that you sent. I will update you and make relevant changes.

**Comment by rajivpjs** [comment]
Hi Karl

With my recent change, I compiled with an example project and I didn't have any issues. This is what I did as per the Jira task description:

`mvn -DdistributionTargetFolder=/Users/rajivpjs/Desktop/Apache/Maven/rajivpjs/maven/mavenfixtarget clean package`

From the mavenfixtarget directory I ran:

`mvn -f /path/to/pom.xml clean package`

This gave me a BUILD SUCCESS.

I then removed the from the /lib/maven-compat-3.4.0-SNAPSHOT.jar and then ran:

`mvn -f /patj/to/pom.xml validate`

The output was BUILD SUCCESS.

Have I missed anything?

**Comment by rfscholte** [comment]
Looks to me you're still testing with the installed version of Maven( e.g. 3.3.9), not your own fresh build. Instead try `/Users/rajivpjs/Desktop/Apache/Maven/rajivpjs/maven/mavenfixtarget/bin/mvn clean package -V` (the -V must confirm you're testing the right version).
I should warn you that this issue is very hard to fix without in dept knowledge of Maven. There are probably other issues which are easier to fix.

**Comment by rajivpjs** [comment]
You are right. I tried `/Users/rajivpjs/Desktop/Apache/Maven/rajivpjs/maven/mavenfixtarget/bin/mvn -f /path/to/pom.xml clean package -V`

It shows version 3.3.9.

Maybe you are right, this issue might be hard for me to fix right now. So, I will close this pull request soon. By the way if you don't mind me asking did you guess me having 3.3.9 or you saw it in some output in my logs? I can't see where you find out that information. Having look at the output I have posted, I don't see anything with 3.3.9.

**Comment by rfscholte** [comment]
Based on the recent messages on the mailing thread I assumed you are an active Maven user who wants to use the most recent version of Maven. My guess was right :)

**Pull request closed without merging**
