### PR TITLE
Move maven-compat to jsr330

### PR DESCRIPTION
**Pull request by gnodet**
The goal of this PR is to completely get rid of old plexus annotations / plugins.
This requires moving maven-compat and the only remaining plexus components to JSR330.

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by michael-o** [comment]
Interesting..didn't we say we won't touch compat anymore?

**Comment by michael-o** [comment]
> Unfortunately we can't just drop this dependency

So this is an intermediate step to ease the pain?

**Comment by gnodet** [comment]
> > Unfortunately we can't just drop this dependency
> 
> So this is an intermediate step to ease the pain?

Yes, as I said, my goal was to clean the build, it just happens I had to get rid of old plexus plugin and I needed to move maven-compat to jsr330 for that.  Quite a big work for a small goal, I agree.

That said, as the number of plugins using the `org.apache.maven.repository.RepositorySystem` is going down, we may be able to make maven-compat optional at some point.  I'll work on a separate draft PR to see how/if this can be achieved.

**Comment by gnodet** [comment]
Superseded by #1150

**Pull request closed without merging**
