### PR TITLE
[MNG-5840] Parent version is a range hack

### PR DESCRIPTION
**Pull request by stephenc**
- I don't like this, but it does let all the integration tests pass:

```
Running org.apache.maven.it.MavenITmng2199ParentVersionRangeTest
mng2199ParentVersionRange(ValidParentVersionRangeWithInclusiveUpperBound)OK (3.7 s)
mng2199ParentVersionRange(ValidParentVersionRangeWithExclusiveUpperBound)OK (1.7 s)
mng2199ParentVersionRange(InvalidParentVersionRange)........OK (0.7 s)
mng2199ParentVersionRange(ValidParentVersionRangeInvalidVersionExpression)OK (0.5 s)
mng2199ParentVersionRange(ValidParentVersionRangeInvalidVersionInheritance)OK (0.4 s)
mng2199ParentVersionRange(ValidLocalParentVersionRange).....OK (0.4 s)
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.509 sec - in org.apache.maven.it.MavenITmng2199ParentVersionRangeTest
Running org.apache.maven.it.MavenITmng5840ParentVersionRanges
mng5840ParentVersionRanges(ParentRangeRelativePathPointsToWrongVersion)OK (0.4 s)
mng5840ParentVersionRanges(ParentRangeRelativePathPointsToCorrectVersion)OK (0.4 s)
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.784 sec - in org.apache.maven.it.MavenITmng5840ParentVersionRanges
Running org.apache.maven.it.MavenITmng5840RelativePathReactorMatching
mng5840RelativePathReactorMatching(RelativePathPointsToWrongVersion)OK (0.4 s)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.374 sec - in org.apache.maven.it.MavenITmng5840RelativePathReactorMatching
```

I have created this as a pull request because I do not like the dependency change it requires.

### CODE REVIEW

**Comment by stephenc** [comment]
@ifedorenko I've simplified this per your comments... still feel that adding the dependency on maven-artifact is not the correct thing... but it is a semi-reasonable fix

**Comment by ifedorenko** [comment]
What other options do we have? I guess we can create new `maven-versioning` module, move `org.apache.maven.artifact.versioning` implementation there and change maven-artifact to delegate to the new code. This is the only "clean" solution I can think of, but I do not have time to do this now and not sure new module with only a handful of classes is justifiable.

**Comment by stephenc** [comment]
After no comments against merging this and with @ifedorenko saying go for it I decided to merge... if people object they can revert it out. I am not in love with this fix but it will be fine IMHO for 3.3.6

**Comment by jvanzyl** [comment]
I'm out in the middle of nowhere, but i'll cancel the vote, test and re-roll once I'm back to civilization.

**Comment by bastiao** [comment]
https://github.com/kilokahn/maven-testers/tree/master/foo-parent 

this code does not work in 3.3.9 :(

**Comment by khmarbaise** [comment]
The problem is simply related to using the version `0.0.2-SNAPSHOT` in foo-business instead of `0.0.3-SNASPHOT` as parent version which will never work...

**Comment by bastiao** [comment]
Yes, you are right.

But In childs I would like to use:

    <parent>
        <artifactId>foo-parent</artifactId>
                <version>${global.version}</version>
        <groupId>com.kilo</groupId>
    </parent>

${global.version} is defined in parent pom.xml.

It compiles in 3.3.3 but not in 3.3.9 :-(

**Comment by khmarbaise** [comment]
So we are talking about something completely different. I have cloned the given repository `https://github.com/kilokahn/maven-testers/` and i can't find a definition for `global.version` ? If you like to use something like above you have to use predefined placeholders ([revision, changelist, sha1](http://maven.apache.org/docs/3.2.1/release-notes.html#Continuous_delivery_friendly_versions_MNG-5576)) so you can call maven like this:

    mvn -Drevision=1.0-SNAPSHOT clean package 

which is already available since Maven 3.2.1...

**Pull request merged**
