### PR TITLE
[MNG-6981] Include child projects of projects selected with --pl

### PR DESCRIPTION
**Pull request by MartinKanters**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG-6981) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by mthmulders — COMMENTED** [review]
Is it possible to add a scenario for this in the DefaultGraphBuilderTest?

**Comment by MartinKanters** [comment]
Apparently our GitHub Actions workflow still needs some adjustments. It has failed on this PR, because it targeted apache/maven-integration-testing instead of infosupport/maven-integration-testing. Here is the working one: https://github.com/infosupport/maven/actions/runs/246611913.

**Comment by MartinKanters** [comment]
> Is it possible to add a scenario for this in the DefaultGraphBuilderTest?

Yes, it is possible, but would require a multi-layered submodule to be tested efficiently. We have introduced that in https://github.com/apache/maven/pull/373. 
My preference is to include this scenario in that test once that PR is merged (or include the test scenario in that PR if this one is merged sooner).
For now it is covered by integration-tests, which should be good enough I think. What do you think?

**Review by mthmulders — APPROVED** [review]

**Comment by mthmulders** [comment]
At second thought, I'm a bit worried about the fact that this change does break existing behaviour. Sure, there's another way to achieve that, but shouldn't that be a sign this change belongs to a new major version of Maven?

**Comment by michael-o** [comment]
@mthmulders We have `-N` for that. What would be the purpose to build the a child POM project w/o its subchildren? We can document that and deal with when we receive complaints.

**Review by michael-o — APPROVED** [review]

**Comment by mthmulders** [comment]
> @mthmulders We have `-N` for that. What would be the purpose to build the a child POM project w/o its subchildren? We can document that and deal with when we receive complaints.

I'm sure about the value of this change, no doubt about that. Don't know what `-N` means in this context, though. Do you have a reference for me?

**Comment by michael-o** [comment]
Non-recursive. `-N` and `-pl` would restore previous behavior.

**Comment by MartinKanters** [comment]
> Non-recursive. `-N` and `-pl` would restore previous behavior.

That was my initial guess as well, but it seems -N will only provide the subjected POM project to the reactor, so -pl on a subproject won't work. The workaround is `-N -f ..`, which is a bit less intuitive, but still a working alternative. [More details here.](https://issues.apache.org/jira/browse/MNG-6981?focusedCommentId=17193098&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17193098)

**Comment by MartinKanters** [comment]
Will merge in master after https://github.com/apache/maven/pull/377 has been merged to get the ITs on GitHub Actions green.

**Comment by mthmulders** [comment]
[Running through Jenkins](https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven/job/MNG-6981-pl-should-include-children/)

**Pull request closed without merging**
