### PR TITLE
fix version comparison

### PR DESCRIPTION
**Pull request by sultan**
Following MNG-7559

Expected: treat equally
* 6.1m5
* 6.1m.5
* 6.1m-5

Actual: not equal
1. 6.1m5 -> 6.1-milestone-5; tokens: [6, 1, [milestone, [5]]]
   6.1m5 > 6.1m.5
2. 6.1m.5 -> 6.1-m.5; tokens: [6, 1, [m, 5]]
   6.1m.5 > 6.1m-5
3. 6.1m-5 -> 6.1-m-5; tokens: [6, 1, [m, [5]]]

---

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by michael-o** [comment]
Is this a followup to https://github.com/apache/maven/commit/97e8bf67113a9697ff8940b0b65b3e4d7bd3c28a?

**Comment by sultan** [comment]
> Is this a followup to [97e8bf6](https://github.com/apache/maven/commit/97e8bf67113a9697ff8940b0b65b3e4d7bd3c28a)?

different test cases, i consider opening a JIRA before making this ready for peer review

**Comment by michael-o** [comment]
> > Is this a followup to [97e8bf6](https://github.com/apache/maven/commit/97e8bf67113a9697ff8940b0b65b3e4d7bd3c28a)?
> 
> different test cases, i consider opening a JIRA before making this ready for peer review

I am inclined to revert the badly attributed commit and give you time to make it proper for all lines of Maven. WDYT?

**Comment by sultan** [comment]
> > > Is this a followup to [97e8bf6](https://github.com/apache/maven/commit/97e8bf67113a9697ff8940b0b65b3e4d7bd3c28a)?
> > 
> > 
> > different test cases, i consider opening a JIRA before making this ready for peer review
> 
> I am inclined to revert the badly attributed commit and give you time to make it proper for all lines of Maven. WDYT?

you can revert the initial PR, so i can make the same pull request again with the same fix.

if these new identified edge cases really are issues that need to be adressed we need an issue listing them.

**Comment by sultan** [comment]
i also think the specs lacks this PR new cases and that they need to be discussed and the expectation decided before continuing this draft

**Comment by michael-o** [comment]
This seems to be superseded.

**Pull request closed without merging**
