### PR TITLE
[MNG-7891] Support configuration for extensions

### PR DESCRIPTION
**Pull request by gnodet**
JIRA issue: https://issues.apache.org/jira/browse/MNG-7891
IT PR: https://github.com/apache/maven-integration-testing/pull/296

### CODE REVIEW

**Comment by laeubi** [comment]
@gnodet I created a little example extension / project here:
- https://github.com/apache/maven-integration-testing/pull/295

**Review by cstamas — APPROVED** [review]
With a remark: personally am really tired to use DOM/Xpp3Dom as "config", we need something smarter here (not in this PR of course, this is just a remark/rant)

**Comment by laeubi** [comment]
> With a remark: personally am really tired to use DOM/Xpp3Dom as "config"

It is `PlexusConfiguration` here ;-)

> we need something smarter

Don't know what smart you have in mind, but of course one could think about mapping this to an object annotated similar to what mojo uses (just the configuration part), but last time I tried something similar it was surprisingly hard (e.g. when it comes to interpolation/default values).

At laest this is much better than having no configuration at al or invent something that is completely extension specific (like custom properties files).

**Comment by jira-importer** [comment]
Resolve #9025

**Pull request merged**
