### PR TITLE
[MNG-6912] - File based profile activation results in absolute paths in OriginalModel

### PR DESCRIPTION
**Pull request by glimmerveen**
Determine active profiles based on 'tmpModel' rather than 'rawModel', thus ensuring the 'rawModel' is not modified in any way.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by glimmerveen** [comment]
I did try to execute the integration tests suite, but I got the following warning: 

> The requested profile "run-its" could not be activated because it does not exist.

**Comment by glimmerveen** [comment]
Coincidentally there is a parallel PR #347 that solves the same issue, but in a different way.

**Comment by basvandenbrink** [comment]
This has been an issue for quite some time and this pull request has been created 10 months ago. Is there any chance that this one gets approved?

@michael-o / @MartinKanters could you take a look at this?

**Review by elharo — COMMENTED** [review]
There is very little chance this will be approved or even reviewed unless it's up to date with head. There's no point in pinging people until master is merged in and conflicts are resolved.

**Comment by glimmerveen** [comment]
Closed as #347, which fixes the same issue, has been merged, so there is no need for this PR anymore.

**Comment by jira-importer** [comment]
Resolve #8410

**Pull request closed without merging**
