### PR TITLE
[MNG-6698] Improve the ManagedVersionMap

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by michael-o** [comment]
While I understand the diff, I don't understand "This map is not used by maven". Who uses this map? Plugins? Other components from our ecosystem?

**Comment by gnodet** [comment]
> While I understand the diff, I don't understand "This map is not used by maven". Who uses this map? Plugins? Other components from our ecosystem?

Mostly plugins I suppose, what I meant is that maven-core itself does not use it.

**Comment by michael-o** [comment]
Alright, that's what I understood.

**Comment by jira-importer** [comment]
Resolve #8548

**Pull request closed without merging**
