### PR TITLE
[MNG-5729] Use monotonic time measurements

### PR DESCRIPTION
**Pull request by gnodet**
This PR introduces a `MonotonicClock` in the Maven API.
It provides accurate duration computation, and relative date/time support, leveraging`System.nanoTime()`.
The clock is UTC-based and provided `Instant` need to be zoned if needed for correct display.

---

https://issues.apache.org/jira/browse/MNG-5729

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by cstamas** [comment]
Is this for rc2 or 4.1?

**Comment by gnodet** [comment]
> Is this for rc2 or 4.1?

I'm on the edge.  The updated PR is more lightweight and does not define a new `Temporal` implementation, but simply reuses the well known `Instant` instead, but provides a `Clock` implementation which uses the monotonic system clock.  This makes the code a lot simpler and safer.

**Comment by cstamas** [comment]
This PR looks quite non-invasive, so I'd just merge it, make it rc2

**Review by cstamas — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #6563

**Pull request merged**
