### PR TITLE
[MNG-7505] Disable reportPlugins processing if m-site-p >= 3.7.0 is used

### PR DESCRIPTION
**Pull request by gnodet**
JIRA: https://issues.apache.org/jira/browse/MNG-7505
IT PR: https://github.com/apache/maven-integration-testing/pull/218

### CODE REVIEW

**Review by slawekjaranowski — APPROVED** [review]
It can be ...
but we have next workaround for plugin which was released 2017

**Comment by gnodet** [comment]
> It can be ...
> but we have next workaround for plugin which was released 2017

This old ? 
@slawekjaranowski  I've updated the PR to get rid of that code completely...

**Comment by slawekjaranowski** [comment]
Now we only move `outputDirectory` from reporting section to site plugin configuration ...
but also this is not needed - plugin parameter has as default: `${project.reporting.outputDirectory}`

**Comment by michael-o** [comment]
Will review

**Review by michael-o — COMMENTED** [review]
So basically the "new style" configuration is dead and the `<reporting />` section remains?

**Comment by slawekjaranowski** [comment]
> So basically the "new style" configuration is dead and the `<reporting />` section remains?

it looks like - only reporting from pom should be used
https://maven.apache.org/plugins/maven-site-plugin/examples/configuring-reports.html
https://maven.apache.org/shared/maven-reporting-exec/

**Review by michael-o — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #9114

**Pull request merged**
