### PR TITLE
mvn.cmd: prevent autorun execution in final exit command

### PR DESCRIPTION
**Pull request by jhermann**
`/D` disables any registered autorun command, which would be called before the `exit`.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by michael-o** [comment]
What type of issue do you exprience to set this switch?

**Comment by jhermann** [comment]
I have this autorun script:
```
@echo off
IF /I x"%COMSPEC%"==x%CMDCMDLINE% (
    cd "%USERPROFILE%"
    clear
    set PATH=%PATH:;C:\Program Files (x86)\Common Files\Oracle\Java\javapath=%
)
```
The IF guard does not seem to work for the call you have. Using /D is the safe option for scripted cmd calls, leaving it out is generally not robust (the above IF is just a last defense).

And obviously, clearing the screen after a mvn run is somewhat sub-optimal.

**Comment by michael-o** [comment]
Please create a JIRA issue first.

**Comment by michael-o** [comment]
No JIRA issue created.

**Pull request closed without merging**
