### PR TITLE
MNG-6414 Add more Apache license headers to skip downloading license …

### PR DESCRIPTION
**Pull request by slachiewicz**
…text

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by slachiewicz** [comment]
The side effect is skip of downloading the license file from www.apache.org what produces error on Java 7

**Comment by slachiewicz** [comment]
license files in lib directory before patch:
```
Directory of maven-3.6.0-SNAPSHOT\lib
09/07/2018  01:27 AM            23,505 cdi-api.license
09/07/2018  01:27 AM            11,358 commons-cli.license
09/07/2018  01:27 AM            11,358 commons-io.license
09/07/2018  01:27 AM            11,358 commons-lang3.license
09/07/2018  01:27 AM               194 jcl-over-slf4j.license
09/07/2018  01:27 AM                 0 jsr250-api.license
09/07/2018  01:27 AM            11,358 maven-artifact.license
09/07/2018  01:27 AM            11,358 maven-builder-support.license
09/07/2018  01:27 AM            11,358 maven-compat.license
09/07/2018  01:27 AM            11,358 maven-core.license
09/07/2018  01:27 AM            11,358 maven-embedder.license
09/07/2018  01:27 AM            11,358 maven-model-builder.license
09/07/2018  01:27 AM            11,358 maven-model.license
09/07/2018  01:27 AM            11,358 maven-plugin-api.license
09/07/2018  01:27 AM            11,358 maven-repository-metadata.license
09/07/2018  01:27 AM            11,358 maven-resolver-api.license
09/07/2018  01:27 AM            11,358 maven-resolver-connector-basic.license
09/07/2018  01:27 AM            11,358 maven-resolver-impl.license
09/07/2018  01:27 AM            11,358 maven-resolver-provider.license
09/07/2018  01:27 AM            11,358 maven-resolver-spi.license
09/07/2018  01:27 AM            11,358 maven-resolver-transport-wagon.license
09/07/2018  01:27 AM            11,358 maven-resolver-util.license
09/07/2018  01:27 AM            11,358 maven-settings-builder.license
09/07/2018  01:27 AM            11,358 maven-settings.license
09/07/2018  01:27 AM            11,358 maven-shared-utils.license
09/07/2018  01:27 AM            11,358 maven-slf4j-provider.license
09/07/2018  01:27 AM            12,637 org.eclipse.sisu.inject.license
09/07/2018  01:27 AM            12,637 org.eclipse.sisu.plexus.license
09/07/2018  01:27 AM            23,505 plexus-cipher.license
09/07/2018  01:27 AM            11,358 plexus-component-annotations.license
09/07/2018  01:27 AM            11,358 plexus-interpolation.license
09/07/2018  01:27 AM            23,505 plexus-sec-dispatcher.license
09/07/2018  01:27 AM            11,358 plexus-utils.license
09/07/2018  01:27 AM               194 slf4j-api.license
09/07/2018  01:27 AM            11,358 wagon-file.license
09/07/2018  01:27 AM            11,358 wagon-http.license
09/07/2018  01:27 AM            11,358 wagon-provider-api.license
```
after:
```
 Directory of lib\MNG-6414

09/09/2018  06:02 PM               194 jcl-over-slf4j.license
09/09/2018  06:02 PM                 0 jsr250-api.license
09/09/2018  06:02 PM            12,637 org.eclipse.sisu.inject.license
09/09/2018  06:02 PM            12,637 org.eclipse.sisu.plexus.license
09/09/2018  06:02 PM               194 slf4j-api.license
```
Maven's zip ackage size decreased from 9 011 332 to 8 867 711 bytes.

**Comment by hboutemy** [comment]
wow, little cause with bigger effects than expected!
nice catch!

**Comment by jira-importer** [comment]
Resolve #7442

**Pull request merged**
