### PR TITLE
Improved visibility of collections and variables across multiple threads

### PR DESCRIPTION
**Pull request by Tibor17**
Upon our discussion with Karl in 
http://maven.40175.n5.nabble.com/Maven-Commit-3b671d07340b002e13775883d09e7f7e0d9a3c49-td5821660.html
i have improved MavenProject.java and surrounding code.

### CODE REVIEW

**Comment by Tibor17** [comment]
@hboutemy 
@jvanzyl 
Any objections to push this?

**Comment by jvanzyl** [comment]
As a check did you run the ITs? There are a few collections that are expected to be mutable unfortunately. I haven't looked at the patch in detail to check but I can look early next week.

Ideally all configuration and projects should be immutable before the build starts. I made a significant change to the project building a few months ago which is a step in the right direction, and the next major refactor is entire construction of project with respect to plugin execution. Right now you can't know all the compile source roots without running a plugin which is admittedly bad, it should be declarative but it's not.

I was planning on talking about immutability and parallelism in the Maven Dev Hangout on January 15th if you're interested.

At any rate, if you know the ITs pass I'll take a look at the patch.

**Comment by Tibor17** [comment]
@jvanzyl 
My ant build says BUILD SUCCESS.
I saw your TODO comments moreless related to immutable objects.
Currently the code is not ready for immutable objects and therefore it was simple toapply *concurrent* collections.
One way or another immutable objects:
+ improve code clarity
+ safe enough in multiple-threads env
+ every s/w is spaghetti code, but using immutable objects you simply put the barriers between parts of the code and then the contributors are willing to make bigger changes and spend their spare time
+ if this speeds up the development, you have chance to push the compettitors away

I am watching Maven Dev Hangout.
Will be glag if you talk about Maven stability.

The method `#getMetadataList()` returns unmodifiable collection, but It can be changed.

**Comment by jvanzyl** [comment]
Ant build? The ITs are in a separate repository. This may be helpful:

http://takari.io/2014/06/01/contributing-to-maven-core.html

There are are 700+ integration tests that need to pass for any change.

**Comment by Tibor17** [comment]
The link should be in README.md.
Look at README file @ JUnit and JavaHamcrest projects, where the most
important is build status @ CloudBees and Travis
https://github.com/junit-team/junit/blob/master/README.md
https://github.com/hamcrest/JavaHamcrest
Why such important projet does not have privilegies in CloudBees and free
account?

**Comment by jvanzyl** [comment]
Tibor,

Empirically on the daily basis I work on a 900 module build using 8 threads with 1500+ developers and there aren't many concurrency issues. I'm not keen on incorporating this patch without a demonstration there is something wrong in the core. Igor and I took a look at creating a harness to test multithreaded builds but it's hard. But I think that needs to be done first to show that something is actually wrong. There may very well be but as I said empirically I haven't actually seen anything.

I would actually rather go the other way and create a patch that makes everything immutable and then watch a bunch of the ITs fail and then work toward making them work, or removing ITs that expect to mutate state. I think this will be far more informative and provide a path to cleaning up the core.

If I had witnessed all sorts of problems with concurrency issues I might be inclined to accept the patch but I don't think it particularly helps. Are you seeing lots of concurrency issues? If the code that clones the project per build thread is removed, yes, things don't work very well.

I'm happy to discuss more. Maybe pop into IRC, but as-is I'm not inclined to accept this. Also have you run the Maven ITs with your patch?

**Comment by Tibor17** [comment]
Hi Jason, 

the point of this patch is to force the devs to write `safe` code. Immediately as I have seen the code I recognized, same as Herve stated in my email, that the code is too open inside.
This means I wanted immutable objects in the core too, but ut is big change which needs the author(s) to improve the core.

I wasn't aware of ITs.
I would appreciate Jenkins build, like CloudBees or ASF machine, where I would be able to change the repo URL from master to my GitHub personal branch.
I don't kow how about you guys, but keeping the PC running and building the core with every bug appeared with my code change consumes the electricity I have to pay.

**Comment by jvanzyl** [comment]
Apache is resource constrained so we have what we have. Please feel free to work with Stephen on the dev list to have something better setup. I'm open to improvement. Anyone who has contributed has not found running the ITs all that troublesome but that's the starting point of any further discussion. The patch can't even be considered if the ITs passing hasn't been validated.

If you don't want to run them to verify using[1] then I'll do it if someone doesn't get to it first. I'm in IRC if you want to discuss the patch.

[1]: http://takari.io/2014/06/01/contributing-to-maven-core.html

**Comment by jvanzyl** [comment]
Does the patch apply for you? I just tried:

Applying: Improved visibility of collections and variables across multiple threads
error: patch failed: maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionResult.java:28
error: maven-core/src/main/java/org/apache/maven/execution/DefaultMavenExecutionResult.java: patch does not apply
Patch failed at 0001 Improved visibility of collections and variables across multiple threads
The copy of the patch that failed is found in:
   /Users/jvanzyl/work/z-maven-with-pr-34/maven/.git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Applying 34.patch failed.

**Comment by Tibor17** [comment]
Jason, 
Don't worry about this patch, I'll close it - since I have private copy and the diff.
I will wait for you patch, and then I'll go through the diff and I will look for visibility issues again.
I reported one concurrency issue in JIRA against Maven two years ago. Since then I don't build Maven modules in parallel - personal attitude.
Usually the devs don't know that they have to think of Java concurrency at the point of architecture design. Usually they have no imagination of what happens with thread private copy of variables and when these copies reconcile with main memory via memory barriers and how this is related to Java Memory Model.

**Comment by jvanzyl** [comment]
Sounds like a plan.

**Comment by jira-importer** [comment]
Resolve #8458

**Pull request closed without merging**
