### PR TITLE
[MNG-7531] Upgrade to SLF4J 2.0.0

### PR DESCRIPTION
**Pull request by slachiewicz**
Following this checklist to help us incorporate your
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by rmannibucau** [comment]
Can we do it in 3.x since it is a breaking change for mojos (the new SPI by itself is one which can breaking functional logs)?

**Comment by slachiewicz** [comment]
Could you describe where it breaks plugins?

**Comment by slachiewicz** [comment]
This is branch for 3.9.0 release

**Comment by michael-o** [comment]
I don't consider this to be appropriate for 3.x and must be greatly analyzed for 4. I rather see little benefit since too much code is still on Plexus Logging.

**Comment by slachiewicz** [comment]
Yes, we export only API, so if plugins wants own implementation - they can use it, why not. Here we change implementation for output and that can be changed globally (we support logback, Log4j2, slf4j and out impl) in maven installation directory (or command line). So if plugin use slf4j simpe v 1.7 it still should work oob i think.

**Comment by slachiewicz** [comment]
@rmannibucau let's be concrete where we have API for logging for V4?
What exact plugins will crash with this slf4j upgrade?

**Comment by rmannibucau** [comment]
Where: it is a work in progress (pr available) but we know we dont promote slf4j - already for 3.x - as a should be used api.
What breaks: plugins location slf4j from .class and creating a custom loader from there. Severals in server area do that but also some forking cause default classloading is not good enough, just test it.

Can be okish for v3 if you add a compat class for 1.7.x loading mecanism if you really want this upgrade (but there is no new feature for users so really think we can skip it).

**Comment by michael-o** [comment]
Please remember: https://issues.apache.org/jira/browse/MNG-6275 and https://issues.apache.org/jira/browse/MNG-6371. Maybe related.

**Comment by kwin** [comment]
> (but there is no new feature for users so really think we can skip it).

I disagree here, https://slf4j.org/manual.html#fluent was added

**Comment by kwin** [comment]
This is not necessarily about logging in Mojos, but about logging in Maven Core itself and in transitive dependencies.

**Pull request closed without merging**
