### PR TITLE
[MNG-8312] Generate the BOM automatically

### PR DESCRIPTION
**Pull request by gnodet**
JIRA issue: [MNG-8312](https://issues.apache.org/jira/browse/MNG-8312)

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Comment by gnodet** [comment]
I wonder if we should make the BOM have no parent at all, that would be easier to manage. 
@slawekjaranowski @cstamas  ?

**Comment by cstamas** [comment]
Yup, BOM is generated and is attached, it does not need SCM and parent...

**Comment by cstamas** [comment]
Also, our plugins are akin to "fat BOM" as well, to not have add those "locked to Maven version" comments all over the place

**Review by cstamas — APPROVED** [review]
Dont we want "fat BOM" as well? Or what is your plan?

**Comment by gnodet** [comment]
Skinny BOM: https://gist.github.com/gnodet/53bf123caa20845752a9b842686acf44
Fat BOM: https://gist.github.com/gnodet/f366cb07e3876184c20d96212924e418

**Comment by cstamas** [comment]
I love the "fat" one! No more "locked to maven...." comment on properties in plugins!

**Comment by jira-importer** [comment]
Resolve #9551

**Pull request merged**
