### PR TITLE
MPOM-211

### PR DESCRIPTION
**Pull request by silkentrance**
- add id property to Scm model
- add hashCode() and equals() methods to Scm model
- add additional tests to Scm model

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.
 - [x] The changes are trivial and do not require to run the Core IT test suite?

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by silkentrance** [comment]
Aside Note:

Looking at maven-scm-api/AbstractScmMojo, I see that it supports the server id via the repository host parameter, looking up the required credentials via that id.

Having Scm model support the id property would require the AbstractScmMojo to also look for an optional id and prefer that over the host:port that is currently being used for looking up the credentials from settings.xml/servers.

**Comment by silkentrance** [comment]
Alternatively, the maven-release plugin should be refactored so that it will determine the host:port and look up the server id from that instead.

**Comment by silkentrance** [comment]
see also https://issues.apache.org/jira/browse/MPOM-211

**Comment by silkentrance** [comment]
Backing out of this since the actual change needs to be made to maven-scm and maven-release, with the two sharing the strategy of looking up the repository's credentials via the settings.xml.

Closing.

**Comment by jira-importer** [comment]
Resolve #8080

**Pull request closed without merging**
