### PR TITLE
[MNG-7863] don't email on s390 failures. The regular results are enough.

### PR DESCRIPTION
**Pull request by elharo**
fixes MNG-7863

### CODE REVIEW

**Review by gnodet — APPROVED** [review]
LGTM, though I have almost no knowledge in Jenkins pipelines configuration...

**Comment by olamy** [comment]
@elharo not sure why you remove this as he did this on purpose with this PR https://github.com/apache/maven/pull/1213 at least you should ask him if he really wants to be removed...

@kun-lu20 ping

**Comment by olamy** [comment]
@elharo ping

**Comment by elharo** [comment]
I stand behind my change, which was filed as a JIRA and approved. I would have CC's some additional reviewers had I noticed the earlier changes at the time, or had their been comments in the file indicating why there was this strange email address for no obvious reason.  Nonetheless those earlier changes were wrong and should have been reverted. The CI should not send email to random external addresses. This is not the correct way to monitor a CI.

Furthermore the S390 builds were in fact broken. See MNG-7864. That's why I noticed this in the first place. If the email was being sent, it wasn't being read and acted on.

**Comment by olamy** [comment]
@kun-lu20 if you need this you need to convince @elharo . Sorry but it's really beyond my motivation... 
good luck...

**Pull request merged**
