### PR TITLE
[INFRA-23217] : s390x Jenkinsfile

### PR DESCRIPTION
**Pull request by srajmane**
- [ ] [JIRA issue](https://issues.apache.org/jira/browse/INFRA-23217) 

Adding support for IBM Z (s390x) into Apache Maven Jenkins CI. 
s390x nodes are already available: https://jenkins-ccos.apache.org/view/all/

### CODE REVIEW

**Comment by srajmane** [comment]
@michael-o @cstamas @khmarbaise Could you please have a look?

**Comment by cstamas** [comment]
@slawekjaranowski @olamy you are more versed in Jenkins, please take a look

**Comment by srajmane** [comment]
@slawekjaranowski @olamy 
Could you please kindly review this PR? Thank you very much!

**Comment by srajmane** [comment]
@michael-o @cstamas @slawekjaranowski Could you please kindly review this PR?

**Comment by slawekjaranowski** [comment]
We have s390 build now ... so it can be closed.

**Pull request closed without merging**
