### PR TITLE
[MNG-7020] Remove Maven 2 WagonExcluder backward compat code

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Review by rfscholte — APPROVED** [review]
Based on just the code this looks good and based on the comment this should be safe to do. I don't know where to expect any impact, if any.

**Comment by michael-o** [comment]
@rfscholte Since you approved this, can I go on and merge?

**Comment by rfscholte** [comment]
IIRC this triggered a new issue. I'll remove my approval and need to have another look at it.

**Comment by michael-o** [comment]
Sure...

**Review by cstamas — APPROVED** [review]
Unsure what to say here...

This was in place for Maven2 plugins (running in Maven3). Hopefully today they will break with Maven4, so WagonExcluder is really not needed as plugin will not even execute. Still, IMO we'd need some safety "thing" maybe and simply reject plugins declaring or any Maven artifact having version 2.x, just to be on safe side? (like prerequisite, but other way around)

**Review by slachiewicz — APPROVED** [review]

**Comment by rfscholte** [comment]
@cstamas @michael-o I thought we also worked on that "require maven-plugin-api version", but can't find the ticket. For me that must be implemented first before accepting this PR.

**Comment by michael-o** [comment]
> 
> 
> @cstamas @michael-o I thought we also worked on that "require maven-plugin-api version", but can't find the ticket. For me that must be implemented first before accepting this PR.

That is true and that is why I have not yet merged it.

**Comment by slachiewicz** [comment]
That was MNG-7122 https://github.com/apache/maven/commit/184db56e4f149fd0b6931a72af22fa184b15a2bd

**Comment by michael-o** [comment]
@rfscholte Can you reassess please?

**Review by mthmulders — COMMENTED** [review]
All integration tests are failing - could it be it's an outdated version of the IT's? Other than that, it looks fine to me.

**Comment by michael-o** [comment]
> 

Let me check...

**Comment by michael-o** [comment]
@mthmulders I have rebased the branch, I guess the ITs should pass. Let's wait.

**Comment by jira-importer** [comment]
Resolve #8019

**Pull request closed without merging**
