### PR TITLE
[MNG-6207] display deprecation build warning for dependencies with scope 'system' declaration

### PR DESCRIPTION
**Pull request by dejan2609**
JIRA ticket: [MNG-6207: Create WARNINGs in case of using system scope](https://issues.apache.org/jira/browse/MNG-6207)

**Note:** this PR is created instead of  #119 

@khmarbaise: FYI

### CODE REVIEW

**Comment by khmarbaise** [comment]
First build has failed based on [violated checkstyle rules](https://builds.apache.org/view/M-R/view/Maven/job/maven-3.x-jenkinsfile/job/MNG-6207/1/console). So best is before you open a pull request to run a full build via `mvn clean verfiy` on the whole Maven project...the checkstyle rules will be checked as part of the build...

**Comment by khmarbaise** [comment]
Second build after fixing the checkstyle issues has worked. Integration into master done. You can close the pull request. Thank for your help to make Maven better.

**Comment by dejan2609** [comment]
Just for the record: somehow it slipped of my mind that `package` phase doesn't execute integration tests (http://maven.apache.org/ref/3.5.0/maven-core/lifecycles.html#default_Lifecycle) and hence this checkstyle error pass unnoticed on my side:
> [ERROR] src/main/java/org/apache/maven/model/validation/DefaultModelValidator.java[471:104] (blocks) LeftCurly: '{' should be on a new line.

Thanx @khmarbaise for this correction and for overall review.

**Comment by dejan2609** [comment]
Just on more thing that recalled from my memory: I did tried to execute tests  (http://maven.apache.org/core-its/core-it-suite) like this: `mvn clean test -Prun-its` but I received warning that profile doesn't exists: 
> [WARNING] The requested profile "run-its" could not be activated because it does not exist.

**Comment by jira-importer** [comment]
Resolve #7241

**Pull request closed without merging**
