### PR TITLE
[MNG-7727] Remove DefaultMavenProfilesBuilder

### PR DESCRIPTION
**Pull request by gnodet**
JIRA issue: https://issues.apache.org/jira/browse/MNG-7727

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
Does this make sense to fiddle with compat although we want to get rid of it?

**Review by elharo — CHANGES_REQUESTED** [review]
I'm not sure I understand the purpose of this. This also is singificant enough to deserve a JIRA issue.

**Comment by gnodet** [comment]
> I'm not sure I understand the purpose of this. This also is singificant enough to deserve a JIRA issue.

The purpose is to:
 * remove references to plexus-utils
 * fix encoding problems with BOM parsing

But given, the code is not used afaik, I'm not sure it's worth fixing it, so removing also solves the problem.

**Comment by gnodet** [comment]
> Does this make sense to fiddle with compat although we want to get rid of it?

Well, we want to get rid of it, but I think that won't be tomorrow. So in the mean time....

**Comment by michael-o** [comment]
> > Does this make sense to fiddle with compat although we want to get rid of it?
> 
> Well, we want to get rid of it, but I think that won't be tomorrow. So in the mean time....

I see, then a JIRA issue is imperative

**Review by rmannibucau — APPROVED** [review]

**Comment by gnodet** [comment]
@elharo would you prefer removing the `DefaultMavenProfilesBuilder` implementation class completely ?

**Comment by elharo** [comment]
When did we deprecate it? If we can simply remove it in 4.0.0, that solves all problems. I will raise a question on the dev mailing list about whether we should start ripping out the deprecated methods and classes in 4.0.0.

I do not think we should replace it with a broken version that simply returns null. Compile-time errors are better than runtime errors.

**Comment by rmannibucau** [comment]
@elharo it already returns null in 99% of the cases so guess this is not a behavior change

**Comment by slachiewicz** [comment]
maybe backport it to 3.9?

**Comment by gnodet** [comment]
> maybe backport it to 3.9?

For what benefit ?

**Comment by slachiewicz** [comment]
> > maybe backport it to 3.9?
> 
> For what benefit ?

to receive faster feedback from end users

**Review by elharo — APPROVED** [review]
LGTM. I'm happy for these classes to be deleted.

**Pull request merged**
