### PR TITLE
[MNG-5738] Addition of command line flag '--legacy-reactor-resolution'.

### PR DESCRIPTION
**Pull request by ChristianSchulte**
See http://jira.codehaus.org/browse/MNG-5738

This pull request will add a new command line flag '--legacy-reactor-resolution' to Maven to allow disabling workspace resolution. The name was choosen to be consistent with '--legacy-local-repositoy'.

### CODE REVIEW

**Comment by ChristianSchulte** [comment]
Regarding the recent discussion about releasing 3.2.6 as 3.3.0: Could this be part of 3.3.0, please ?

**Comment by jvanzyl** [comment]
No, I don't think it's a good idea to be honest.

**Comment by jvanzyl** [comment]
I thought we agreed you were closing this pull request.

**Comment by ChristianSchulte** [comment]
I am still convinced that it is a good idea to allow Maven 3 'mvn site-deploy' to work the same way as Maven 2. What's the issue with that ?

**Comment by jvanzyl** [comment]
The behaviour you describe you need is wrong and the I'm convinced at this point that the site plugin should just be a stand-alone tool and was implemented incorrectly in Maven 2.x as a lifecycle and it continues to pervert Maven core and that everything to do with reporting should be ripped out of the core once and for all. I will help extract the logic out of core and help make the Site plugin an independent tool, but I'm not integrating this patch.

**Comment by ChristianSchulte** [comment]
There are situations the behaviour is not wrong, in my opinion. Resolution for non project `<packaging>` related lifecycles, for example. Maven could detect this automically based on various criteria: not the default lifecycle, not project packaging related, attribute of a lifecycle, not executed at an even hour, etc but it does not. No issue. The command line option lets you choose the needed behaviour yourself without being forced (issue!) by Maven to anything. I can live with this not getting committed. That's not the point. For me that standalone site building tool would exactly be `mvn --legacy-reactor-resolution site`.

**Comment by jvanzyl** [comment]
The crux of my argument is that Maven should not be doing anything other than building, non build lifecycles were a mistake and have done nothing but make the core more complex and make it harder to evolve. Generating a site is just an invocation of a tool, it's not a lifecycle. The site plugin lives somewhere between the core and a more sophisticated plugin and honestly has just become a huge mess. If you want to make a stand-alone site tool, then it should be so and not require magical features in Maven core.

**Comment by ChristianSchulte** [comment]
Could not be more confusing.

Apache Maven is a software project management and comprehension tool. Based on the concept of a project object model (POM), Maven can manage a project's build, reporting and documentation from a central piece of information.

No more 'reporting and documentation' in the future makes the 'from a central piece of information' meaningless.

**Comment by jvanzyl** [comment]
There's nothing wrong with there being a site plugin, configuration for the a site housed within the site plugin and running the site plugin. What is not right is how it was fused into the base level of the POM and not contained to its plugin and how it's special requirements have created several inconsistencies in the core that have made it hard to evolve. What is also not right is requiring special resolution magic for a specific plugin to run. You think that creating a special mode of resolution for one specific Maven plugin seems reasonable? I personally do not.

**Comment by ChristianSchulte** [comment]
```
parent
  module1
  module2
```

With Maven 3 I need to

```
cmd>cd parent && mvn site-deploy -N && cd module1 && mvn site-deploy && cd ../module2 && mvn site-deploy
```
to get the same behaviour as executing

```
cmd>cd parent && mvn site-deploy
```

with Maven 2. So in Maven 3 I would like to

```
cmd>cd parent && mvn --legacy-reactor-resolution site-deploy
```

Pretty much the same way the following command line flag can be used to make Maven 3 behave the same way as Maven 2.

```
 -llr,--legacy-local-repository         Use Maven 2 Legacy Local
                                        Repository behaviour, ie no use of
                                        _remote.repositories. Can also be
                                        activated by using
                                        -Dmaven.legacyLocalRepo=true
```

**Comment by hboutemy** [comment]
Reporting is a key feature of Maven I strongly want to keep working (or fix when we introduced problems while improving build consistency during Maven 3.x refactoring)

I like the option idea to fix (or workaround) the described use case, but I understand Jason resistance to adding it since it causes inconsistency. I still don't have strong final opinion if this is the way to go or not, either only as a temporary workaround or as a real permanent feature.

What I know is that, while working on maven-reporting-exec, ie the component that launches report mojos during site generation, in MSHARED-266 for version 1.2, I found that there were more than this resolution issue that makes reporting mojo execution a special case: build forking and aggregate are other special cases that cause issues, IMHO
And every change I could imagine to avoid build forking worked with most report plugins, but not with cobertura-maven-plugin: "producing artifacts or consuming artifacts" is a key factor, ie most reports are "consuming artifacts" but a few are "producing artifacts".

I imagine this idea about "disabling workspace resolution" will affect cobertura-maven-plugin: since this report is producing artifacts, it will require workspace resolution, isn't it?
Christian, did you try with a build that uses cobertura-maven-plugin?

**Comment by ChristianSchulte** [comment]
What's the state of the current head as of today ? I just wanted to test the cobertura plugin but cannot build the site with Maven 3.2.6-SNAPSHOT due to the following exception. That's happening with a released project known to work. So `mvn site -e` with Maven 3.2.5 succeeds whereas 3.2.6-SNAPSHOT fails.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project jomc-parent: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.4:site failed: A required class was missing while executing org.apache.maven.plugins:maven-site-plugin:3.4:site: org/slf4j/spi/LocationAwareLogger
```

```
Caused by: java.lang.NoClassDefFoundError: org/slf4j/spi/LocationAwareLogger
        at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:157)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:289)
        at org.apache.commons.digester.Digester.<init>(Digester.java:308)
        at org.apache.velocity.tools.config.XmlFactoryConfiguration.read(XmlFactoryConfiguration.java:117)
        at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:140)
        at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:116)
        at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:91)
        at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:69)
        at org.apache.velocity.tools.config.FileFactoryConfiguration.read(FileFactoryConfiguration.java:59)
        at org.apache.velocity.tools.config.ConfigurationUtils.getDefaultTools(ConfigurationUtils.java:79)
        at org.apache.velocity.tools.config.ConfigurationUtils.getAutoLoaded(ConfigurationUtils.java:176)
        at org.apache.velocity.tools.ToolManager.autoConfigure(ToolManager.java:74)
        at org.apache.velocity.tools.ToolManager.<init>(ToolManager.java:68)
        at org.apache.velocity.tools.ToolManager.<init>(ToolManager.java:59)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.createVelocityContext(DefaultSiteRenderer.java:427)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.generateDocument(DefaultSiteRenderer.java:565)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderDocument(DefaultSiteRenderer.java:422)
        at org.apache.maven.doxia.siterenderer.DoxiaDocumentRenderer.renderDocument(DoxiaDocumentRenderer.java:51)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:311)
        at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:129)
        at org.apache.maven.plugins.site.render.SiteMojo.renderDoxiaDocuments(SiteMojo.java:261)
        at org.apache.maven.plugins.site.render.SiteMojo.renderLocale(SiteMojo.java:172)
        at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:141)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 21 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.spi.LocationAwareLogger
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 45 more
```

**Comment by hboutemy** [comment]
the current head is expected to be released soon: we'll need to investigate before releasing, IMHO

comparing 3.2.5 to actual head, slf4j version did not change: 1.7.5

when reading the changelog for head, this could perhaps be related to http://jira.codehaus.org/browse/MNG-5742 , which is the only issue I see that was intended to change classloading (this may of course be worse: unintented change when doing something else)

I tested with m-site-p ITs and found that the issue happen with m-javadoc-p too (without failing the build): see full-reporting IT output log:
[WARNING] An issue has occurred with maven-javadoc-plugin:2.9.1:javadoc, skipping LinkageError org/slf4j/spi/LocationAwareLogger, please report an issue to Maven dev team.
java.lang.NoClassDefFoundError: org/slf4j/spi/LocationAwareLogger

I created http://jira.codehaus.org/browse/MNG-5779 (as critical) to track the issue

**Comment by ChristianSchulte** [comment]
I have no experience with the cobertura plugin. I just added

```
<reportPlugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>cobertura-maven-plugin</artifactId>
  <version>2.7</version>
</reportPlugin>
```

to the configuration of the site plugin of a working project. Executing `mvn site -e` with Maven 3.2.5, site building succeeds. Using Maven 3.3.0-SNAPSHOT with the latest changes to head, the following exception is thrown.

```
[ERROR] Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at net.sourceforge.cobertura.instrument.InstrumentMain$LoggerWrapper.<init>(InstrumentMain.java:165)
        at net.sourceforge.cobertura.instrument.InstrumentMain$LoggerWrapper.<init>(InstrumentMain.java:164)
        at net.sourceforge.cobertura.instrument.InstrumentMain.<clinit>(InstrumentMain.java:66)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 3 more
```

That exception is not thrown using Maven 3.2.5. There still seems to be a class loading issue.

**Comment by mcculls** [comment]
@ChristianSchulte I believe that was recently fixed in master: https://github.com/apache/maven/commit/57a6196422873eaf2f00a282b33894a74dcfd19c

**Comment by hboutemy** [comment]
yes, it was just fixed in http://jira.codehaus.org/browse/MNG-5779

**Comment by ChristianSchulte** [comment]
That exception is thrown with a recent head.
See https://github.com/ChristianSchulte/maven

**Comment by hboutemy** [comment]
another issue found regarding slf4j, this time with cobertura plugin, during instrumentation http://jira.codehaus.org/browse/MNG-5783 created, with the difference in {{Populating class realm plugin>org.codehaus.mojo:cobertura-maven-plugin:2.8-SNAPSHOT}}

**Comment by jvanzyl** [comment]
I chatted with Igor and he's going to try and change the way the classpath is constructed for plugins. The issue here appears to be forking where SLF4J is filtered out of the classpath which is going to cause issues. For in VM use the classrealm needs to be filtered because we're exporting from the core but while forking we'll leave the classpath untouched. We'll try that and see if the ITs all work and fixes this particular issue.

**Comment by ifedorenko** [comment]
http://jira.codehaus.org/browse/MNG-5783 should be fixed in master now. I've provided explanation of the problem and links to the fix and corresponding IT changes in the jira.

**Comment by hboutemy** [comment]
thank you for your work: the bugs are fixed now, cobertura-maven-plugin and m-site-p ITs pass

now back to the start of this PR :)

Christian: did you know about MPIR-322? I know it's not exactly what you are expecting with this PR, but does it already help (for my use cases, it helps...)

**Comment by ChristianSchulte** [comment]
I am really no fan of adding just another workaround.

@Jason: Are you suggesting to split site rendering from report data generation ? So the build lifecycle produces report data attached to the project picked up during site rendering ? Cobertura instrumentation takes place during the build lifecycle and site rendering picks up the data generated there without compiling and running any tests any more, for example ? Not talking about picking up data from the build output directory here but resolving that data based on e.g. classifiers.

**Comment by jvanzyl** [comment]
@ChristianSchulte Definitely more along the lines of what you describe where there is no site lifecycle. I think this is a design error in allowing non-build lifecycles. But yes, having the build produce data that can be consumed by other tools whether that be a reporting tool, metrics tool, or anything else is the way it should work.

**Comment by ChristianSchulte** [comment]
@jvanzyl: You would not want the `test-jar` goal to package compiled test classes instrumented by some reporting tool, would you ? So the forking logic needs to change in a way that a forked lifecycle will run isolated (e.g. with its own output directory). A rather incompatible change in the core requiring new reporting plugins. Something to be done in the next Maven version introducing a new POM version.

**Comment by jvanzyl** [comment]
No, and I would not advocate the use of tools like that which would distort the standard lifecycle and promote tools like Jacoco that do not require things like that. As a tool that collaborates with the standard build lifecycle it should be able to operate on either data emitted by the eventing system in Maven or operate on, or use artifacts as they are produced from the system. Like adding an agent to dynamically instrument code. Tools like Clover and Cobertura are frankly terrible tools that are super hard to integrate and we've done some stupid things in the core to accommodate them and that was categorically a mistake. If things like Clover and Cobertura break in Maven 4.x I honestly don't care. They are designed incorrectly in my opinion or were designed for a time where there didn't exist proper support to be truly independent from how Maven operates. The model should be "report on standard data produced, or by looking at standard artifacts being produced", not I'm going to "jam myself into the process to completely alter how the build works to get the data I need."

**Comment by ChristianSchulte** [comment]
I totally agree with this. Do not cripple Maven to support bad ideas or concepts. "Supported by Maven" as an indicator for something. Not supported by Maven so not worth integrating means Maven must be ideal.

**Comment by jvanzyl** [comment]
And I have been talking about this for years but have admittedly done nothing yet. But I believe the direction to go is to make some example data generators that can be used by tools to display the information. I think the site plugin has just grown into completely the wrong thing. It's generally terrible at generating standard doco as things like Jekyll just destroy it in terms of usability and community. Insofar as reporting it's just too invasive and it needs to be fully extracted from Maven's core so Maven can evolve. A personal goal is to entirely remove site/reporting logic from Maven's core in 4.x. This does not mean I want to wreck reporting but to create a facility that allow reporting tools to get at the data it needs to produce the reports that users expect.

**Pull request closed without merging**
