### PR TITLE
[MNG-7471] 3.9.x Make Resolver util and connector-basic provided

### PR DESCRIPTION
**Pull request by cstamas**
Problem: resolver spi, impl and connector-basic has changes in 1.8.0 (SPI interface RepositoryLayout got new method, that is implemented in connector-basic, and code from impl is using it). But, Maven core exports only resolver api, spi and impl packages, while the rest is at mercy of a plugin. This means ,that these artifacts (api, spi and impl) will always come from Maven core, whatever version plugin declares, while the "rest" (connector-basic and util) will be of version that plugin declares. The current state hence prevented ANY KIND of changes on SPI interfaces that would be implemented in connector-basic (which is the case in Resolver 1.8.0).

Solution: make all these resolver artifacts "provided" (to behave like maven-core or maven-plugin-api is behaving): simply put, whatever resolver artifact plugin depends on, it should NOT use it's own version, but the version from Maven. This ensures that api-spi-impl-connector-basic as "aligned" and are same version.

Details:

The change is to make util is exportedArtifact AND exportedPackage, while connector-basic is only exportedArtifact.

Reasoning:
* exportedArtifact -- prevents "own" artifact to be added to realm
* exportedPackage -- makes it "visible" in realm

So, this basically prevents bad versions of util and connector-basic
enter the plugin realm (as they will be not added to it), while
util remains "visible" to plugins, as the intent was, most
common due GenericVersions etc.

This change also results in simpler expectations to plugin developers:
resolver libraries should really behave like maven-core or maven-compat:
when plugin declares dependency on these (w/ scope provided as best
practice), they really get version of these that are of version that
maven runs in, not version they declare. So same thing happens now with
resolver: you will get same version of resolver that maven uses your plugin
runs in. 

Before this change, it was a mixed bag: api, spi and impl was from maven,
while util and connector-basic was version you pulled in as dep.

---

https://issues.apache.org/jira/browse/MNG-7471

### CODE REVIEW

**Comment by cstamas** [comment]
> What does this logically change and the reasoning?

Did you read PR description fully? :smile:

**Comment by michael-o** [comment]
Now I did. Honestly, I have no clue here. I totally trust your judgement.

**Comment by michael-o** [comment]
Stupid question: Do we need an IT which proves that these changes are required?

**Comment by cstamas** [comment]
> Stupid question: Do we need an IT which proves that these changes are required?

https://github.com/apache/maven-integration-testing/pull/158

**Comment by cstamas** [comment]
The CI failed on macOS as for some reason Bootstrap failed, and hence, many unrelated ITs failed as well (as things were not present in local repo)

**Comment by slawekjaranowski** [comment]
> The CI failed on macOS as for some reason Bootstrap failed, and hence, many unrelated ITs failed as well (as things were not present in local repo)

reason:
```
transfer failed for https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom: Operation timed out (Read failed)
```
try re-run filed build

**Comment by cstamas** [comment]
> reason:...

Whatever the reason is, it is unrelated to change in this PR, that was my point. Probably some networking issue on GH side...

**Comment by slawekjaranowski** [comment]
> Whatever the reason is, it is unrelated to change in this PR, that was my point. Probably some networking issue on GH side...

exactly GH issue ...

**Review by gnodet — APPROVED** [review]

**Review by slawekjaranowski — APPROVED** [review]

**Comment by michael-o** [comment]
Testing again...

**Comment by cstamas** [comment]
Merged manually:
maven-3.9.x 4de39476ff690774ece57637e91653d2ef234fd3
master a83ed86c4850c3fc09e5623eb00869ab3e39c959

**Comment by rbourbonnavarro** [comment]
Hi @cstamas, why was the package of `maven-resolver-connector-basic` not exported as the one of `maven-resolver-util` was? I have a use case where I'm setting up the [`RepositorySystem`](https://github.com/apache/maven/blob/ac0bc5541e3d1a19b22c4138c354237c8202e11f/maven-core/src/main/java/org/apache/maven/repository/RepositorySystem.java#L42) with the [`DefaultServiceLocator`](https://github.com/apache/maven-resolver/blob/fa5d6cf96618cca3ea5b8dcba48b315f68586c78/maven-resolver-impl/src/main/java/org/eclipse/aether/impl/DefaultServiceLocator.java#L93) and I can't add the [`BasicRepositoryConnectorFactory`](https://github.com/apache/maven-resolver/blob/fa5d6cf96618cca3ea5b8dcba48b315f68586c78/maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory.java#L48) as the implementation for [`RepositoryConnectorFactory`](https://github.com/apache/maven-resolver/blob/fa5d6cf96618cca3ea5b8dcba48b315f68586c78/maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/RepositoryConnectorFactory.java#L32) because I don't have access to it. 
How is the right way to achieve this in `Maven 3.9`?

**Comment by cstamas** [comment]
Service locator is deprecated, will be removed, so stay away from it. See instead this https://github.com/maveniverse/mima

**Pull request closed without merging**
