### PR TITLE
Switch to official Guice 4.0

### PR DESCRIPTION
**Pull request by mcculls**
For anyone interested in using Guice 4.0 with Maven :)

PS. you should use Eclipse/Sisu 0.3.1 with Guice 4.0, luckily master branch is already using that version

### CODE REVIEW

**Comment by jvanzyl** [comment]
Would be a nice change. Anything of note we should be concerned about API/SPI, or performance wise?

**Comment by mcculls** [comment]
The only difference remaining between this and sisu-guice is support for `@Inject`ion of SLF4J loggers, but I don't believe that's used much, if at all. Personally these days I prefer to create loggers using the static factory method.

Performance should be comparable, although I have yet to run a detailed comparison - I'd be interested in feedback from people using large or complicated builds.

**Comment by jvanzyl** [comment]
To be clear are you saying that the injection of loggers is not supported with Guice 4? I don't think it's used much but I believe it is used. Yes, I have been using the static factory method, or lombok.

Maybe this is the impetus to get the perf harness back up and running to check. I'll merge it here locally and try it for a week.

On Apr 29, 2015, at 6:03 AM, Stuart McCulloch <notifications@github.com> wrote:

> The only difference remaining between this and sisu-guice is support for @Injection of SLF4J loggers, but I don't believe that's used much, if at all. Personally these days I prefer to create loggers using the static factory method.
> 
> Performance should be comparable, although I have yet to run a detailed comparison - I'd be interested in feedback from people using large or complicated builds.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

Thanks,

Jason

----------------------------------------------------------
Jason van Zyl
Founder, Takari and Apache Maven
http://twitter.com/jvanzyl
http://twitter.com/takari_io
---------------------------------------------------------

A master in the art of living draws no sharp distinction between his work and his play; his labor and his leisure; his mind and his body; his education and his recreation. He hardly knows which is which. He simply pursues his vision of excellence through whatever he is doing, and leaves others to determine whether he is working or playing. To himself, he always appears to be doing both. 

  -- Fran�ois-Ren� de Chateaubriand

**Comment by mcculls** [comment]
To be absolutely clear:
* injection of SLF4J loggers using `@Inject` is not supported in the official Guice library
* injection of SLF4J loggers using `@Requirement` is supported by Sisu's Plexus shim
* injection of j.u.l loggers using `@Inject` is supported in the official Guice library

Adding support for injection of SLF4J loggers is possible outside of Guice, but it requires you to use a custom annotation rather than `@Inject`: https://github.com/google/guice/wiki/CustomInjections

**Comment by jvanzyl** [comment]
Thanks for the clarification. I'm not too concerned about not being able to @Inject SLFJ loggers any longer but we can't break components that might be doing it.

**Pull request closed without merging**
