### PR TITLE
[MNG-7129] Incremental build and shared cache feature

### PR DESCRIPTION
**Pull request by hboutemy**
after initial merge of Deutsche Bank donation to MNG-7129 branch #526, let's rework the code to better match Maven codebase

For example switching from jaxb2 to Modello

### CODE REVIEW

**Comment by michael-o** [comment]
Why into 3.8.x? Shouldn't this be Maven 4 for now?

**Comment by hboutemy** [comment]
without PR, no review: I had to create a PR to create life :)

**Comment by maximilian-novikov-db** [comment]
> > This diff looks huge to me
> 
> yes surely there is some rework to make this diff easier to evaluate and choose to merge into a main branch for a "normal" Maven release I tried to move the whole "caching" package into a separate module a try to have a more visible separation of concerns, but 3 classes had dependencies on maven-core: MojoExecutionManager, ProjectUtils, CacheController. Then it's not so easy...
> 
> I chose to start by working on Modello migration #598, that will ease some parts: help welcome any other idea on finding a concrete step to go forward are welcome

@hboutemy @michael-o we've prepared a change to the core which will allow to move the caching module to an extension, it's in testing now. We're going to raise a pr in a week.

**Comment by gnodet** [comment]
Superseded by #607

**Pull request closed without merging**
