### PR TITLE
[MNG-7055] Fix G level metadata handling in 3.9.x

### PR DESCRIPTION
**Pull request by cstamas**
Maven Artifact Transfer silently prevents group level metadata to reach Resolver and causes metadata loss on install/deploy.
Fix is to "bridge" this from maven-resolver-provider (and core) by reusing the actual metadata that
m-plugin-p:addPluginArtifactMetadata mojo adds, but m-a-t filters out.

This is backport of commit d141957ff5a3c08ae53c68e4ba19b49055f717c4 from master to maven-3.9.x branch.

### CODE REVIEW

**Comment by cstamas** [comment]
Was too eager, maybe lifecycle mappings should not be changed?

**Comment by cstamas** [comment]
Why is CI building Java7?

**Comment by michael-o** [comment]
Because I have forked 3.8.x which still had Java 7.

**Comment by cstamas** [comment]
CI is still crap, one IT failed (unrelated), and even that failed as it could run `clean` goal??? (are jobs isolated or what is happening)

**Comment by cstamas** [comment]
Verified locally the PR, all ok. @michael-o or @gnodet please review

**Review by michael-o — APPROVED** [review]
If there is an accompanying IT, please make sure that the required Maven version is altered also.

**Comment by jira-importer** [comment]
Resolve #7983

**Pull request merged**
