### PR TITLE
Patch for MNG-5956

### PR DESCRIPTION
**Pull request by nhojpatrick**
Issue raised https://issues.apache.org/jira/browse/MNG-5956

If you use modules, and that results in the same project/pom being included multiple times then an exception is thrown. But as it's the exact same project/pom it can simple be ignore in my view.

Simple project structure;
./pom.xml
./common/pom.xml
./sub1/pom.xml
./sub2/pom.xml

If sub1 has nested modules but for some reason common should 50% of the time be rebuilded if sub1 i rebuilt then adding ../common aids developers.

if sub2 has a similar setup to sub2, then when you build at the root directory an error is produces as both sub1 and sub2 reference common.

This pull request should ignore where the project is an exact match of the same physical pom.

### CODE REVIEW

**Comment by michael-o** [comment]
@jvanzyl Should be allow this or rather fail and force people to fix their setup?

**Comment by nhojpatrick** [comment]
I've worked on 5+ projects where they ranged from 75-150 maven projects. Allow this configuration would have simplified and reduce build times. The usual work around I've seen is developers creating scripts to manually navigate to dependencies within the same multi module project structure. When you have 10-40 developers working on a project I would prefer maven to handle this so everyone uses mvn clean install, instead of scripts being email or shared around or random scripts littering the repo.

I've created a very basic project which demonstrates what I would like to allow happen and current fails. https://github.com/nhojpatrick/apache.maven.maven-core.MNG-5956

**Comment by khmarbaise** [comment]
First i see your setup as wrong..cause you use modules multiple times within the reactor (Apart from using `<relativePath>..</relativePath>` which is simply not needed`). What i don't understand is why would this setup reduce build time? Can you elaborate a little bit more how that influences the build time? And what do you mean by searching the dependencies within a multi module build ?

**Comment by michael-o** [comment]
I second @khmarbaise answer, I do neither understand the problem you have. Looking at the demo project you have provided, I looks completely screwed up. Modules are supposed to be once int he reactor. It rather looks like a mess.

**Comment by nhojpatrick** [comment]
Totally forgot about this defect, as I was waiting for it to be merged in.

A git repo might might contain two deploy-able artifacts and currently the whole build might take 30 mins if a fresh clone.

**Comment by nhojpatrick** [comment]
I totally forgot about this defect.
@khmarbaise yep I would like to use modules multiple times, if your building everything then yes they are included multiple times. The build time improvements come when having to rebuild a portition of the multi module project.
@michael-o It might looks like a mess but allowing this would help reduce the workarounds I've seen.

**Comment by michael-o** [comment]
@nhojpatrick  I do understand your concerns but we strive for convention over configuration and not encouraging crappy setups. I am not really fond of this. 

@jvanzyl What do you think?

**Comment by jira-importer** [comment]
Resolve #7734

**Pull request closed without merging**
