### PR TITLE
[MNG-7548] Kill off "legacy" repository metadata support

### PR DESCRIPTION
**Pull request by gnodet**
JIRA issue: https://issues.apache.org/jira/projects/MNG/issues/MNG-7548

### CODE REVIEW

**Review by cstamas — APPROVED** [review]
LGTM, but as issue mentions, we have other places to look into as well

**Comment by gnodet** [comment]
> LGTM, but as issue mentions, we have other places to look into as well

@cstamas What are you referring it ? I read the issue again but I don't see...

**Comment by cstamas** [comment]
Ah, I meant "we have many other places **in ecosystem**" like that invoker plugin etc. So we need to search'n'destroy all those places.

**Comment by jira-importer** [comment]
Resolve #8902

**Pull request merged**
