### PR TITLE
[MNG-8334] Fix output redirection

### PR DESCRIPTION
**Pull request by gnodet**
JIRA issue: [MNG-8334](https://issues.apache.org/jira/browse/MNG-8334)

- **Fix empty output when using -l or redirecting output**
- **Fix incomplete log in file**

Alternative PR to #1824 @cstamas, and it should fix both type of redirections (`-l` and shell stdout `>` redirection)

This PR is more in line with what I had in mind.
In particular, this would allow stuff like the multiplexed output from mvnd
where we display information to the terminal, but not the actual log output.

### CODE REVIEW

**Comment by cstamas** [comment]
Looks good, the only strange thing is that `mvn -v -l log.txt` does not redirect (emit version to console). Also command `mvn -v > log.txt` sends ansi escapes to log file.

**Review by cstamas — APPROVED** [review]
Almost all issues fixed, is good. Am also for enhancing logging (like multiplexing).

One issue (or non issue): `mvn -v` is NOT (yet) colored, as I see it exits so fast that Jansi (or jline) is not yet inited.

**Review by cstamas — APPROVED** [review]
Last bits fixed, good to go!

**Comment by jira-importer** [comment]
Resolve #9519

**Pull request merged**
