### PR TITLE
[MNG-7045] - Drop useless and outdated cdi-api from maven

### PR DESCRIPTION
**Pull request by rmannibucau**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by bmarwell — APPROVED** [review]

**Comment by michael-o** [comment]
This is on schedule for next week. I asked a colleague to turn your POM into an IT.

**Comment by rmannibucau** [comment]
@michael-o late ping ;)

**Comment by michael-o** [comment]
@rmannibucau Pong. Colleague is working. He's a Maven Core IT virgin, so bear with him... ;-)

**Comment by michael-o** [comment]
PR for IT is there. I will schedule this hopefully for the weekend. @rmannibucau you are not forgotten!

**Comment by michael-o** [comment]
Going through now...

**Comment by michael-o** [comment]
I asked for an IT for good reason. I ran the suite multiple times from a fresh clone and see this failing:
```
java.lang.AssertionError:
Compile goal was expected to run once
Expected: is <1>
     but: was <2>
        at org.apache.maven.it.MavenITmng6566ExecuteAnnotationShouldNotReExecuteGoalsTest.assertCompiledOnce(MavenITmng6566ExecuteAnnotationShouldNotReExecuteGoalsTest.java:100)
        at org.apache.maven.it.MavenITmng6566ExecuteAnnotationShouldNotReExecuteGoalsTest.testRunsCompileGoalOnceWithPhaseExecution(MavenITmng6566ExecuteAnnotationShouldNotReExecuteGoalsTest.java:84)
```

Output:
```
mosipov@bsd1srv:/usr/home/mosipov/var/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer (MNG-7045=)
$ less log-phase-execution.txt
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.apache.maven.its.mng6566:consumer >----------------
[INFO] Building consumer 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Version not locked for default bindings plugins [maven-resources-plugin], you should define versions in pluginManagement section of your pom.xml or parent
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ consumer ---
[WARNING] File encoding has not been set, using platform encoding UTF-8. Build is platform dependent!
[WARNING] See https://maven.apache.org/general.html#encoding-warning
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Using 'null' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/src/main/resources
[INFO] skip non existing resourceDirectory /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/src/main/resources-filtered
[INFO]
[INFO] --- maven-compiler-plugin:0.1-stub-SNAPSHOT:compile (default-compile) @ consumer ---
[INFO] [MAVEN-CORE-IT-LOG] Using output file path: target/compiler-compile.txt
[INFO] [MAVEN-CORE-IT-LOG] Creating output file: /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/target/compiler-compile.txt
[INFO] [MAVEN-CORE-IT-LOG] Created output file: /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/target/compiler-compile.txt
[INFO]
[INFO] >>> plugin:1.0-SNAPSHOT:require-compile-phase (default) > compile @ consumer >>>
[INFO]
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ consumer ---
[WARNING] File encoding has not been set, using platform encoding UTF-8. Build is platform dependent!
[WARNING] See https://maven.apache.org/general.html#encoding-warning
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Using 'null' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/src/main/resources
[INFO] skip non existing resourceDirectory /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/src/main/resources-filtered
[INFO]
[INFO] --- maven-compiler-plugin:0.1-stub-SNAPSHOT:compile (default-compile) @ consumer ---
[INFO] [MAVEN-CORE-IT-LOG] Using output file path: target/compiler-compile.txt
[INFO] [MAVEN-CORE-IT-LOG] Creating output file: /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/target/compiler-compile.txt
[INFO] [MAVEN-CORE-IT-LOG] Created output file: /var/mosipov/Projekte/mit/core-it-suite/target/test-classes/mng-6566-execute-annotation-should-not-re-execute-goals/consumer/target/compiler-compile.txt
[INFO]
[INFO] <<< plugin:1.0-SNAPSHOT:require-compile-phase (default) < compile @ consumer <<<
[INFO]
[INFO]
[INFO] --- plugin:1.0-SNAPSHOT:require-compile-phase (default) @ consumer ---
[INFO] MNG-6566 plugin require-compile-phase goal executed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.148 s
[INFO] Finished at: 2020-12-20T20:04:27+01:00
[INFO] ------------------------------------------------------------------------
```

I haven't look into, I would expect @rmannibucau to do that.

**Comment by rmannibucau** [comment]
@michael-o don't you see the same without the fix?

**Comment by michael-o** [comment]
> 
> 
> @michael-o don't you see the same without the fix?

Correct, from Maven master there is no failure. The test passes.

**Comment by michael-o** [comment]
I also need to admit that during my last couple of months of work many ITs started to fall out because they are crappy/unstable. Go through the commits from me. This might be the case here too.

**Comment by rmannibucau** [comment]
@michael-o have to admit i dont see the link there :s, anything could help to reproduce?

**Comment by michael-o** [comment]
> 
> 
> @michael-o have to admit i dont see the link there :s, anything could help to reproduce?

Neither I do, but you just need to run ITs.

**Comment by rmannibucau** [comment]
I also have some stability issues with testing suite - but even without these PR - but from a first review it looks really unrelated so I would move forward with this PR and maybe open a track about IT to mayve use docker/testcontainers - to have the expected setup which is not trivial and was causing some issues with my local build for ex.

**Comment by michael-o** [comment]
Which issues do you experience? Please share.
Did you run the tests without the PR on Maven?

**Comment by michael-o** [comment]
@rmannibucau Guess what, I just had the same failure on a completely different branch. I am going to merge this.

**Comment by rmannibucau** [comment]
@michael-o I got a lot of issues with the env (some missing maven version for ex) then with the git setup I guess (EOL). For ex, using maven 3.6.3 I get:


    mng6772 NestedImportScopeRepositoryOverride.itInDependency(). FAILURE (1.5 s)
    mng6772 NestedImportScopeRepositoryOverride.itInProject().... FAILURE (1.4 s)
    mng6759     TransitiveDependencyRepositories.TransitiveDependenciesAccountForRepositoriesListedByDependencyTrailPredecessor() FAILURE (1.7 s)
    mng6720 FailFast.ItShouldWaitForConcurrentModulesToFinish().. OK (4.7 s)

I suspect mng6772 can be a wrong maven version rule but mvn6759 should have passed with 3.6.3.

**Comment by michael-o** [comment]
One need to explicitly check the log files, but in most cases a fresh clone will solve the issue. I did a lot recently to checksum verification.

**Comment by jira-importer** [comment]
Resolve #7993

**Pull request closed without merging**
