### PR TITLE
[MNG-6873] algin junit version to 4.13

### PR DESCRIPTION
**Pull request by calvinhkf**
align library versions...

### CODE REVIEW

**Comment by calvinhkf** [comment]
@slachiewicz  I was trying to keep junit version consistent as the issue reports.  Updated two junit dependencies to 4.13.

**Comment by slachiewicz** [comment]
maybe more places to fix, like here (searched for <artifactId>junit</
maven-embedder\src\examples\simple-project\pom.xml
maven-core\src\test\resources\org\apache\maven\lifecycle\pom.xml

**Comment by calvinhkf** [comment]
@slachiewicz hi, I have  re-run the dependency analysis and have included another 5 files that are missed previously and junit versions are all upgrated to 4.13...

**Comment by slachiewicz** [comment]
Change for Junit merged to master - thx!

**Pull request closed without merging**
