### PR TITLE
[MNG-7679] Fix NPE when executing a single mojo without a POM

### PR DESCRIPTION
**Pull request by cstamas**
As in that case NPE happened.

---

https://issues.apache.org/jira/browse/MNG-7679

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by michael-o** [comment]
Merged!

**Comment by ssingchd** [comment]
When will this fix be available in maven 3.9.0?

**Comment by michael-o** [comment]
> When will this fix be available in maven 3.9.0?

Tomorrow, if you are willing to sponsor it.

**Comment by mk-khan** [comment]
Hi @slawekjaranowski , its been quite sometime no new releases published, any idea if this fix is being deployed anytime soon to 3.9.X version?

**Comment by michael-o** [comment]
> Hi @slawekjaranowski, @michael-o , its been quite sometime no new releases published, any idea if this fix is being deployed anytime soon to 3.9.X version?

Tomorrow, if you are willing to sponsor it.

**Pull request closed without merging**
