### PR TITLE
[MNG-6778] - Use https for maven schemaLocations

### PR DESCRIPTION
**Pull request by cwansart**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

----

This pull request changes the maven xsd urls from http to https according to https://issues.apache.org/jira/browse/MNG-6778. It *does not* change the urls for other xsds `core-extension`, `settings`, `profiles`, `paramdoc`, `lifecycle`, `profiles`, `metadata` and `toolchains`.

### CODE REVIEW

**Comment by cwansart** [comment]
Still need to run core-its.

**Comment by michael-o** [comment]
Please note that parts of this work will be destroyed likely next time when the release plugin is run.

**Comment by cwansart** [comment]
@michael-o why? I changed the schemaLocations in the `maven.mdo` so I thought then running the build it will simply re-create everything with the changed url?

**Comment by michael-o** [comment]
I do remember that the Release Plugin rewrites the start tag. Previously, it injected still the old schema location. I may be wrong, but this needs to be checked.

**Comment by rfscholte** [comment]
Just verified this: both master and 2.5.3 of maven-release-plugin doesn't change the schemaLocation if it is there.

**Comment by michael-o** [comment]
Great, very good to know.

**Comment by jira-importer** [comment]
Resolve #8219

**Pull request merged**
