### PR TITLE
[MNG-5457] Added the repository id to show which repository is being …

### PR DESCRIPTION
**Pull request by rajivpjs**
I have added the repository id within both the AbstractMavenTransferListener.java & Slf4jMavenTransferListener.java.

Hopefully, this should fix this issue.

Please review and let me know of any changes.

Thanks.

### CODE REVIEW

**Comment by michael-o** [comment]
Unusable. `getLocalRepository()` always gives you *your* local repository on disk. This is not the remote repository Aether is pulling from or pushing to. Hence, you will always see `...local...:`.

**Comment by rajivpjs** [comment]
I am working on another fix.

Thanks.

**Comment by michael-o** [comment]
This looks better. Can you squash the commit? Additionally, this requires an integration test with three repos: central (by default), and two others. Preferably file-based. We'd see that this works.

**Comment by rajivpjs** [comment]
What do you mean by squash the commit? Do you have any examples of Integration tests for Apache way of doing things?

Thanks.

**Comment by michael-o** [comment]
[Squashing commits](http://stackoverflow.com/a/5189600/696632). We have a complete test set of IT [here](https://maven.apache.org/core-its/).  There is a [bus load](https://github.com/apache/maven-integration-testing/tree/31780e49d00ad5be0dd80ee5b37483f624bbf394/core-it-suite/src/test/resources) of them. Find one with an internal repo for resting. You IT would show that your approach actually works.

**Comment by michael-o** [comment]
Just, it does not work. The list you are using is a static list of ordered repos to be tried. The first one does not denote the one to be used. From Maven build:

    [INFO] ------------------------------------------------------------------------
    [INFO] Building Apache Maven Distribution 3.4.0-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5.1/maven-compiler-plugin-3.5.1.pom
    Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5.1/maven-compiler-plugin-3.5.1.pom (10 kB at 19 kB/s)
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5.1/maven-compiler-plugin-3.5.1.jar
    Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5.1/maven-compiler-plugin-3.5.1.jar (50 kB at 292 kB/s)
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.19.1/maven-surefire-plugin-2.19.1.pom
    Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.19.1/maven-surefire-plugin-2.19.1.pom (5.6 kB at 48 kB/s)
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.19.1/surefire-2.19.1.pom
    Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire/2.19.1/surefire-2.19.1.pom (18 kB at 121 kB/s)
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.19.1/maven-surefire-plugin-2.19.1.jar
    Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/2.19.1/maven-surefire-plugin-2.19.1.jar (38 kB at 191 kB/s)
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.6/maven-assembly-plugin-2.6.pom
    Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.6/maven-assembly-plugin-2.6.pom (16 kB at 112 kB/s)
    Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.6/maven-assembly-plugin-2.6.jar
    Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/2.6/maven-assembly-plugin-2.6.jar (246 kB at 524 kB/s)
    Downloading from central: https://repository.apache.org/snapshots/org/apache/maven/maven-embedder/3.4.0-SNAPSHOT/maven-embedder-3.4.0-20160712.211951-154.pom
    Downloaded from central: https://repository.apache.org/snapshots/org/apache/maven/maven-embedder/3.4.0-SNAPSHOT/maven-embedder-3.4.0-20160712.211951-154.pom (6.4 kB at 6.7 kB/s)
    Progress (1): 815 B
    
Note the snapshots at the end.

**Comment by rajivpjs** [comment]
In your example, where is the snapshots at the end? Are we saying repository at index 0, is not correct? If yes, what is the best way to determine which repository is correct?

**Comment by michael-o** [comment]
This is the snapshot: `Downloading from central: https://repository.apache.org/snapshots/org/apache/maven/maven-embedder/3.4.0-SNAPSHOT/maven-embedder-3.4.0-20160712.211951-154.pom`

Unfortunately, the mediated repo is only known to Aether. I have to fix this issue long time ago but was stuck at the same point. I think it won't work without an Aether fix.

**Comment by rajivpjs** [comment]
"Since Aether is currently in transition to us" - what do you mean? Is Aether going to come to Apache When do you think we will be able to fix this?

**Comment by michael-o** [comment]
> "Since Aether is currently in transition to us" - what do you mean? Is Aether going to come to Apache When do you think we will be able to fix this?

I think so, we will at least be able to add `getRemoteRepositoryId()`.

> In the meantime, should I leave this pull request open?

You can do that and rework the PR as soon as Aether has reached the appropriate state.

**Comment by rajivpjs** [comment]
Sure. I will close this for now and will reopen when we know Aether has reached the appropriate state.

Thanks.

**Comment by michael-o** [comment]
@rajivpjs I think I know the spot to fix in Aether, though I am not familiar with the Aether code. Give me 15 min.

**Comment by rajivpjs** [comment]
ok cool. I will wait for your reply.

Thanks.

**Comment by michael-o** [comment]
I just have patched Aether, let's see wether Maven will accept 1.1.0-SNAPSHOT.

**Comment by michael-o** [comment]
You can always watch dev@maven.apache.org.

**Comment by michael-o** [comment]
My patch works:

    Downloaded from central: https://repo.maven.apache.org/maven2/org/sonatype/forge/forge-parent/5/forge-parent-5.pom (8.4 kB at 55 kB/s)
    Downloading from apache.snapshots: https://repository.apache.org/snapshots/org/apache/maven/maven-core/3.4.0-SNAPSHOT/maven-metadata.xml
    Downloaded from apache.snapshots: https://repository.apache.org/snapshots/org/apache/maven/maven-core/3.4.0-SNAPSHOT/maven-metadata.xml (782 B at 199 B/s)
    Downloading from apache.snapshots: https://repository.apache.org/snapshots/org/apache/maven/maven-core/3.4.0-SNAPSHOT/maven-core-3.4.0-20160712.211941-155.pom
    Downloaded from apache.snapshots: https://repository.apache.org/snapshots/org/apache/maven/maven-core/3.4.0-SNAPSHOT/maven-core-3.4.0-20160712.211941-155.pom (8.8 kB at 2.1 kB/s)
    
I will push my changes shortly.

**Comment by michael-o** [comment]
Here is the Aether change: https://github.com/michael-o/aether-core/commit/942fc4122d803225c2b465831ef1378bb9946669

**Comment by rajivpjs** [comment]
That's great. Well done!

I can see only the Aether changes were made. Did you make any Apache Maven changes? The text "from" in "Downloading from central", how was that appended?

**Comment by michael-o** [comment]
The branch is already in preparation.

**Comment by rajivpjs** [comment]
Which branch should I be looking at and in which project?

**Comment by michael-o** [comment]
Here is the Maven change: https://github.com/michael-o/maven/commit/fd1f665225cea9cdee84cad3de193f771d82e42d

**Comment by rfscholte** [comment]
@rajivpjs can you close this pullrequest? This open PR causes warnings for https://issues.apache.org/jira/browse/MNG-5457 on the release page.

**Comment by jira-importer** [comment]
Resolve #6878

**Pull request closed without merging**
