### PR TITLE
[MNG-7029] Remove super POM release profile

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by michael-o** [comment]
@rfscholte The profile detection (MNG-7051) will be merged soon, but still there is no way to fail explicitly here because the profile is activated with a property:
```
osipovmi@deblndw011x:~/var/Projekte/maven-release (master=)
$ grep -r performRelease .
./maven-release-api/src/main/java/org/apache/maven/shared/release/config/ReleaseDescriptor.java:     * If set to true, this will set the property "performRelease" to true.
./maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhase.java:                additionalArguments = additionalArguments + " -DperformRelease=true";
./maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhase.java:                additionalArguments = "-DperformRelease=true";
./maven-release-manager/src/main/mdo/release-descriptor.mdo:            If set to true, this will set the property "performRelease" to true.
./maven-release-manager/src/test/java/org/apache/maven/shared/release/exec/ForkedMavenExecutorTest.java:        String arguments = "-DperformRelease=true -Dmaven.test.skip=true";
./maven-release-manager/src/test/java/org/apache/maven/shared/release/exec/ForkedMavenExecutorTest.java:        verify( argMock ).setLine( "-DperformRelease=true -Dmaven.test.skip=true" );
./maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhaseTest.java:                                                                                                   eq( "-DperformRelease=true -f pom.xml" ),
./maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhaseTest.java:                                     eq( "-DperformRelease=true -f pom.xml" ),
./maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhaseTest.java:                                     eq( "-DperformRelease=true -f pom1.xml" ),
./maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhaseTest.java:                                     eq( "-DperformRelease=true -f pom.xml" ),
./maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhaseTest.java:                                     eq( "-Dmaven.test.skip=true -DperformRelease=true -f pom.xml" ),
./maven-release-manager/src/test/java/org/apache/maven/shared/release/phase/RunPerformGoalsPhaseTest.java:                                     eq( "-DperformRelease=true -f pom.xml" ),
./maven-release-plugin/src/it/projects/perform/MRELEASE-459/verify.groovy:def addArgsExpr = /\Q[DEBUG] Additional arguments: \E(?:-Dhttps.protocols=TLSv1.2 )?-P(.+)\Q-DperformRelease=true -f pom.xml\E/
./maven-release-plugin/src/it/projects/perform/MRELEASE-459/verify.groovy:// M2:  [DEBUG] Additional arguments: -P custom-release -DperformRelease=true -f pom.xml
./maven-release-plugin/src/it/projects/perform/MRELEASE-459/verify.groovy:// M3:  [DEBUG] Additional arguments: -P it-repo,it-repo,custom-release -DperformRelease=true -f pom.xml
./maven-release-plugin/src/main/java/org/apache/maven/plugins/release/PerformReleaseMojo.java:     * If set to true, the release plugin sets the property "performRelease" to true, which activates the profile
```

Still any objections to merge this?

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by rfscholte** [comment]
https://github.com/apache/maven-release/blob/master/maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/AbstractRunGoalsPhase.java#L109-L113 shows profile activation by id, so please do this in the right order and merge after MNG-7051.

**Comment by michael-o** [comment]
> 
> 
> https://github.com/apache/maven-release/blob/master/maven-release-manager/src/main/java/org/apache/maven/shared/release/phase/AbstractRunGoalsPhase.java#L109-L113 shows profile activation by id, so please do this in the right order and merge after [MNG-7051](https://issues.apache.org/jira/browse/MNG-7051).

Indeed, I will obey the order, of course. I am confused why `RunPerformGoalsPhase` uses the actvation property instead of the profile...

**Comment by rfscholte** [comment]
Most likely quite old code still hanging around, never removed to preserve backwards compatibility.

**Comment by michael-o** [comment]
The question is should that be completely removed from MRELEASE or moved to the profile altogether to fail explicitly?

**Comment by michael-o** [comment]
I prefer hard failure with deprecation of that config option.

**Comment by rfscholte** [comment]
https://maven.apache.org/maven-release/maven-release-plugin/perform-mojo.html#useReleaseProfile is already marked as deprecated

**Comment by michael-o** [comment]
The we are good to remove it for next major.

**Comment by jira-importer** [comment]
Resolve #8008

**Pull request closed without merging**
