### PR TITLE
Mac OS X - way of getting JAVA_HOME location 

### PR DESCRIPTION
**Pull request by ananich**
Based on [man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/java_home.1.html)

### CODE REVIEW

**Comment by mfriedenhagen** [comment]
@ananich: #35 should take care oft this and even tackles the other start scripts. Since I think Mavericks Mountain Lion, a JDK is not installed by default, so the first branches should not be a problem as anyone with a default /System Java has set or installed this on purpose.

**Comment by KostyaSha** [comment]
:+1:

**Comment by barthel** [comment]
@jvanzyl Please think about merging.

:+1: 
The man page of ``java_home`` is dated from 04 August 2010. This should be old enough to integrate it in Maven, I thought.

With the actual 'El Captain' (Mac OS 10.11.1) all the ``JAVA_HOME`` locations are outdated. Only ``/Library/Java/JavaVirtualMachines/`` is valid, but without the ``CurrentJDK`` link.

``/usr/libexec/java_home`` provides the correct path.

**Comment by michael-o** [comment]
Please close this PR. the shell script has been drastically reduced and your change isn't mergeable anymore.

**Pull request closed without merging**
