### PR TITLE
[MNG-6471] during parallel build, ensure to set the thread name to the artifactId

### PR DESCRIPTION
**Pull request by rmannibucau**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by michael-o** [comment]
Nice idea, now do the threads look like now?

**Comment by michael-o** [comment]
Your change does not correspond to the issue title. You do not set the module name, but the artifact id.

**Comment by rmannibucau** [comment]
Yes, name is too variable to be reliable but artifactId works great, here is some output:


    [my-project] [INFO] --- jacoco-maven-plugin:0.8.0:prepare-agent (prepare-agent-it) @ my-project ---
    [my-project] [INFO] invoker.mavenOpts set to -javaagent:/home/rmannibucau/.m2/repository/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/home/rmannibucau/1_dev/my-project/target/jacoco.exec
    [my-project] [INFO] 
    [my-project] [INFO] --- jacoco-maven-plugin:0.8.0:report (post-integration-test) @ my-project ---
    [my-project] [INFO] Skipping JaCoCo execution due to missing execution data file.
    [my-project] [INFO]

**Comment by michael-o** [comment]
I think we can do better because if we abstract from MAven the pure artifact id as thread name is too simple. Maybe we could say "Building <artifactId>"?

**Comment by rmannibucau** [comment]
Not sure. "Building" wouldnt bring any info if hardcoded - as today you have BuildThread. We could set the goal but this is on the rest of the line and would make it verbose for no real gain IMHO. Shorter is the log line, better it is ;)

**Comment by michael-o** [comment]
GitHub swallowed some text. Please recheck.

**Comment by rmannibucau** [comment]
The point was that all the additional info you can use to enrich the line are on other lines if you filter by groupid:artifactid. Putting both on the thread name is too verbose and almost never useful in practise so i ended up with the artifact id only.

That said using a configurable pattern is fine too if you prefer.

**Comment by michael-o** [comment]
I wonder how you would recommend make it configurable?

**Comment by rmannibucau** [comment]
Out of my mind i was thinking to the same way LoggingSupport is done: string.format with all possible params (gav, etc) and then user relies on %x. Alternatively maven interpolation would work well.

**Comment by AlexanderAshitkin** [comment]
using log context sounds more natural for me. thread name should better not be mutated nor 2 threads should have the same name. 
So i propose to use http://logback.qos.ch/manual/mdc.html or equivalents for this.

**Comment by michael-o** [comment]
Here is a very simple counter proposal:
```

$ git diff                                                                                                                                                                                                          diff --git a/maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java b/maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java                    index 73839fc7c..cf4481172 100644                                                                                                                                                                                   --- a/maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java                                                                                                                      +++ b/maven-core/src/main/java/org/apache/maven/lifecycle/internal/LifecycleModuleBuilder.java                                                                                                                      @@ -100,6 +100,7 @@ public void buildProject( MavenSession session, MavenSession rootSession, Reacto                                                                                                                             }                                                                                                                                                                                                                                                                                                                                                                                                                                       BuilderCommon.attachToThread( currentProject );                                                                                                                                                        +            Thread.currentThread().setName( "builder-" + currentProject.getId() );                                                                                                                                                                                                                                                                                                                                                                  projectExecutionListener.beforeProjectExecution( new ProjectExecutionEvent( session, currentProject ) );
--
```

Idealy, this is solved in `BuilderCommon.attachToThread()`and a `BuilderCommon.detachfFomThread()` method.

**Comment by michael-o** [comment]
@rmannibucau I have picked up and rebased your commit, also added more context because the sole module name can occur multiple times in a large reactor. If no one objects I will merge this in a week or so.

**Comment by rmannibucau** [comment]
@michael-o I would strip "Builder-" or at least make it "mvn-" (builder is too common and we don't know if it is a plugin or maven itself so it just takes space IMHO). Otherwise +1 for your version.

**Comment by michael-o** [comment]
What about a hybrid: `mvn-builder-`?

**Comment by rmannibucau** [comment]
@michael-o +1

**Comment by michael-o** [comment]
@rmannibucau Please have a look at the update.

**Comment by famod** [comment]
Has there been any follow-up w.r.t. to logging a shorter name?
While having a precise name for the thread makes sense, `-Dorg.slf4j.simpleLogger.showThreadName=true` just consumes too much space and it's the only (easy) way to see more clearly which thread/module a line is coming from.

**Comment by michael-o** [comment]
> 

No. Do you have a better idea to solve this? It has been extremely helpful for me to solve issues with Resolver and synchronization. Thread (names) are resued, therefore impossible to process with `grep`.

**Comment by rmannibucau** [comment]
@famod it is just the artifactId normally so shouldn't be crazy long compared to default thread names, BuildThreadxxxx is not that shorter until you build OSGi artifacts setting the groupId in their artifact name but here we can't really help if we want this feature which is more helful than hurtful IMHO.

**Comment by famod** [comment]
I'm just testing 3.8.4 in my current project and I'm seeing this:
```
[mvn-builder-de.somecorp.foo.barbazx:register-server:jar:2.0.0.local-dev3]
```
(groupId obfuscated but same length)

Over 70 chars. Pretty long, no?

> Do you have a better idea to solve this?

Not yet. The MDC approach sounds good.
Btw, I was just asking if there was already a ticket or PR as a follow up. I was not demanding anything! 🙂

**Comment by rmannibucau** [comment]
@famod ok, got back memory - actually checked ;): https://github.com/apache/maven/commit/a242c1a9127a643b432cbcc926155c7a1589f2f6. Agree `mvn-builder-" + ${project.id}` is too long - actually why this original PR was just using the artifactId. Guess it can be either configurable by some maven option but also guess only the default is important so maybe `mvn-builder-" + ${project.artifactId}` would be more relevant to drop the useless data?

**Comment by michael-o** [comment]
ArtifactId alone might not be unique in a huge build or an aggregator project.

**Comment by rmannibucau** [comment]
@michael-o yep, do you prefer to bother 99.9% of users of 0.1% (surestimated since you must have such a project and rely on this feature and it must be on a full build and you must skip other logs to loose the context and not be able to sort it and you must not have a dependency between the 2 artifacts with the same name so it is never). I clearly vote to make it user friendly and be it for the never met case ;).

**Comment by michael-o** [comment]
I don't have such a project. I wonder whether we could use a package name collapser like Logback has.

@famod please raise an issue

**Comment by rmannibucau** [comment]
Would stay verbose or unreadable as in log4j/logback, saner to drop it IMHO until we maje it configurable.

**Comment by michael-o** [comment]
We have the MavenSession, so config isn't a huge problem. I am all ears for proposals, but dropping without anything better is not acceptable.

**Comment by rmannibucau** [comment]
@michael-o the feature is to give more hints on users to what is "current", habing type and gId is not helping as much as loosing the gId detail so it is better. Now a config is an option while default stick to artifactId IMHO. Here we dont look for accuracy but efficiency.

**Comment by famod** [comment]
I had a quick look and AFAICS the SLF4J SimpleLogger that Maven is using does not seem to support MDC (or NDC). Bummer!

So there's currently only the thread name.

https://issues.apache.org/jira/browse/MNG-7381

**Comment by michael-o** [comment]
It is simple after all

**Comment by jira-importer** [comment]
Resolve #7199

**Pull request closed without merging**
