### PR TITLE
Upgrade to junit 5

### PR DESCRIPTION
**Pull request by gnodet**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by rfscholte** [comment]
These numbers are interesting:

before patch
Tests | Errors | Failures | Skipped 
-- | -- | -- | -- 
1030 | 0 | 0 | 1

after patch

Tests | Errors | Failures | Skipped
-- | -- | -- | -- 
1038 | 0 | 0 | 10

can you explain this difference?

**Comment by gnodet** [comment]
> These numbers are interesting:
> 
> before patch
> 
> Tests	Errors	Failures	Skipped
> 1030	0	0	1
> after patch
> 
> Tests	Errors	Failures	Skipped
> 1038	0	0	10
> can you explain this difference?

@rfscholte This is caused by https://github.com/apache/maven/pull/431/commits/d8692416ffa2029581b6f771a75704f5a6ee2495
The tests were disabled by prepending the test method name with `disabled` which cause the methods to be excluded from the tests completely.  They are now included, but disabled.

**Comment by gnodet** [comment]
There are also a few tests that actually do not work:
https://github.com/gnodet/maven/commit/5bc542fce94ec873f503e9e127fbfd9d46d3a11d#diff-b8f35d04005261b9de1033f5d6470eb58437c6c738c13819526de6e1fb3454f5R208-R215
In the above example, the `new DefaultArtifactVersion( "..." )` does not actually throw an exception.  I assumed this was expected given the assertion in the catch, so I ended up disabling the test.  There are a few occurences of those.  Reviewing all `@Disabled` tests would be a good thing, but that's not the point of this PR.

**Comment by rfscholte** [comment]
Merged with https://github.com/apache/maven/commit/bb916d0784c7631866167928e4d0615df3317567

**Pull request closed without merging**
