### PR TITLE
[MNG-7672] Fork should only execute the project and its submodules

### PR DESCRIPTION
**Pull request by gnodet**
Following this checklist to help us incorporate your
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] SUMMARY`,
       where you replace `MNG-XXX` and `SUMMARY` with the appropriate JIRA issue.
 - [ ] Also format the first line of the commit message like `[MNG-XXX] SUMMARY`.
       Best practice is to use the JIRA issue title in both the pull request title and in the first line of the commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by pzygielo** [comment]
Just about vocabulary.
Commit comment and JIRA issue mention children.
Code is about aggregator and submodules.
As I understand it - being submodule does not mean anything about being child, and is not related with inheritance. Perhaps this could be re-worded to not mix the two.

-----
https://maven.apache.org/pom.html#a-final-note-on-inheritance-v-aggregation

**Review by cstamas — APPROVED** [review]

**Comment by cstamas** [comment]
Interesting fact; this PR fixes code added to Maven 3.0-RC1 (!!!) but the Javadoc for aggregator says literally this what this PR introduces (so the two was not aligned since 3.0-RC1): https://maven.apache.org/ref/3.8.7/maven-plugin-api/apidocs/org/apache/maven/plugin/descriptor/MojoDescriptor.html#isAggregator--

**Comment by gnodet** [comment]
> Interesting fact; this PR fixes code added to Maven 3.0-RC1 (!!!) but the Javadoc for aggregator says literally this what this PR introduces (so the two was not aligned since 3.0-RC1): https://maven.apache.org/ref/3.8.7/maven-plugin-api/apidocs/org/apache/maven/plugin/descriptor/MojoDescriptor.html#isAggregator--

Yes, I saw the javadoc for the `isAggregator` and it guided me in finding this fix !

**Comment by cstamas** [comment]
So, what is the status of this (am more interested in 3.9 backport), is this fix confirmed? When is merge expected?

**Comment by gnodet** [comment]
> So, what is the status of this (am more interested in 3.9 backport), is this fix confirmed? When is merge expected?

#969 and #970 
I think @michael-o wanted to review this PR, right ?

**Pull request merged**
