### PR TITLE
FIX: MAVEN_OPTS env variable with mvnDebug

### PR DESCRIPTION
**Pull request by pcollaog**
+ Add a temp env variable for save the MAVEN_OPTS before load .mavenrc.

Signed-off-by: Francisco Collao Garate <pcollaog@gmail.com>

### CODE REVIEW

**Comment by michael-o** [comment]
We should have a JIRA issue for this

**Comment by jvanzyl** [comment]
https://issues.apache.org/jira/browse/MNG-5813

**Comment by pcollaog** [comment]
Great.. thanks for create the jira issue ;)



On Tue, Apr 28, 2015 at 1:04 PM, Jason van Zyl <notifications@github.com>
wrote:

> https://issues.apache.org/jira/browse/MNG-5813
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/maven/pull/44#issuecomment-97120279>.
>



-- 
Francisco Collao Gárate
LinuxUser #363300
http://blog.pcollaog.cl

**Comment by pcollaog** [comment]
Any plans to fix this problem?

**Comment by pcollaog** [comment]
Close: https://issues.apache.org/jira/browse/MNG-5813

**Comment by jira-importer** [comment]
Resolve #6750

**Pull request closed without merging**
