### PR TITLE
[MNG-5222] Improvement in deprecated params detection

### PR DESCRIPTION
**Pull request by slawekjaranowski**
In previous solution we used `ConfigurationListener` where we had information about setting value on specific Mojo filed.

Value in listener (which can be any class instance) will be compared to custom prepared String from Mojo parameters default.

Plugin configurator (can be user implementation) has own logic how to create parameter value from strings provide in default arguments in plugin configuration.

So to achieve goal of issue - we want to check when user use deprecated Mojo parameter in configuration - we can check `XmlPlexusConfiguration` before plugin fields will be populated.

I introduce interface `MavenPluginConfigurationValidator` 
which has as input `XmlPlexusConfiguration` and `MojoDescriptor` for validating xml configuration used in plugin.

In this PR it is first implementation - `DeprecatedPluginValidator` 
which check deprecated parameter.

We can easy add next implementation eg. for checking if read-only parameters is used in configuration. 

---

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
build on Jenkins fails due to using master branch from integration-test

**Review by michael-o — COMMENTED** [review]
Can you briefly describe the logical change here? Refactor to a reusable component? What will happen you you will validate deprecated mojos, new interface or broaden this one?

**Comment by slawekjaranowski** [comment]
PR description updated.

**Comment by slawekjaranowski** [comment]
kindly ping

**Comment by michael-o** [comment]
Let me try to rephrase here:
* You are early validating (as compared to before) here *bofore* the actual mojo is polulated through DI?
* This interface can also be used to log if a mojo itself is deprecated?

**Comment by slawekjaranowski** [comment]
> Let me try to rephrase here:
> 
> * You are early validating (as compared to before) here _bofore_ the actual mojo is polulated through DI?

yes, based on used configuration in XmlPlexusConfiguration

> * This interface can also be used to log if a mojo itself is deprecated?

checking for mojo itself is deprecated can be done in the same implementation - it is similar task, simply I wan't mix issues

but next implementation can be used for checking if read-only params is used in configuration

**Review by michael-o — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #6710

**Pull request merged**
