### PR TITLE
[MNG-8372] Augment error message to give users more context when running into deprecated encryption warning

### PR DESCRIPTION
**Pull request by ottlinger**
@cstamas sorry I formatted the commit messages differently .... hopefully the ITS run through.

### CODE REVIEW

**Comment by ottlinger** [comment]
@cstamas how come that Maven does not define a defaultGoal in its pom? :) I did not want to add it in this MR, was just wondering.

**Comment by ottlinger** [comment]
The failing test has nothing to do with my change but is a problem within the GitHubAction Infra structure (network error to reach Maven repo).

**Comment by ottlinger** [comment]
@cstamas doe the ITS run with the GitHubActionBuild as well? I'm unable to start the tests locally. Both howtos seem to contradict each other and the deployment of the Maven artifact does not work as described :(

**Comment by ottlinger** [comment]
@cstamas the build is green - ready4review. Thanks.

**Review by cstamas — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #9481

**Pull request merged**
