### PR TITLE
MNG-7087 - Fix problem in the build

### PR DESCRIPTION
**Pull request by gnodet**
It fails with maven 4

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by michael-o** [comment]
Folks, please do not merge yet. This issue has releaved a nasty bug in producer/consumer. This can only be merged when we have solved the concurrency bug: https://issues.apache.org/jira/projects/MNG/issues/MNG-708

**Comment by gnodet** [comment]
@michael-o the builds seems to work for me with this PR and https://github.com/apache/maven/pull/443

**Comment by gnodet** [comment]
@michael-o The problems fixed by this PR are unrelated to the consumer/producer bug (the duplicate id is a pure validation problem because the rules have changed in 4.0 and the rat one is related to new dependencies I think).

**Comment by michael-o** [comment]
> 
> 
> @michael-o The problems fixed by this PR are unrelated to the consumer/producer bug (the duplicate id is a pure validation problem because the rules have changed in 4.0 and the rat one is related to new dependencies I think).
> But these are clearly under [MNG-7087](https://issues.apache.org/jira/browse/MNG-7087).

That's correct, but then I fixed the validation problem I was not able to reproduce the concurrency issue anymore. I tried Java 11 to 15.

**Comment by gnodet** [comment]
> > @michael-o The problems fixed by this PR are unrelated to the consumer/producer bug (the duplicate id is a pure validation problem because the rules have changed in 4.0 and the rat one is related to new dependencies I think).
> > But these are clearly under [MNG-7087](https://issues.apache.org/jira/browse/MNG-7087).
> 
> That's correct, but then I fixed the validation problem I was not able to reproduce the concurrency issue anymore. I tried Java 11 to 15.

That's weird.  I just rebuilt this very branch with maven 3 and then tried to use the create distribution to build maven.  It fails very early
```
➜  maven git:(fix-build) ~/tmp/apache-maven-4.0.0-alpha-1-SNAPSHOT/bin/mvn -v
Apache Maven 4.0.0-alpha-1-SNAPSHOT (fc9e66c1ed04165a420c8a78e4555e3b4f999361)
Maven home: /Users/gnodet/tmp/apache-maven-4.0.0-alpha-1-SNAPSHOT
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
➜  maven git:(fix-build) ~/tmp/apache-maven-4.0.0-alpha-1-SNAPSHOT/bin/mvn install -DskipTests   
[INFO] Scanning for projects...
ERROR:  ''
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] input contained no data
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project (/Users/gnodet/work/git/maven/maven-model-builder/pom.xml) has 1 error
[ERROR]     input contained no data
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the '-e' switch.
[ERROR] Re-run Maven using the '-X' switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

**Comment by michael-o** [comment]
This is exactly what I have on FreeBSD 12-STABLE. Same OpenJDK version. But I am rather shocked that your locale isn't `fr_FR`.

**Comment by gnodet** [comment]
> This is exactly what I have on FreeBSD 12-STABLE. Same OpenJDK version. But I am rather shocked that your locale isn't `fr_FR`.

The translations are not always understandable.  Googling for English errors is way easier than localized ones, so I've been using an English OS since years.  I also happen to use a qwerty keyboard which is way easier for coding.  :smirk:

**Comment by gnodet** [comment]
Superseded by https://github.com/apache/maven/commit/a515fbe04e8d41a28e926d0dc25998ea0f50c785

**Pull request closed without merging**
