### PR TITLE
MNG-6220 add color CLI option

### PR DESCRIPTION
**Pull request by mryan43**
https://issues.apache.org/jira/browse/MNG-6220

### CODE REVIEW

**Comment by michael-o** [comment]
I will comment shortly.

**Comment by michael-o** [comment]
They are several issues. People are used to [GNU](https://www.gnu.org/software/grep/manual/grep.html#General-Output-Control) and [BSD](https://www.freebsd.org/cgi/man.cgi?query=grep&sourceid=opensearch) tools like grep. They use values `never`, `always`, `auto`. Having said that I do think we need to do this exactly the same way: [`grep.c`](https://github.com/freebsd/freebsd/blob/master/usr.bin/grep/grep.c#L627-L647). Option `always` requires special attention due to `isatty` in combination with `less(1)`.

**Comment by michael-o** [comment]
Two issues:

1. Unfortunately, Commons CLI does not offer valid values. If it would, it would fail if the option value is wrong. I would do so too.
2. You blindly `return` from `always`, but still forget that Jansi will ignore that because `isatty` returns false as soon as `stdout` is passed via pipe.

**Comment by mryan43** [comment]
Good idea to align the name of choices with grep, I just changed it.

About "isatty", do you think we should set the jansi.force system property when --color is set to "always" ? https://github.com/fusesource/jansi/blob/2616142fda4425d779ac94a3d9bfa76412021b23/jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java

**Comment by michael-o** [comment]
I think yes, grep doesn't do different. Please try the patch thoroughly!

**Comment by mryan43** [comment]
I will test with less and jenkins and comment again with results.

**Comment by mryan43** [comment]
Unfortunately, the system property is read only once in a static init block in the JansiConsole class before the cli main method is invoked, so my change doesn't work.

We have a kind of chicken and egg situation and we need to decide if we prefer 

a) not setting up Jansi until arguments/config have been parsed and validated (and call MessageUtils.systemInstall(); later in the loggin() method)

b) forcing jansi until arguments and config have been parsed (by adding System.setProperty( "jansi.force", "true" ); before MessageUtils.systemInstall(); in MavenCli#main and then eventually disable it later in the loggin() method

What do you think ?

**Comment by mryan43** [comment]
I applied solution B.

I have added an auto-detection method in MessageUtils in my fork of maven-shared-utils (https://github.com/mryan43/maven-shared) based on the corresponding code in jansi.

Unfortunately, upgrading to 3.2.0-SNAPSHOT from maven breaks compilation because of changes done for MSHARED-587 but I'm affraid fixing them would be out of scope of this PR.

**Comment by mryan43** [comment]
I feel stuck until someone with more experience of the maven code base update the version of maven-shared-utils to 3.2.1-SNAPSHOT on the default branch, anyone up to the task ?

**Comment by michael-o** [comment]
I don't might to pick this up, but it won't happen before Sep for personal priorities.

**Comment by rfscholte** [comment]
Here's my proposal: https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commit;h=fd57754218e749305be1dd745fda9407960cf985

**Comment by agudian** [comment]
@rfscholte: looks good! 👍

**Comment by mryan43** [comment]
Great thanks @rfscholte !

**Pull request closed without merging**
