### PR TITLE
[MNG-7111] Fix maven parallel builds

### PR DESCRIPTION
**Pull request by gnodet**
Fix exception on master when using parallel builds.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by michael-o** [comment]
Is there a JIRA issue for that and exceptions you have observed?

**Comment by gnodet** [comment]
@michael-o this looks like a fix for https://issues.apache.org/jira/projects/MNG/issues/MNG-7087 at first glance

**Review by rmannibucau — APPROVED** [review]

**Comment by michael-o** [comment]
Thanks for the fix. We first need to know whether this class was intended to be used concurrently. @rfscholte Can you take a look?

**Comment by rfscholte** [comment]
I need to investigate this a bit more. My thought would be that during phase 1 the maps are filled, and this is single threaded. During phase 2 the builds are done in parallel, and maps are only used for retrieval. In such case I wouldn't expect the need for concurrent hashmaps. Or am I missing a detail?

**Comment by gnodet** [comment]
> I need to investigate this a bit more. My thought would be that during phase 1 the maps are filled, and this is single threaded. During phase 2 the builds are done in parallel, and maps are only used for retrieval. In such case I wouldn't expect the need for concurrent hashmaps. Or am I missing a detail?

Fwiw, the second thread was accessing the map from the following location:
https://github.com/apache/maven/blob/673a7d1fef55795ea47a147f158a1411475e7495/maven-model-builder/src/main/java/org/apache/maven/model/building/AbstractModelSourceTransformer.java#L153-L163

**Comment by gnodet** [comment]
@rfscholte I've added another commit which fix a deadlock.

**Comment by rfscholte** [comment]
This is the next I want to fix. I do understand the cause: before the commit both filemodel and raw model where part of phase 1, now raw model has moved to phase 2. This is also where the build/consumer builds up the context, so it can be re-used during distribution. So yes, these must become ConcurrentHashMaps.
@gnodet I would expect ConcurrentHashMaps to be enough, why the need for the extra layer of `Holder`?

**Comment by rfscholte** [comment]
This is the next I want to fix. I do understand the cause: before the commit both filemodel and raw model where part of phase 1, now raw model has moved to phase 2. This is also where the build/consumer builds up the context, so it can be re-used during distribution. So yes, these must become ConcurrentHashMaps.
@gnodet I would expect ConcurrentHashMaps to be enough, why the need for the extra layer of `Holder`?

**Comment by rfscholte** [comment]
This is the next I want to fix. I do understand the cause: before the commit both filemodel and raw model where part of phase 1, now raw model has moved to phase 2. This is also where the build/consumer builds up the context, so it can be re-used during distribution. So yes, these must become ConcurrentHashMaps.
@gnodet I would expect ConcurrentHashMaps to be enough, why the need for the extra layer of `Holder`?

**Comment by gnodet** [comment]
> This is the next I want to fix. I do understand the cause: before the commit both filemodel and raw model where part of phase 1, now raw model has moved to phase 2. This is also where the build/consumer builds up the context, so it can be re-used during distribution. So yes, these must become ConcurrentHashMaps.
> @gnodet I would expect ConcurrentHashMaps to be enough, why the need for the extra layer of `Holder`?

@rfscholte the reason is explain at https://issues.apache.org/jira/browse/MNG-7111, it can cause deadlocks... The holder makes the usage of the concurrent hash map safe.

**Comment by rfscholte** [comment]
Merged with https://github.com/apache/maven/commit/9e19b57c720d226b0b30992535819f700a665d14
Thanks for this PR!

**Pull request closed without merging**
