### PR TITLE
[MNG-6389] - Move toolchains model generation from maven-core to maven-toolchain module

### PR DESCRIPTION
**Pull request by gastaldi**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by gastaldi** [comment]
@rfscholte can you review and merge when possible?

**Comment by rfscholte** [comment]
I don't think  the MavenToolchainMerger belongs there. If you take a look at https://maven.apache.org/ref/3.5.3/ I would say we should also introduce a maven-toolchain-builder and move all matching packages to that artifact.

**Comment by gastaldi** [comment]
@rfscholte I created the maven-toolchain-builder module with the matching packages, see if that works for you

**Comment by rfscholte** [comment]
I have to look closely if all required actions are done. E.g. new modules also means updating `maven/src/site/xdoc/maven-deps.odg`. Not sure if this is the only doc that needs to be updated.

**Comment by gastaldi** [comment]
Ok let me know what those are or feel free to push directly to my branch as a new commit

**Comment by gastaldi** [comment]
>I don't think the MavenToolchainMerger belongs there

Are you sure about that? The `maven-model` project has a merger too: https://github.com/apache/maven/blob/master/maven-model/src/main/java/org/apache/maven/model/merge/ModelMerger.java

**Comment by rfscholte** [comment]
This is an important line in the javadoc:
> This is a hand-crafted prototype of the default model merger that should eventually be generated by Modello
So in the end the merger should be generated based on the `.mdo` file.  This means that `MavenToolchainMerger` indeed belongs to the maven-toolchain artifact.
In the end there should be no manual code in this artifact, only generated code, hence my original comment.

**Comment by rfscholte** [comment]
@gastaldi can you update your PR, we should be able to merge this soon.

**Comment by gastaldi** [comment]
Hi @rfscholte I'm afraid I won't have time to work on this anymore. I'm closing it for the time being. Thanks!

**Pull request closed without merging**
