### PR TITLE
[MNG-7380] Don't log non-threadsafe warning if only building a single module

### PR DESCRIPTION
**Pull request by famod**
I tested this with the core repo itself and the rat-plugin.
There seem to be no ITs for that warning whatsoever so I didn't bother (but of course I did run all of them).

Will gladly create a backport PR for 3.8.5 after this has been merged.

@michael-o, regarding you comment in the ticket:
> I wonder whether this applies to forked lifecycles also...

I don't think there will be anything special, but I might be wrong.

---

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by michael-o — APPROVED** [review]
Looks good to me actually, but still would like someone with forked skills have a look also. @hboutemy

**Comment by gnodet** [comment]
> Looks good to me actually, but still would like someone with forked skills have a look also. @hboutemy

Fwiw, I think with the recent locks addition in https://github.com/apache/maven/commit/10a72f30f7bdd19e803820a215383b975a5283ce, even forked lifecycles can not execute concurrently, so that should not be a problem imho.

**Review by gnodet — APPROVED** [review]

**Comment by michael-o** [comment]
I have a counter/additional proposal as well:
1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.
2. Don't invoke a MT build with single module reactor even if `-T` is requesed and log info message

WDYT?

**Comment by famod** [comment]
@michael-o 
>     1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.

Please don't because with that I would need to pass `-T1` (because we have `-T0.5C` in `.mvn/maven.config`).
This would be strict but not user friendly.

>     2. Don't invoke a MT build with single module reactor even if `-T` is requesed and log info message

Much better that 1. IMHO, but for a good chunk of usages (or even all?) this message would be just noise.
I like the optimization though to not kick off a MT build.

**Comment by rmannibucau** [comment]
With Guillaume's comment it looks like the warning can just be dropped at runtime and should be moved to plugin developer side only if not explicitly set so users will be happy whatever the plugin dev did, no?

**Comment by famod** [comment]
> With Guillaume's comment it looks like the warning can just be dropped at runtime and should be moved to plugin developer side only if not explicitly set so users will be happy whatever the plugin dev did, no?

AFAICS, you could still hit concurrency issues in a plugin is executed concurrently for _different_ modules in the reactor. The commit @gnodet referenced is about project/module scoped locking if I'm not mistaken.

**Comment by rmannibucau** [comment]
but same applies to mojo, we are able to ensure a not thread safe mojo is not executed concurrently which means the warning is never relevant to end users, only to plugin dev so it is not the place to log it anyway, no?

**Comment by famod** [comment]
Ok, you mean extending the locking logic? Might work.
I was referring to the current state of affairs.

Not sure if there should then still be a message for users. Some plugin maintainers will probably ignore such warnings and will only react if users start bugging them - but for that the users need to know that their build throughput is crippled.

**Comment by gnodet** [comment]
> I have a counter/additional proposal as well:
> 
> 1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.
> 2. Don't invoke a MT build with single module reactor even if `-T` is requesed and log info message
> 
> WDYT?

What about using `MavenSession#isParallel()` instead ?
It's set to `true` by the `MultithreadedBuilder` when the number of threads is 2 or more, which sounds exactly what is needed.

**Comment by michael-o** [comment]
> @michael-o
> 
> > ```
> > 1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.
> > ```
> 
> Please don't because with that I would need to pass `-T1` (because we have `-T0.5C` in `.mvn/maven.config`). This would be strict but not user friendly.

I see, but what is the purpose of having `T0.5C` for a single module build?


> > ```
> > 2. Don't invoke a MT build with single module reactor even if `-T` is requesed and log info message
> > ```
> 
> Much better than 1. IMHO, but for a good chunk of usages (or even all?) this message would be just noise. I like the optimization though to not kick off a MT build.

Maybe at debug level, there is already one message which denotes the builder type.

**Comment by rmannibucau** [comment]
@famod you are likely right but it still means we pollute thousands of people instead of one for something which is 1. generally not hurting and 2. can likely not be fixed anyway so it should move to the plugin build and if you still want the end user to know, to some build check (like dependabot or sonar) but not the actual build IMHO. That said, a debug level  would work for me (while it is not info ;)) as suggested.

**Comment by michael-o** [comment]
@famod I have checked option 2 and I see that in `MavenCli` the builder id is set based on the `-T` option being available. Since the reactor is not available at that point, at least here one cannot switch batch to the single threaded bulder.

**Comment by michael-o** [comment]
> > I have a counter/additional proposal as well:
> > 
> > 1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.
> > 2. Don't invoke a MT build with single module reactor even if `-T` is requesed and log info message
> > 
> > WDYT?
> 
> What about using `MavenSession#isParallel()` instead ? It's set to `true` by the `MultithreadedBuilder` when the number of threads is 2 or more, which sounds exactly what is needed.

At which point? It will just replace `degreeOfConcurrency >= 2? Won't it?

**Comment by michael-o** [comment]
> With Guillaume's comment it looks like the warning can just be dropped at runtime and should be moved to plugin developer side only if not explicitly set so users will be happy whatever the plugin dev did, no?

Why? How is the user know otherwise that his build might fail? Given the fast amount of plugins out there I think moving this is unrealistic.

**Comment by famod** [comment]
> > @michael-o
> > > ```
> > > 1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.
> > > ```
> > 
> > 
> > Please don't because with that I would need to pass `-T1` (because we have `-T0.5C` in `.mvn/maven.config`). This would be strict but not user friendly.
> 
> I see, but what is the purpose of having `T0.5C` for a single module build?

There is none, it's just a side-effect of `-T0.5C` in `.mvn/maven.config`.
Most of the time we build the entire project (or automatically incremental via [GIB](https://github.com/gitflow-incremental-builder/gitflow-incremental-builder)), so having parallel builds by default makes a lot of sense for us (more productive and DRY).
But we have also use cases for `-f` and `-pl` (`-N` not so much). So if option 1 would be implemented we would gain nothing from this PR as we would still need to add `-T1`.

**Comment by gnodet** [comment]
> > > I have a counter/additional proposal as well:
> > > 
> > > 1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.
> > > 2. Don't invoke a MT build with single module reactor even if `-T` is requesed and log info message
> > > 
> > > WDYT?
> > 
> > 
> > What about using `MavenSession#isParallel()` instead ? It's set to `true` by the `MultithreadedBuilder` when the number of threads is 2 or more, which sounds exactly what is needed.
> 
> At which point? It will just replace `degreeOfConcurrency >= 2? Won't it?

Yes, but it's cleaner.

**Comment by michael-o** [comment]
> > > > I have a counter/additional proposal as well:
> > > > 
> > > > 1. Log a warning when MT build is requested, but only one module is in the reactor. Hence, MT build is pointless.
> > > > 2. Don't invoke a MT build with single module reactor even if `-T` is requesed and log info message
> > > > 
> > > > WDYT?
> > > 
> > > 
> > > What about using `MavenSession#isParallel()` instead ? It's set to `true` by the `MultithreadedBuilder` when the number of threads is 2 or more, which sounds exactly what is needed.
> > 
> > 
> > At which point? It will just replace `degreeOfConcurrency >= 2? Won't it?
> 
> Yes, but it's cleaner.

Agree, and reads better.

**Comment by jira-importer** [comment]
Resolve #7941

**Pull request closed without merging**
