### PR TITLE
Upgrade SLF4J to 1.7.25

### PR DESCRIPTION
**Pull request by ebourg**
The changes to SLF4J required to support maven-slf4j-provider have been [released ](https://jira.qos.ch/browse/SLF4J-394) in the version 1.7.25. If I'm not mistaken it should be possible to remove the patching tweak now.

### CODE REVIEW

**Comment by ebourg** [comment]
Is the StaticLoggerBinder implementation necessary? I built Maven without and it seemed to work, the resulting version was able to build a couple of random projects and the console output was colored.

**Comment by hboutemy** [comment]
AFAIK, you have colors on messages, but not on levels: the specific logger is necessary for levels.
It's also necessary for colored error rendering.
Just look at MavenSimpleLogger and you'll see exactly these 2 features in this class

**Comment by ebourg** [comment]
Understood, thank you. I've added a StaticLoggerBinder implementation but now SLF4J complains that there are two StaticLoggerBinder on the classpath (from maven-slf4j-provider and slf4j-simple). I'll try to shade slf4j-simple and remove its StaticLoggerBinder class.

**Comment by ebourg** [comment]
It's better now, the levels and the exceptions are properly colored, and SLF4J no longer complains about the duplicate StaticLoggerBinder.

**Comment by hboutemy** [comment]
great, I'll merge your ideas with https://github.com/apache/maven/commit/75b23eb01f913cf90d6ac4f9d2d5d7f6b9d69e1a : removing the patching part will be a be a good benefit

issue tracked in https://issues.apache.org/jira/browse/MNG-6196

**Comment by hboutemy** [comment]
ideas added to the MNG-6196 branch in https://github.com/apache/maven/commit/c2a8787eb7450cb28d7f08698788c5e58a3f8a02 : no monkey patch any more
I kept dependency:unpack+build-helper:add-source instead of switching to shade because I prefer the resulting source jar

**Comment by ebourg** [comment]
Thank you. The add-source trick is a bit problematic for the Debian packaging because we don't build the source jars, but we can live with a Debian specific patch using the shade plugin instead.

**Comment by slachiewicz** [comment]
This one can be closed.

**Comment by jira-importer** [comment]
Resolve #7250

**Pull request closed without merging**
