### PR TITLE
[MNG-6028] Include current goals in resume suggestion

### PR DESCRIPTION
**Pull request by splatch**
This PR is small improvement which allows to simply pick up returned sugestion and restart the build.

JIRA issue: https://issues.apache.org/jira/browse/MNG-6028.

### CODE REVIEW

**Comment by hboutemy** [comment]
question: if the initial command contained something like "-Dparam=value", does the generated command contain it?

**Comment by splatch** [comment]
@hboutemy not really, it just includes goals and -rf flag. No other params are added. Shall we include them too?

**Comment by splatch** [comment]
I updated to use `StringUtils` from plexus utils available in imports.

**Comment by michael-o** [comment]
I agree with @hboutemy and would go for `<goals and options>` if we cannot guarentee the exact same input.

**Comment by axelfontaine** [comment]
I disagree with @hboutemy . It's not because something can't be made to work in 100% of the cases from day 1, that the vast number of cases where it does work should be discarded.

+1 for this PR.

**Comment by hboutemy** [comment]
than you Axel for feedback: it's good to have discussion.
IMHO, the reality of how I work is: I scroll up to get my previous command then add the "-rf xxx"
don't you do the same?

**Comment by michael-o** [comment]
@hboutemy @splatch Is there something we can agree on and proceed with the PR reasonably?

**Comment by splatch** [comment]
@michael-o I had no capacity to push it forward towards direction pointed by @hboutemy. If there is a will to accept PR as-is then I can rebase it against the current head. Otherwise, I will have to abandon it. :(

**Comment by michael-o** [comment]
@hboutemy if we cannot agree on something let's make it general with `<args>` otherwise we have goals, phases, options and properties.

**Comment by michael-o** [comment]
@splatch, I think we won't come to a conclusion here. Since `<goals>` is incomplete right now, let's rename to `<args>` for now.

**Comment by michael-o** [comment]
@splatch, if we cannot agree on something let's make it general with `<args>` otherwise we have goals, phases, options and properties. @hboutemy @rfscholte WDYT?

**Comment by rfscholte** [comment]
`<args>` works for me

**Comment by Tibor17** [comment]
@axelfontaine probably the devs probably know that fix is incomplete with some alternatives.
I understand the customer @splatch and i do not understand our devs because they did not guide @splatch to write ITs with all alternatives. Probably they have not picked up all alternatives and maybe they did not think about JMX with complete set of CLI args.

**Comment by michael-o** [comment]
Superceded by MNG-6747.

**Pull request closed without merging**
