### PR TITLE
[3.8.x][MNG-7395] - Support system-properties in extension.xml

### PR DESCRIPTION
**Pull request by laeubi**
We at [Tycho](https://github.com/eclipse/tycho) have a combination of a core-extension and a build-plugin. What always is a source of confusion, that one is able to define e.g. a `<tycho-version>` property that could be overridden on the commandline using -D but no such thing exits for the `.mvn/extensions.xml`

This makes it also hard to make some regression-testing e.g. to check fast if a certain problem occurs also in the previous version as one always has to take in mind that the `.mvn/extensions.xml` must be edited by hand.

For that reason it would help if at least basic interpolation using the "maven-properties" would be possible.

This PR adds support for having basic interpolation in `.mvn/extensions.xml` to either:

1. Specify a (default) version in `maven.config`
2. Specify a version on the commandline with `mvn -Dsome.version=1.2.3`

FYI @mickaelistria @akurtakov 

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/MNG/issues/MNG-7395) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by michael-o** [comment]
@laeubi Instead of `jvm.config` you can also use `maven.config`. This will make it a user property.

**Comment by laeubi** [comment]
@michael-o thanks for the hint with maven.config! I'm currently try to derive a Integration test and probably will use `maven.config ` there as well.

**Comment by michael-o** [comment]
Good, `jvm.config` should really be for JVM-related options only.

**Comment by laeubi** [comment]
I have updated the PR description accordingly.

**Comment by jira-importer** [comment]
Resolve #9171

**Pull request merged**
