### PR TITLE
[MNG-7019] Notify also at start when profile is missing

### PR DESCRIPTION
**Pull request by michael-o**
@rfscholte Here it is, prerequisite for release profile removal.

### CODE REVIEW

**Comment by rfscholte** [comment]
This is only one the warning part. It should also break the build, because what we've already seen due a bug in maven-release-plugin is that if the release-profile is not activated (and you are not aware of it) you'll end up with an incomplete release. 
Sebb also suggested to suppress that check, but I see that as optimization. https://issues.apache.org/jira/browse/MNG-6511 suffers the same issue. I suggested to introduce a ? prefix to mark it as optional. e.g. `-P ?apache-release` will active this profile, but won't break it when it is missing, whereas `-P apache-release` should break the build.

**Comment by michael-o** [comment]
Correct, this PR is for the warning only. No other functionality intentionally. I agree with breaking the build and the options `?` prefix, but it must be handled in separate tickets.

**Comment by michael-o** [comment]
Is this PR acceptable for you?

**Comment by rfscholte** [comment]
Once the separate ticket is created (with cross links to each other) this change is fine.

**Comment by michael-o** [comment]
Isn't it MNG-6012?

**Comment by rfscholte** [comment]
Ok, now I understand the confusion, I wasn't aware this is a new subtask of MNG-6012. 
The description of MNG-6012 needs to be updated that (1) is fixed with MNG-7019, and that MNG-6012 is now about (2): breaking the build.

**Comment by michael-o** [comment]
Agreed.

**Comment by michael-o** [comment]
Done: https://issues.apache.org/jira/browse/MNG-6012?focusedCommentId=17232034&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17232034

**Comment by michael-o** [comment]
@rfscholte Are we good to merge now?

**Review by rfscholte — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #8018

**Pull request merged**
