### PR TITLE
[MNG-6206] display deprecation build warning in case when dependencies use metaversions (LATEST or RELEASE)

### PR DESCRIPTION
**Pull request by dejan2609**
**JIRA ticket**: [MNG-6206: We should produce a WARNING by using RELEASE, LATEST as versions](https://issues.apache.org/jira/browse/MNG-6206)

(Note: replaces previously closed PR #120)

### CODE REVIEW

**Comment by khmarbaise** [comment]
Please make a complete commit message with reference to the appropriate ticket.
```
[MNG-6206] display deprecation build warning in case when dependencies use metaversions (LATEST or RELEASE)
 Maybe some explantations/descriptions if needed
```
I have applied your patch on a branch MNG-6206 to check via the integration tests. I have modified the commit message see here:
https://git-wip-us.apache.org/repos/asf?p=maven.git;a=commitdiff;h=eb6b212b567c287734a2dbbef3c113fe650f1def

Waiting on the results of the integration tests.

**Comment by dejan2609** [comment]
@khmarbaise
Integration tests passed as expected, that's nice.

Commit message is altered just a little bit and force-pushed here.

**Comment by khmarbaise** [comment]
I have merged the pull request to Maven master. So you can close the pull request here on GitHub. Thanks for our help.

**Comment by dejan2609** [comment]
I'm happy to help ! 
Regards.

**Comment by ctrueden** [comment]
@dejan2609 @khmarbaise I use LATEST and RELEASE a lot for various purposes, such as CLI tooling that automatically synthesizes POMs to perform various tasks. I personally feel deprecating these metaversions was a mistake—I find them incredibly useful, with the understanding that I would never use them for production reproducible builds. But I do understand the rationale: we don't want to encourage anyone to use these in a way that harms the stability of dependency resolution, reproducibility-wise. So I'm OK with it, as long as there is a migration path forward for these sorts of use cases.

But what is that path? I cannot find a way to replicate either of the metaversion behaviors using version ranges. There are problems with version ranges ([MNG-3092](https://issues.apache.org/jira/browse/MNG-3092), [MNG-6049](https://issues.apache.org/jira/browse/MNG-6049)) preventing them from being used as a replacement for LATEST or RELEASE. Furthermore, in my tests, specifying a version range like `[0,)` causes Maven to download POMs at a bunch of (maybe all?) versions of an artifact, whereas `LATEST` and `RELEASE` do not trigger en masse downloading.l

Is there a non-deprecated syntax that has equivalent behavior? As things stand, I am concerned that support for these metaversions is going to disappear in a future version of Maven. If there is no way to achieve the metaversion behavior without them, please let me know, so that I can open an issue on the JIRA. Thanks!

**Comment by jira-importer** [comment]
Resolve #7242

**Pull request closed without merging**
