### PR TITLE
[MNG-8005] do not ignore ide WorkspaceReader

### PR DESCRIPTION
**Pull request by jonasrutishauser**
This change should fix the regression introduced by https://github.com/apache/maven/pull/963/files#diff-c14736c8f0b57d9f26af7f81fff3114a217edbed2b42049aa3c746ddab38966eR245-R250

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by cstamas — APPROVED** [review]

**Review by gnodet — CHANGES_REQUESTED** [review]
@jonasrutishauser I don't really see what's broken with the mentioned commit...
Support for additional workspace readers has already been added through https://github.com/gnodet/maven/commit/a4729755ae54833caaa408cd7c614ee814f85c00

The IDE workspace reader is already injected in the repository system session:
  https://github.com/apache/maven/blob/732e3649e12ab9c6bce570340b83b7270d5c346a/maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java#L156

**Comment by gnodet** [comment]
@jonasrutishauser an IT would be welcomed

**Comment by jonasrutishauser** [comment]
As requested I added a test: apache/maven-integration-testing#332

**Comment by jonasrutishauser** [comment]
> The IDE workspace reader is already injected in the repository system session:
> 
> https://github.com/apache/maven/blob/732e3649e12ab9c6bce570340b83b7270d5c346a/maven-core/src/main/java/org/apache/maven/internal/aether/DefaultRepositorySystemSessionFactory.java#L156

That's correct, but this injected reader is directly overwritten:
https://github.com/apache/maven/blob/732e3649e12ab9c6bce570340b83b7270d5c346a/maven-core/src/main/java/org/apache/maven/DefaultMaven.java#L417-L422

**Comment by cstamas** [comment]
Proposed PR that is a bit broader (but performs bigger and IMHO "proper" cleanup in this area): https://github.com/apache/maven/pull/1385

**Comment by jira-importer** [comment]
Resolve #10844

**Pull request closed without merging**
