### PR TITLE
Implement some #toString() methods (3.9.x)

### PR DESCRIPTION
**Pull request by pzygielo**
- [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

-----

- Picked from #914 and spotless-reformatted.

### CODE REVIEW

**Comment by pzygielo** [comment]
Seems that ITs fail since c0c752baefac68bdedf106265337df82545a6944 on that branch.

**Comment by michael-o** [comment]
Merge with 4adaf2abca4e3018b92c0c03e07c50a6b1a8ddab. Looking at ITs. If they rely on `#toString()` then they are flawed :-(

**Comment by michael-o** [comment]
The failures in the Core ITs aren't related to this PR. All is good, different topic to fix them.

**Comment by jira-importer** [comment]
Resolve #8806

**Pull request closed without merging**
