### PR TITLE
Fix packaging not found

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by gnodet** [comment]
@cstamas @wendigo this will hopefully fix the problem in beta-2 for trino. I'd like to merge it and have https://github.com/trinodb/trino/pull/21966 point to the snapshot repository... ?

**Comment by wendigo** [comment]
@gnodet I can test with a snapshot - please share a link to the build (zip)

**Review by cstamas — APPROVED** [review]
LGTM, but this looks hacky as we discussed with Guillaume

**Comment by wendigo** [comment]
I couldn't test it through the wrapper:
```
grep distributionUrl .mvn/wrapper/maven-wrapper.properties
distributionUrl=https://repository.apache.org/content/repositories/snapshots/org/apache/maven/apache-maven/4.0.0-beta-3-SNAPSHOT/apache-maven-4.0.0-beta-3-20240515.173255-2-bin.zip
./mvnw: line 246: /var/folders/n4/vl45d5rn5n1_yk_pl5xkpd380000gn/T/tmp.CNmLdxlcJH/apache-maven-4.0.0-beta-3-20240515.173255-2/mvnw.url: No such file or directory
```

I'm testing it locally now.

**Comment by wendigo** [comment]
Locally it works flawlessly :) Thanks @gnodet

**Pull request merged**
