### PR TITLE
Maven.config from start scripts

### PR DESCRIPTION
**Pull request by michael-o**
Merely a draft for:
* https://cwiki.apache.org/confluence/display/MAVEN/Commandline+inheritance

### CODE REVIEW

**Comment by mthmulders** [comment]
From [MNG-7193](https://issues.apache.org/jira/browse/MNG-7193):
> `MAVEN_ARGS` is overwritten by `maven.config` is overwritten by CLI arguments.

However, if I build Maven on this branch and test with 

```console
$ cat .mvn/maven.config 
-V
-DskipTests=true

$ MAVEN_ARGS="-DskipTests=false" mvn test 
```

I get
```console
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running foo.AppTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 s - in foo.AppTest
```

Since `maven.config` should have precedence over `MAVEN_ARGS`, I would expect the tests to be skipped. If I use the same `maven.config` and run `mvn test` (without `MAVEN_ARGS`) the tests are skipped, as expected.

I did a second test, where a Maven profile upgrades a plugin; it shows the same behaviour: `MAVEN_ARGS` "wins" from `.mvn/maven.config`, despite [MNG-7193](https://issues.apache.org/jira/browse/MNG-7193) saying the reverse.

**Comment by michael-o** [comment]
Let me get in touch with you later this week about this.

**Comment by michael-o** [comment]
You're right. It was written before we have agreed on option 7 in https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=186877056#content/view/186877056. I will rework.

**Comment by michael-o** [comment]
This PR will be superseded with two alternatives as soon as #637 and #638  are merged.

**Comment by michael-o** [comment]
Superseded by #936.

**Pull request closed without merging**
