### PR TITLE
[MNG-8370] Add maven.repo.local.head

### PR DESCRIPTION
**Pull request by cstamas**
As counterpart to maven.repo.local.tail, but this one "prepends" while other "appends". This means one can do like this

```
$ mvn install -Prun-its -Dmaven.repo.local.head=~/.m2/repository-it
```

And have stuff installed into dedicated IT local repo (as IT bits must be installed), instead to pollute own local repo.

---

https://issues.apache.org/jira/browse/MNG-8370

### CODE REVIEW

**Review by gnodet — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
@cstamas, @gnodet what do you think to add it to 3.9.x?

**Comment by cstamas** [comment]
Yes plase

**Comment by slawekjaranowski** [comment]
Ok, I will do

**Comment by jira-importer** [comment]
Resolve #9483

**Pull request merged**
