### PR TITLE
Replace Properties with Map<String, String> in the v4 api

### PR DESCRIPTION
**Pull request by gnodet**
Remove properties from the v4 model and use Map<String, String> instead

### CODE REVIEW

**Comment by michael-o** [comment]
Are we sure that String-based properties are sufficient?

**Comment by gnodet** [comment]
> Are we sure that String-based properties are sufficient?

No, but is there any way to be sure ?  The sources are all string based (system properties, environment properties, and model properties).  It's more about what we want to provide imho.

**Comment by michael-o** [comment]
Note that modules like Resolver do use objects in their config properties...

**Comment by cstamas** [comment]
> Note that modules like Resolver do use objects in their config properties...

If so, that's wrong. That should be in session data I guess. Do you refer to Wagon config (the only case I know of)?

**Comment by michael-o** [comment]
> > Note that modules like Resolver do use objects in their config properties...
> 
> If so, that's wrong. That should be in session data I guess. Do you refer to Wagon config (the only case I know of)?

See here: https://maven.apache.org/resolver/configuration.html. Many non-string properties.

**Comment by gnodet** [comment]
> > > Note that modules like Resolver do use objects in their config properties...
> > 
> > 
> > If so, that's wrong. That should be in session data I guess. Do you refer to Wagon config (the only case I know of)?
> 
> See here: https://maven.apache.org/resolver/configuration.html. Many non-string properties.

Those are all in maven-resolver.  Do you imply if they are useful there, we should also provide a `Map<String, Object>` in the maven api ?

**Comment by cstamas** [comment]
@michael-o that is resolver, and Maven _is configuring_ resolver, while Maven itself can get hold only on string-string pairs, as the "sources" are really system properties, cmd switches, etc. How can a use define "an object" as config property for maven? MavenExecRequest holds Properties as well https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java

**Comment by michael-o** [comment]
> > > > Note that modules like Resolver do use objects in their config properties...
> > > 
> > > 
> > > If so, that's wrong. That should be in session data I guess. Do you refer to Wagon config (the only case I know of)?
> > 
> > 
> > See here: https://maven.apache.org/resolver/configuration.html. Many non-string properties.
> 
> Those are all in maven-resolver. Do you imply if they are useful there, we should also provide a `Map<String, Object>` in the maven api ?

I think so, yes. If you look at `Properties#getProperty()` it returns the value if and only if it is of type `String`. I wonder what the benefit of `Map<String, Object>`  over `Properties`.

**Comment by michael-o** [comment]
> @michael-o that is resolver, and Maven _is configuring_ resolver, while Maven itself can get hold only on string-string pairs, as the "sources" are really system properties, cmd switches, etc. How can a use define "an object" as config property for maven? MavenExecRequest holds Properties as well https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java

I aware of the string-only sources, but that doesn't mean that properties can be added at runtime which aren't strings. WDYT?

**Comment by gnodet** [comment]
> > @michael-o that is resolver, and Maven _is configuring_ resolver, while Maven itself can get hold only on string-string pairs, as the "sources" are really system properties, cmd switches, etc. How can a use define "an object" as config property for maven? MavenExecRequest holds Properties as well https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java
> 
> I aware of the string-only sources, but that doesn't mean that properties can be added at runtime which aren't strings. WDYT?

Note that this change is mainly about the model which is immutable.  Which makes me realize I did not change the `Session.getUserProperties()` and `Session.getSystemProperties()`.   So for the model classes, I would think an immutable `Map<String, String>` should be sufficient.  

Currently, the `Project`, does not expose a set of properties, but that can be added.  Fwiw, the model is actually immutable, however, `Session` and `Project` objects wrap the existing `MavenSession` and `MavenProject`, so they are not really immutable, even though no direct API can modify those.  Changing a project property can currently be done using a `Service` so that maven can intercept any call: for example the `Project` can be _modified_ using the [`ProjectManager`](https://github.com/apache/maven/blob/master/api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectManager.java#L91).  And the `setProperty` currently takes a `String` as the value, so that method would have to be modified.

Anyway, I think `Session.getUserProperties()` and `Session.getSystemProperties()`, `Project.getProperties()` can be moved to `Map<String, Object>`.  That should be sufficiently opened.

Fwiw, the benefit of `Map<String, Object>` over `Properties` is that it's an interface, so the underlying implementation can be changed.  It can be made immutable, easily copied, can be used in newer API with streams, etc...  Furthermore, the `Properties` class is completely broken, merging semantics of `Map<String, String>` and `Map<String, Object>` for backward compatibility.  The immutable model actually provides an immutable version of `Properties`, but this is very cumbersome to implement and a `Map` would allow to get rid of those implementations, and even replace them with `Map.copyOf()` when switching to JDK 11.

**Comment by michael-o** [comment]
> > > @michael-o that is resolver, and Maven _is configuring_ resolver, while Maven itself can get hold only on string-string pairs, as the "sources" are really system properties, cmd switches, etc. How can a use define "an object" as config property for maven? MavenExecRequest holds Properties as well https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/execution/MavenExecutionRequest.java
> > 
> > 
> > I aware of the string-only sources, but that doesn't mean that properties can be added at runtime which aren't strings. WDYT?
> 
> Note that this change is mainly about the model which is immutable. Which makes me realize I did not change the `Session.getUserProperties()` and `Session.getSystemProperties()`. So for the model classes, I would think an immutable `Map<String, String>` should be sufficient.
> 
> Currently, the `Project`, does not expose a set of properties, but that can be added. Fwiw, the model is actually immutable, however, `Session` and `Project` objects wrap the existing `MavenSession` and `MavenProject`, so they are not really immutable, even though no direct API can modify those. Changing a project property can currently be done using a `Service` so that maven can intercept any call: for example the `Project` can be _modified_ using the [`ProjectManager`](https://github.com/apache/maven/blob/master/api/maven-api-core/src/main/java/org/apache/maven/api/services/ProjectManager.java#L91). And the `setProperty` currently takes a `String` as the value, so that method would have to be modified.
> 
> Anyway, I think `Session.getUserProperties()` and `Session.getSystemProperties()`, `Project.getProperties()` can be moved to `Map<String, Object>`. That should be sufficiently opened.
> 
> Fwiw, the benefit of `Map<String, Object>` over `Properties` is that it's an interface, so the underlying implementation can be changed. It can be made immutable, easily copied, can be used in newer API with streams, etc... Furthermore, the `Properties` class is completely broken, merging semantics of `Map<String, String>` and `Map<Object, Object>` for backward compatibility. The immutable model actually provides an immutable version of `Properties`, but this is very cumbersome to implement and a `Map` would allow to get rid of those implementations, and even replace them with `Map.copyOf()` when switching to JDK 11.

Thanks for the elaboration. I think  `Map<String, Object>`/`Map<String, String>` dependending on the usecase is the best compromise. If this is really about model only, `String, String` is appropriate.

I hope this can solve: https://issues.apache.org/jira/browse/MNG-6801 and also hope that something like https://issues.apache.org/jira/browse/MNG-6437 won't be blocked by this.

**Comment by gnodet** [comment]
> I think `Map<String, Object>`/`Map<String, String>` dependending on the usecase is the best compromise. If this is really about model only, `String, String` is appropriate.

Looking at the main use case, which is plugin configuration, it seems only the _properties_ (i.e. string key/string value) are actually used at this step, see https://github.com/apache/maven/blob/2a9f39336cec1d8e52d30cc48503d51ed8672536/maven-core/src/main/java/org/apache/maven/plugin/PluginParameterExpressionEvaluator.java#L385-L398.
So I'm not sure it makes sense to open the API wider to `Map<String, Object>`.  This should not affect the old api and upon migration, users should use the `SessionData` instead. WDYT ?

> I hope this can solve: https://issues.apache.org/jira/browse/MNG-6801 and also hope that something like https://issues.apache.org/jira/browse/MNG-6437 won't be blocked by this.

For [MNG-6801](https://issues.apache.org/jira/browse/MNG-6801), it should just be a simple change to support it on the v4 model. For [MNG-6437](https://issues.apache.org/jira/browse/MNG-6437), I have a local test showing that interpolation can be enhanced to support `${session.multiModuleProjectDirectory.uri}` using the v4 api and `session.getMultiModuleProjectDirectory().toUri()`.

**Comment by gnodet** [comment]
I'm going to merge this PR.  If there's an actual use case for some maps to be opened to `Map<String, Object>` instead of `Map<String, String>`, we can always change those.

**Pull request merged**
