### PR TITLE
Fixing misspellings in test names (Progessed to Progressed)

### PR DESCRIPTION
**Pull request by august782**
I noticed that there seem to be some misspellings in the test names in this test class (along with some similar misspellings in local variable names), and so this pull request simply addresses those misspellings.

### CODE REVIEW

**Comment by michael-o** [comment]
Merged, please close.

**Comment by michael-o** [comment]
@august782 Please close this PR.

**Comment by august782** [comment]
This pull request's status right now is "Merged" and I cannot close this pull request.

**Comment by michael-o** [comment]
Terribly annoying :-(

**Pull request merged**
