### PR TITLE
Fix dependabot alerts

### PR DESCRIPTION
**Pull request by cstamas**
(that are not applicable, but look ugly).

These tests are NOT built, but are taken from real projects several years ago, and used in POM related UTs.

Hence, for example update of velocity is completely okay, even if in "real life" it would not compile.

### CODE REVIEW

**Comment by gnodet** [comment]
> (that are not applicable, but look ugly).
> 
> These tests are NOT built, but are taken from real projects several years ago, and used in POM related UTs.
> 
> Hence, for example update of velocity is completely okay, even if in "real life" it would not compile.

So what's the point ?  The version don't even match those used by maven...

**Comment by gnodet** [comment]
Ah, the answer is in the PR title...

**Review by gnodet — APPROVED** [review]

**Comment by cstamas** [comment]
The point is **only** to make these go away https://github.com/apache/maven/security/dependabot

Yes, these are POMs used in UTs only in some POM-related tests...

**Comment by mthmulders** [comment]
Wouldn't it make more sense to exclude those projects using [dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)?

**Comment by cstamas** [comment]
Sure! 

> Wouldn't it make more sense to exclude those projects using [dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)?

Sure, that would work as well...

**Comment by cstamas** [comment]
@mthmulders any example how to do it?

**Comment by mthmulders** [comment]
> @mthmulders any example how to do it?

It seems not to be as easy as I hoped: https://github.com/dependabot/dependabot-core/issues/4364, https://github.com/dependabot/dependabot-core/issues/2883.

The best I could find is a suggestion to configure the "maven" `package-ecosystem` multiple times: once for the root of the project, and then for each location that you want to exclude you specify it again but with `interval: "never"`. Not sure if that works as intended.

**Comment by cstamas** [comment]
Yes, that is my understanding as well... or ignore, but then one need to enlist ALL ignored deps, that probably overlaps with Maven used ones, where we DO WANT dependabot.

It would be simplest if there would be something like `ignore_directory` or alike.

**Pull request merged**
