### PR TITLE
[3.9.x][MNG-7391] add execution strategy+runner required by Maven Build Cache

### PR DESCRIPTION
**Pull request by hboutemy**
https://issues.apache.org/jira/browse/MNG-7391

supercedes #622

### CODE REVIEW

**Review by maximilian-novikov-db — APPROVED** [review]

**Comment by michael-o** [comment]
Does this really make sense on 3.8.x? I would expect that Build Cache is 3.9+?!

**Comment by gnodet** [comment]
> Does this really make sense on 3.8.x? I would expect that Build Cache is 3.9+?!

The target is definitely 3.9.x.  I renamed to `[3.8.x]` to target the branch.  As soon as 3.8.5 is done, the plan is to create a 3.9.x branch and merge this PR there.

**Comment by gnodet** [comment]
Fixed with https://github.com/apache/maven/commit/1954d51ff2841045b4af8a515ad0719805269d8d

**Comment by jira-importer** [comment]
Resolve #9173

**Pull request closed without merging**
