### PR TITLE
[MNG-6114] Elements from the global settings should be ordered before…

### PR DESCRIPTION
**Pull request by michael-o**
… elements from the user settings

This supersedes and closes #142

### CODE REVIEW

**Comment by michael-o** [comment]
@rfscholte Any objections to merge this

**Comment by rfscholte** [comment]
@cstamas @stephenc as this is a change in the dependency resolution, you should have a look it this too.

**Comment by michael-o** [comment]
@cstamas @stephenc Any opinion?

**Comment by cstamas** [comment]
IMHO this looks okay.

**Pull request closed without merging**
