### PR TITLE
[MNG-4777] Match property for profile activation against a regex

### PR DESCRIPTION
**Pull request by vjkoskela**

### CODE REVIEW

**Comment by jvanzyl** [comment]
How do you plan on using this feature?

**Comment by vjkoskela** [comment]
The use case we had was to activate a different profile for snapshot and release versions in order to release to a custom artifact store using the http wagon plugin. We couldn't match directly against the version so we pulled it into a property which enabling matching with these changes.

**Comment by rfscholte** [comment]
Not anymore possible to merge. Also, changing the specification will have a negative effect on all consumers of the pom. Allowing regex as property comes with extra requirements and such profile must be removed when distributing the pom. 
I'll close this PR, MNG-4777is still open.

**Comment by jira-importer** [comment]
Resolve #6321

**Pull request closed without merging**
