### PR TITLE
#MNG-5844: Close IO Streams in finally block

### PR DESCRIPTION
**Pull request by sugartxy**
Place the close method in the finally clause, so we can ensure it always
runs regardless of how the method exits.

### CODE REVIEW

**Comment by ifedorenko** [comment]
Maven is targeting java 7 already, try-with-resource is more appropriate way to guarantee IO streams are closed.

**Comment by jvanzyl** [comment]
+1 please use try-with-resources

**Comment by sugartxy** [comment]
@ifedorenko @jvanzyl thx. I will rewrite it using try-with-resources ASAP.

**Comment by sugartxy** [comment]
@jvanzyl  Please let me know if you want something else to be done on this pull request before you could merge it.

**Comment by Tibor17** [comment]
try-with-resources is cool.
+1

**Comment by krosenvold** [comment]
Unfortunately I just merged the gigantic migrate everything to jdk7 branch, which made this pull request stale. Can you re-align it, and I will merge it ?

**Comment by sugartxy** [comment]
@krosenvold sorry for the mistake I've made. Does it work now?

**Comment by jvanzyl** [comment]
@sugartxy looks like @krosenvold is doing some JDK7 work so I'll let him merge this.

**Comment by sugartxy** [comment]
Oops! I misunderstood. Thank u! :)

**Comment by krosenvold** [comment]
There were some minor adjustments I did to your stuff, but nothing significant :) Thanks a lot !

**Comment by jira-importer** [comment]
Resolve #6417

**Pull request closed without merging**
