### PR TITLE
[MNG-6727] Changed expression check to project.version and project.parent.version

### PR DESCRIPTION
**Pull request by jmax01**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by jmax01** [comment]
All (*-latestest, 11) ITS fail in the same spot unrelated to the patch.

It appears it can't find `java.util.Objects` which was added in `1.7`.

```
2021-01-06T20:54:59.0695722Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project build-plugin: Compilation failure
2021-01-06T20:54:59.0710252Z [ERROR] /home/runner/work/maven/maven/maven-integration-testing/core-it-suite/target/test-classes/mng-6972-allow-access-to-graph-package/build-plugin/src/main/java/com/example/BuildExtensionUsingGraphPackage.java:[4,17] cannot find symbol
2021-01-06T20:54:59.0714174Z [ERROR]   symbol:   class Objects
2021-01-06T20:54:59.0716976Z [ERROR]   location: package java.util
2021-01-06T20:54:59.0719183Z [ERROR] -> [Help 1]
2021-01-06T20:54:59.0730372Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project build-plugin: Compilation failure
2021-01-06T20:54:59.0743693Z /home/runner/work/maven/maven/maven-integration-testing/core-it-suite/target/test-classes/mng-6972-allow-access-to-graph-package/build-plugin/src/main/java/com/example/BuildExtensionUsingGraphPackage.java:[4,17] cannot find symbol
2021-01-06T20:54:59.0746982Z   symbol:   class Objects
2021-01-06T20:54:59.0749402Z   location: package java.util
```

**Comment by michael-o** [comment]
> 
> 
> All (*-latestest, 11) ITS fail in the same spot unrelated to the patch.
> 
> It appears it can't find `java.util.Objects` which was added in `1.7`, this is very odd.
> 
> ```
> 2021-01-06T20:54:59.0695722Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project build-plugin: Compilation failure
> 2021-01-06T20:54:59.0710252Z [ERROR] /home/runner/work/maven/maven/maven-integration-testing/core-it-suite/target/test-classes/mng-6972-allow-access-to-graph-package/build-plugin/src/main/java/com/example/BuildExtensionUsingGraphPackage.java:[4,17] cannot find symbol
> 2021-01-06T20:54:59.0714174Z [ERROR]   symbol:   class Objects
> 2021-01-06T20:54:59.0716976Z [ERROR]   location: package java.util
> 2021-01-06T20:54:59.0719183Z [ERROR] -> [Help 1]
> 2021-01-06T20:54:59.0730372Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project build-plugin: Compilation failure
> 2021-01-06T20:54:59.0743693Z /home/runner/work/maven/maven/maven-integration-testing/core-it-suite/target/test-classes/mng-6972-allow-access-to-graph-package/build-plugin/src/main/java/com/example/BuildExtensionUsingGraphPackage.java:[4,17] cannot find symbol
> 2021-01-06T20:54:59.0746982Z   symbol:   class Objects
> 2021-01-06T20:54:59.0749402Z   location: package java.util
> ```

This has also been observed with other PRs as well. I'd see it as unrelated for now.

**Comment by jmax01** [comment]
@michael-o Do I need a separate Jira to change the error message from: "Version must be a constant" to "A version inherited from the parent must not be a version range" since this would require changes to [MavenITmng2199ParentVersionRangeTest.java](https://github.com/apache/maven-integration-testing/blob/master/core-it-suite/src/test/java/org/apache/maven/it/MavenITmng2199ParentVersionRangeTest.java)?

Further, if I do update MavenITmng2199ParentVersionRangeTest what version range do I use to allow checking both messages? I am hoping this gets back ported to the next 3.x version (if there is one).

**Comment by slachiewicz** [comment]
FYI - I fixed ITS (by default compiler.target was set to Java 6.

CI run in progress: https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven/job/MNG-6727/

**Comment by michael-o** [comment]
Since I don't know the implications of this I requested @rfscholte and @khmarbaise to review this.

**Comment by bullboa** [comment]
Hi @jmax01 , I bumped into this bug yesterday and found and looked at your fix. When I clone it and build maven locally from your branch it solves the bug in my project, thank you! I saw you [created a branch](https://github.com/apache/maven/compare/MNG-6727) in October, were you planning on opening a new PR for that branch? This is my first venture into the source code of Maven but from what I can understand this problem is an actual bug that your PR will fix, so it would be fantastic to have it merged and at some point included in a future release.

In theory maybe I can open a PR for your new branch and basically copy+paste what you wrote above, but I'm not sure if that would be the best approach. Maybe you would want to merge your other branch into this one and we can see if that builds ok?

**Comment by michael-o** [comment]
Please rebase

**Comment by michael-o** [comment]
As far as I understand this PR it slightly relaxes the expression to a disallowed minimum. What about pom.version?

**Comment by michael-o** [comment]
Just tried `${pom.version}` with `help:evaluate`, this must be also tested.

**Comment by michael-o** [comment]
@jmax01 `${pom.parent.version}` also needs to be added. Also rebase and reconcile the conflict. Targetting for 3.8.5.

**Review by michael-o — CHANGES_REQUESTED** [review]
@jmax01 `${pom.parent.version}` also needs to be added. Also rebase and reconcile the conflict. Targetting for 3.8.5.

**Pull request closed without merging**
