### PR TITLE
[MNG-7285] [3.8.x] Replace ThreadLocal in MavenProject with locking in MojoExecutor to fix MNG-6843

### PR DESCRIPTION
**Pull request by famod**
As mentioned here https://github.com/apache/maven/pull/570#issuecomment-939153676, this removes the `ThreadLocal` from `MavenProject` that was introduced in 3.8.2 and instead adds locking to `MojoExecutor` to prevent MNG-6843.

The major advantage is that there are no threading visibility issues anymore when passing around `MavenProject`s.

The major downside is that `MavenProject` artifacts are not "protected" anymore from concurrent modifications, just as in 3.8.1 and before.
Another downside is higher overall build runtime in case an aggregating goal takes some time to finish as it will block all other mojo executions until finished (in parallel build mode).

It does fix MNG-6843 which can be verified via https://github.com/famod/parallel-testbed/tree/compiler-fix

PS: The root cause can only be solved with a proper refeactoring like #475 but I don't think even that is enough.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by michael-o** [comment]
@rmannibucau Do you consider this as a better approach than thread local? What about Olivier's PR?

**Comment by famod** [comment]
Oliver's PR doesn't help when thread pools are involved, btw.

@gnodet I'd love to hear your take on this.

**Comment by gnodet** [comment]
@famod I will do asap.  At first glance, I wonder if this is somewhat related to  https://issues.apache.org/jira/browse/MNG-7156 and #476.  The problem and locking strategy are different, but if the problem is the access to the `MavenProject`, I wonder if #476 would solve both problems...

**Comment by mickaelistria** [comment]
Maybe you should consider adding #570 or similar test into this PR to validate this fix and also prevent from future regressions.

**Comment by famod** [comment]
@michael-o
> Can you provide a PR for master when we have agreed on a solution?

Sure!

@gnodet 
Thanks for the pointer, I'll have a look #476 later

**Comment by gnodet** [comment]
> I confirm that #476 seems to fix [MNG-6843](https://issues.apache.org/jira/browse/MNG-6843) as well. I've built maven-3.8.x with that `LockingEventSpy` and there were no failures in https://github.com/famod/parallel-testbed/tree/compiler-fix 👍
> 
> Overall, I would prefer #476 over this because it also prevents inconsistencies in other places. It's also more fine grained in that it seems to reduce the locking scope to the actual project being executed whereas with my approach, all mojo executions have to wait for an aggregating execution, no matter which project they are about to be executed for.
> 
> @gnodet
> 
> > I think my proposal would not cause any delay in the build
> 
> If a "regular" mojo execution wants to run for project A, but an aggregating mojo execution comes first, chances are that A is indeed locked and the other execution has to wait for that. So there will be a "delay" but there is no way around that, a lock is a lock.
> 
> What I don't fully understand yet: When is `ProjectStarted` fired, especially in the case for an aggregating execution (which involves multiple projects)?

The `ProjectStarted` is fired when a project's build is began, i.e. once for a given project in a reactor, whereas during an aggregating execution, there's the notion of _forked lifecycle_, and the `ForkedProjectStarted` event is fired from inside the `MojoExecutor`.

**Comment by famod** [comment]
@gnodet 
> whereas during an aggregating execution, there's the notion of _forked lifecycle_, and the `ForkedProjectStarted` event is fired from inside the `MojoExecutor`.

I was under the impression that forked lifecycles/goals and aggregating executions are two different things?
I'm mean your locking approach seems to work, so I won't complain, but I haven't fully understood why.

**Comment by gnodet** [comment]
Superseded by #628 for 3.x and #627 for master.

**Pull request closed without merging**
