### PR TITLE
MNG-7529  - 3.9.x port

### PR DESCRIPTION
**Pull request by hgschmie**
Ensure that any versions resolved as part of a version range request
only reference repositories that are actually enabled for the type of
version (SNAPSHOT versions against snapshot repos, release versions
against release repositories).

Following this checklist to help us incorporate your
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed
       for the change (usually before you start working on it).  Trivial changes like typos do not
       require a JIRA issue. Your pull request should address just this issue, without
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MNG-XXX] SUMMARY`, where you replace `MNG-XXX`
       and `SUMMARY` with the appropriate JIRA issue. Best practice is to use the JIRA issue
       title in the pull request title and in the first line of the commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will
       be performed on your pull request automatically.
 - [X] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by michael-o** [comment]
Why? No one had reviewed this.

**Comment by slawekjaranowski** [comment]
Maybe by mistake ...
 - pointing issue are not conected with change
 - zero `commits` in PR, PR was update after merge

@hgschmie - can you explain?

**Comment by michael-o** [comment]
I am inclined to force push a revert. (Drop commit)

**Comment by hgschmie** [comment]
I reopened that as #787, BTW. I was not aware that committers require review; Apache has traditionally always been CTR.

**Comment by michael-o** [comment]
> I reopened that as #787, BTW. I was not aware that committers require review; Apache has traditionally always been CTR.

We don't do CTR anymore because 3.4.0 caused a lot of havoc. Therefore, anything which isn't a simple typo/doc change goes through a PR. It takes more time, but achieves better quality.

**Pull request merged**
