### PR TITLE
[MNG-7391] Fix MojosExecutionStrategy lookup to be able to look into the SessionScope

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by laeubi** [comment]
This looks good even though I'm not that familiar with how providers work, will this lookup on each request (so you get the highest component freshyl on the call) or do it cache it once requested?

**Comment by gnodet** [comment]
The component is cached by its scope.  When `m-build-cache-e` is not active, it's `@Singleton` and when it's active, it's the `@SessionScope`.  In both cases, that's fine, as the build cache extension does everything in the session scope anyway.

**Comment by laeubi** [comment]
@gnodet @michael-o just wondering, would this maybe a good candidate for a maven-3.8.6 or are there no bug-fix releases for maven?

**Comment by gnodet** [comment]
@laeubi the MojosExecutionStrategy has been introduced in 3.9.x and 4.0.x, but it's not present in 3.8.x branch.

**Comment by laeubi** [comment]
Alright, I forget about this :-)

**Comment by jira-importer** [comment]
Resolve #9173

**Pull request merged**
