### PR TITLE
[MNG-8172] Fix site building

### PR DESCRIPTION
**Pull request by gnodet**
JIRA issue: https://issues.apache.org/jira/browse/MNG-8172
Workaround for https://issues.apache.org/jira/browse/DOXIASITETOOLS-343

### CODE REVIEW

**Comment by michael-o** [comment]
Big question is now: Should the components in m-site-p rewritten to make things right? (for both Maven 3 and 4)

**Comment by gnodet** [comment]
> Big question is now: Should the components in m-site-p rewritten to make things right? (for both Maven 3 and 4)

Doxia 2.x can be used on Maven 3, right ? So if we fix it there, it may be sufficient, assuming we somehow force Maven 4 users to use m-site-p 4.x.  Though I suppose once the work is done on Doxia 2.x, porting it to Doxia 1.x should not be too difficult...

**Comment by gnodet** [comment]
> > Big question is now: Should the components in m-site-p rewritten to make things right? (for both Maven 3 and 4)
> 
> Doxia 2.x can be used on Maven 3, right ? So if we fix it there, it may be sufficient, assuming we somehow force Maven 4 users to use m-site-p 4.x. Though I suppose once the work is done on Doxia 2.x, porting it to Doxia 1.x should not be too difficult...

Given https://github.com/apache/maven-doxia-sitetools/pull/161, I assume the code does not build projects from local repository anymore.  I need to check if m-site-p 4.x works correctly on Maven 4.0.0-beta-3 or not.

**Comment by gnodet** [comment]
> > > Big question is now: Should the components in m-site-p rewritten to make things right? (for both Maven 3 and 4)
> > 
> > 
> > Doxia 2.x can be used on Maven 3, right ? So if we fix it there, it may be sufficient, assuming we somehow force Maven 4 users to use m-site-p 4.x. Though I suppose once the work is done on Doxia 2.x, porting it to Doxia 1.x should not be too difficult...
> 
> Given [apache/maven-doxia-sitetools#161](https://github.com/apache/maven-doxia-sitetools/pull/161), I assume the code does not build projects from local repository anymore. I need to check if m-site-p 4.x works correctly on Maven 4.0.0-beta-3 or not.

It does not, because the new `DefaultSiteTools` relies on `MavenProject.getParent()` which returns a `MavenProject` with `getBasedir() == null` when the parent has been loaded from the local repository.  We may want to change some semantics on the longer term, but for now, I don't think there's an easy way to work around the situation.  I think we should use this PR to restore the behaviour for next 4.x release.

**Comment by michael-o** [comment]
> > Big question is now: Should the components in m-site-p rewritten to make things right? (for both Maven 3 and 4)
> 
> Doxia 2.x can be used on Maven 3, right ? So if we fix it there, it may be sufficient, assuming we somehow force Maven 4 users to use m-site-p 4.x. Though I suppose once the work is done on Doxia 2.x, porting it to Doxia 1.x should not be too difficult...

I wouldn't put any effort into Doxia 1.x. Doxia 2.x is fully compatible with Maven 3 and intended to be used with 3.6.3+. m-site-p will be available for both Maven 3 and 4 with Doxia 2.x.

**Comment by michael-o** [comment]
Let me test this in the next few days.

**Comment by cstamas** [comment]
Did testing show any results?

**Comment by michael-o** [comment]
Still absent, will test end of week.

**Review by michael-o — APPROVED** [review]
Tested, works for me.

**Pull request merged**
