### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PoojaChandak**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by PoojaChandak** [comment]
Kindly have a look and let me know if the suggestions are good to be merged.

**Comment by PoojaChandak** [comment]
Hi, Kindly check if this is ok.

**Comment by slachiewicz** [comment]
Please squash all commits into single one

**Comment by PoojaChandak** [comment]
I have squashed commit number 12ce124 and 8a045a5 into one ad38521
Can you help me understand what else needs to be done?

**Comment by PoojaChandak** [comment]
Hi,
Kindly help me here.

**Comment by PoojaChandak** [comment]
I have acknowledged the mentioned by checking the boxes in the commit details.

**Comment by PoojaChandak** [comment]
Kindly help me understand what needs to be done to merge these changes and close this PR. Thanks.

**Review by elharo — APPROVED** [review]

**Comment by PoojaChandak** [comment]
The pull request was approved and then closed without merging. Kindly let me know if any amendments are suggested.

**Comment by slachiewicz** [comment]
H thank you for contribution - your fish has been merged as fe26a18

**Pull request closed without merging**
