### PR TITLE
[MNG-7129] http repo refactoring for java8

### PR DESCRIPTION
**Pull request by AlexanderAshitkin**
Cache repositories refactoring for java8 - using optionals instead of nullables

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
I believe that this entire code needs to be rewritten to use Wagon instead of manually fiddling with `HttpClient`.

**Comment by AlexanderAshitkin** [comment]
> I believe that this entire code needs to be rewritten to use Wagon instead of manually fiddling with `HttpClient`.

good point and should not be a big deal. will try to do it in following prs

**Comment by gnodet** [comment]
> > I believe that this entire code needs to be rewritten to use Wagon instead of manually fiddling with `HttpClient`.
> 
> good point and should not be a big deal. will try to do it in following prs

Not necessarily instead, but a simple abstraction layer would allow to use the default http repository or use wagon as an alternative and more versatile provider.

**Comment by AlexanderAshitkin** [comment]
> > > I believe that this entire code needs to be rewritten to use Wagon instead of manually fiddling with `HttpClient`.
> > 
> > 
> > good point and should not be a big deal. will try to do it in following prs
> 
> Not necessarily instead, but a simple abstraction layer would allow to use the default http repository or use wagon as an alternative and more versatile provider.

Agree. It could be reworked as we like in the future, just at this point it will be a small cleanup which doesnt have much of implications. also, it was tested, so it will be great to merge it.

Conceptually i agree with more comprehensive rework in future

**Comment by gnodet** [comment]
> > > > I believe that this entire code needs to be rewritten to use Wagon instead of manually fiddling with `HttpClient`.
> > > 
> > > 
> > > good point and should not be a big deal. will try to do it in following prs
> > 
> > 
> > Not necessarily instead, but a simple abstraction layer would allow to use the default http repository or use wagon as an alternative and more versatile provider.
> 
> Agree. It could be reworked as we like in the future, just at this point it will be a small cleanup which doesnt have much of implications. also, it was tested, so it will be great to merge it.
> 
> Conceptually i agree with more comprehensive rework in future

I'm going to merge.  What's the reasoning for using an `Optional ` instead of throwing an exception ?

**Comment by AlexanderAshitkin** [comment]
> I'm going to merge.  What's the reasoning for using an `Optional ` instead of throwing an exception ?

Hi. The rationale is that cache misses are natural. Optionals allow to isolate normal flow from real errors (like transport and format issues) and to avoid flood of not so useful "not found" exceptions. If it is necessary to assert a resource presence it should be done in cache logic by a caller

**Pull request merged**
