### PR TITLE
[MNG-6776] Inconsistent list of parameters for MojoDescriptor (testcase)

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by cstamas** [comment]
Yup, this is wrong, but: these classes are NOT used/mutated at runtime, but are populated from sources (buildtime) and populated from XML (runtime). Still, this leaves a room for improvement. IMO, you can pick up https://github.com/apache/maven/pull/584 and this UT and create a PR.

**Comment by cstamas** [comment]
@slachiewicz could you please push the UT to this PR https://github.com/apache/maven/pull/584 ?

**Comment by cstamas** [comment]
Superseded by https://github.com/apache/maven/pull/584

**Comment by jira-importer** [comment]
Resolve #8491

**Pull request closed without merging**
