### PR TITLE
[MNG-6302] logging the module count

### PR DESCRIPTION
**Pull request by rmannibucau**
Idea is to let the user identify how many modules are still to be executed/processed

### CODE REVIEW

**Comment by michael-o** [comment]
Looks good to me.

**Comment by stephenc** [comment]
👍

**Comment by hboutemy** [comment]
merged as a branch in Maven git https://github.com/apache/maven/tree/MNG-6302_module-progress
and reworked to avoid additional line "Module i/n" but have instead integrated at the end of "Building" line:
```
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache Maven Distribution 3.5.3-SNAPSHOT                [15/15]
[INFO] ------------------------------------------------------------------------
```

**Comment by michael-o** [comment]
@hboutemy Tested your branch. Great improvement to the PR! +1

**Comment by jira-importer** [comment]
Resolve #7563

**Pull request merged**
