### PR TITLE
[MNG-5600] Dependency management import should support exclusions

### PR DESCRIPTION
**Pull request by alex1989hu**
The original patch is made by: Christian Schulte <schulte@apache.org>
@ChristianSchulte

For more information kindly ask you to visit the original pull request  #148

### CODE REVIEW

**Comment by alex1989hu** [comment]
@olamy kind ping

**Comment by michael-o** [comment]
@alex1989hu Is there an IT for that?

**Comment by alex1989hu** [comment]
> @alex1989hu Is there an IT for that?

Yes, it is written in the referenced PR #148 --> [maven-integration-testing/pull/30](https://github.com/apache/maven-integration-testing/pull/30)

**Comment by valdar** [comment]
Any update on this?

**Comment by michael-o** [comment]
Completely forgot. Can someone rebase here?

**Comment by alex1989hu** [comment]
> Completely forgot. Can someone rebase here?

Sure

**Comment by rfscholte** [comment]
IT of github.com/apache/maven-integration-testing/pull/30 needs to be rebased too.

**Comment by alex1989hu** [comment]
> IT of github.com/[apache/maven-integration-testing/pull/30](https://github.com/apache/maven-integration-testing/pull/30) needs to be rebased too.

Rebased here: https://github.com/apache/maven-integration-testing/pull/59

**Comment by michael-o** [comment]
@slachiewicz You have created a branch for this. Do you want to pursue this PR?

**Comment by renatoathaydes** [comment]
Hey, is this feature undesirable for Maven to have? Or is this PR being blocked for other reasons? Either way is fine with me, just wanted to know if there's a reason there's been no activity here in nearly 2 years now.

**Comment by djohle** [comment]
Not to be a "me 2" here, but I ran into this issue today.  But I figured I would at least comment to show my support of including this change.

I was centralizing some repeatedly used dependencies in a multi-module project via dependencyManagement in the parent POM.  These dependencies came with some excludes (fortunately the same one in each usage), so I put those in the parent as well.  Was quite surprised that building my application resulted in 2x the size of the final package and a complete failure to function at all (there is a reason I do these exclusions!).  To work around this I had to re-add the exclusions to each of the relevant modules.

Like the previous comment...I can totally understand if there are reasons for blockage, but those are not apparent.  Looking back to the beginning, this enhancement/fix is over 4 years old now!  Kind of sucks to see an already-solved issues be ignored like this.

**Comment by michael-o** [comment]
@cstamas @gnodet @hboutemy Is this something we can consider for 4? I don't think it would be appropriate for 3.9.0, but it is opt-in only. WDYT?

**Comment by famod** [comment]
@michael-o 

I would very much appreciate if that would end up in 3.9 (as you said it's opt in and only little code is touched).
Otherwise it will be practically unusable for years to come, given that big projects like Quarkus cannot/will not force users to use the latest maven version and Maven 4 adoption _will_ most likely take considerably more time that 3.9.

**Comment by mistriel** [comment]
Also bumped into that issue today, I was kind of shocked that it's not supported OOB. For me it's blocks the creation of parent pom for all microservices that imports `spring-boot-dependencies` (very common) where importing another project bom that has conflict with `spring-boot-dependencies`.  Guy's this is must !

**Comment by JWT007** [comment]
Another +1 "me too"... would really like to see this feature!

**Pull request closed without merging**
