### PR TITLE
[MNG-7220] Fix threadLocalArtifactsHolder leaking into cloned project

### PR DESCRIPTION
**Pull request by famod**
Just like #527 but for `master`.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MNG) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MNG-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MNG-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the [Core IT][core-its] successfully.

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

[core-its]: https://maven.apache.org/core-its/core-it-suite/

### CODE REVIEW

**Comment by rmannibucau** [comment]
This broke 3.8.2 so would be great to invest in another working solution IMHO.

**Comment by olamy** [comment]
why `InheritableThreadLocal` cannot be a good solution? what are the cons using `InheritableThreadLocal`?

**Comment by rmannibucau** [comment]
It mainly leaks and threads it is propagated to are uncontrolled so behavior is.
Guess a reference counting (per module) or alike solution is maybe closer to something portable, and enabling it only in concurrent builds is saner and limit the impacts a lot.

**Comment by famod** [comment]
My 2 cents:
In mid or long term there should be a better solution for this and the band-aid TL should be dropped.
But so far nobody has come up with a non-api-breaking solution to fix the initial problem. Just reverting the TL re-introduces a nasty concurrency issue, so IMO this is not a good option.
So, since 3.8.2 is out there and introduces some regressions, let's get the two fixes for that merged and release 3.8.3 ASAP.

**Comment by rmannibucau** [comment]
@famod so minimum is to disable the TL when concurrency = 1 which leads to 0 issues for everyone - even if build is slower. Guess it is acceptable until somebody wants to implement a ref counting or alike solution.

**Comment by michael-o** [comment]
> 
> 
> @famod so minimum is to disable the TL when concurrency = 1 which leads to 0 issues for everyone - even if build is slower. Guess it is acceptable until somebody wants to implement a ref counting or alike solution.

If we can access concurrency information at that point actually...

**Review by michael-o — APPROVED** [review]

**Comment by michael-o** [comment]
Will also test in the next couple of days and merge.

**Comment by famod** [comment]
> > @famod so minimum is to disable the TL when concurrency = 1 which leads to 0 issues for everyone - even if build is slower. Guess it is acceptable until somebody wants to implement a ref counting or alike solution.
> 
> If we can access concurrency information at that point actually...

I don't see how, unfortunately. (not without adding new public methods to MavenProject that have to be called from..._somewhere_)

**Comment by rmannibucau** [comment]
The concurrency is in the session (`session.getRequest().getDegreeOfConcurrency();` or something like that) so I guess it is more a matter of wrapper the project injected in mojo instead of changing maven project itself. So maven project would stay untouched and a ConcurrentMavenProject would use a thread local if getDegreeOfConcurrency() > 1.
Had sometihng along those lines in mind but I wouldn't change MavenProject at all.

**Comment by michael-o** [comment]
> The concurrency is in the session (`session.getRequest().getDegreeOfConcurrency();` or something like that) so I guess it is more a matter of wrapper the project injected in mojo instead of changing maven project itself. So maven project would stay untouched and a ConcurrentMavenProject would use a thread local if getDegreeOfConcurrency() > 1.
> Had sometihng along those lines in mind but I wouldn't change MavenProject at all.

This makes sense and should be evaluated in a separate issue.

**Comment by jira-importer** [comment]
Resolve #8248

**Pull request closed without merging**
