### PR TITLE
[MNG-8461] Initial settings method must restore context state

### PR DESCRIPTION
**Pull request by cstamas**
Effective settings are (should be) created twice, once for "early boot" of Plexus when extensions are loaded up, and then again when Maven "boots".

Bug was that early call "corrupted" (inited settings) in context causing that 2nd required call (due spy) was omitted. This resulted in lack of settings related spy events firing (as we do have IT for spy but it does not test settings events).

---

https://issues.apache.org/jira/browse/MNG-8461

Related: https://github.com/alextu/maven4-reproducer/issues/1

### CODE REVIEW

**Comment by cstamas** [comment]
I think we can... but am now looking at MavenITmng4936EventSpyTest and it seems it does test for this thing but did not fail?

**Comment by cstamas** [comment]
So, we need to dig in, why reproducer fails, and why IT succeeds. Locally running the related IT I have this (mng-4936/target/spy.log):

fixed: Apache Maven 4.0.0-rc-3-SNAPSHOT (a9f6f3b71d21542869f635c197dc8076583937f1)
```
init
event: org.apache.maven.api.services.SettingsBuilderRequest$SettingsBuilderRequestBuilder$DefaultSettingsBuilderRequest
event: org.apache.maven.internal.impl.DefaultSettingsBuilder$DefaultSettingsBuilderResult
event: org.apache.maven.api.services.ToolchainsBuilderRequest$ToolchainsBuilderRequestBuilder$DefaultToolchainsBuilderRequest
event: org.apache.maven.internal.impl.DefaultToolchainsBuilder$DefaultToolchainsBuilderResult
event: org.apache.maven.execution.DefaultMavenExecutionRequest
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.execution.DefaultMavenExecutionResult
close
```

master: Apache Maven 4.0.0-rc-3-SNAPSHOT (575ad3719c79b061c78d531ec9d29793f159c2ec)
```
init
event: org.apache.maven.api.services.SettingsBuilderRequest$SettingsBuilderRequestBuilder$DefaultSettingsBuilderRequest
event: org.apache.maven.internal.impl.DefaultSettingsBuilder$DefaultSettingsBuilderResult
event: org.apache.maven.api.services.ToolchainsBuilderRequest$ToolchainsBuilderRequestBuilder$DefaultToolchainsBuilderRequest
event: org.apache.maven.internal.impl.DefaultToolchainsBuilder$DefaultToolchainsBuilderResult
event: org.apache.maven.execution.DefaultMavenExecutionRequest
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.lifecycle.internal.DefaultExecutionEvent
event: org.apache.maven.execution.DefaultMavenExecutionResult
close
```

Basically they are same.

**Comment by cstamas** [comment]
Still cannot figure, and I starting to doubt in our ITs... The only difference I found so far:
* reproducer uses `.mvn/extensions.xml` to load up spy listener
* IT uses `-Dmaven.ext.class.path=spy-0.1.jar` so it is much earlier already present in system

Still, as the code change shows, the event should not be emitted, but it seems it was? Checked also, the IT is forked, and forked executor is used, so it cannot be some "leftover"...

**Comment by jira-importer** [comment]
Resolve #9394

**Pull request merged**
